// Code generated by mockery v2.53.6. DO NOT EDIT.

package weather

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWeatherRepository is an autogenerated mock type for the WeatherRepository type
type MockWeatherRepository struct {
	mock.Mock
}

type MockWeatherRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWeatherRepository) EXPECT() *MockWeatherRepository_Expecter {
	return &MockWeatherRepository_Expecter{mock: &_m.Mock}
}

// ListAll provides a mock function with given fields: ctx
func (_m *MockWeatherRepository) ListAll(ctx context.Context) ([]WeatherRecord, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []WeatherRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]WeatherRecord, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []WeatherRecord); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]WeatherRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWeatherRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockWeatherRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWeatherRepository_Expecter) ListAll(ctx interface{}) *MockWeatherRepository_ListAll_Call {
	return &MockWeatherRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockWeatherRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockWeatherRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWeatherRepository_ListAll_Call) Return(_a0 []WeatherRecord, _a1 error) *MockWeatherRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWeatherRepository_ListAll_Call) RunAndReturn(run func(context.Context) ([]WeatherRecord, error)) *MockWeatherRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListByLocation provides a mock function with given fields: ctx, location
func (_m *MockWeatherRepository) ListByLocation(ctx context.Context, location string) ([]WeatherRecord, error) {
	ret := _m.Called(ctx, location)

	if len(ret) == 0 {
		panic("no return value specified for ListByLocation")
	}

	var r0 []WeatherRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]WeatherRecord, error)); ok {
		return rf(ctx, location)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []WeatherRecord); ok {
		r0 = rf(ctx, location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]WeatherRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWeatherRepository_ListByLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByLocation'
type MockWeatherRepository_ListByLocation_Call struct {
	*mock.Call
}

// ListByLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - location string
func (_e *MockWeatherRepository_Expecter) ListByLocation(ctx interface{}, location interface{}) *MockWeatherRepository_ListByLocation_Call {
	return &MockWeatherRepository_ListByLocation_Call{Call: _e.mock.On("ListByLocation", ctx, location)}
}

func (_c *MockWeatherRepository_ListByLocation_Call) Run(run func(ctx context.Context, location string)) *MockWeatherRepository_ListByLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWeatherRepository_ListByLocation_Call) Return(_a0 []WeatherRecord, _a1 error) *MockWeatherRepository_ListByLocation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWeatherRepository_ListByLocation_Call) RunAndReturn(run func(context.Context, string) ([]WeatherRecord, error)) *MockWeatherRepository_ListByLocation_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceAll provides a mock function with given fields: ctx, records
func (_m *MockWeatherRepository) ReplaceAll(ctx context.Context, records []WeatherRecord) error {
	ret := _m.Called(ctx, records)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []WeatherRecord) error); ok {
		r0 = rf(ctx, records)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWeatherRepository_ReplaceAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceAll'
type MockWeatherRepository_ReplaceAll_Call struct {
	*mock.Call
}

// ReplaceAll is a helper method to define mock.On call
//   - ctx context.Context
//   - records []WeatherRecord
func (_e *MockWeatherRepository_Expecter) ReplaceAll(ctx interface{}, records interface{}) *MockWeatherRepository_ReplaceAll_Call {
	return &MockWeatherRepository_ReplaceAll_Call{Call: _e.mock.On("ReplaceAll", ctx, records)}
}

func (_c *MockWeatherRepository_ReplaceAll_Call) Run(run func(ctx context.Context, records []WeatherRecord)) *MockWeatherRepository_ReplaceAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]WeatherRecord))
	})
	return _c
}

func (_c *MockWeatherRepository_ReplaceAll_Call) Return(_a0 error) *MockWeatherRepository_ReplaceAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWeatherRepository_ReplaceAll_Call) RunAndReturn(run func(context.Context, []WeatherRecord) error) *MockWeatherRepository_ReplaceAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWeatherRepository creates a new instance of MockWeatherRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWeatherRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWeatherRepository {
	mock := &MockWeatherRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
