// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AddMemberRequest defines model for AddMemberRequest.
type AddMemberRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// Token JWT Access Token
	Token string `json:"token"`
	User  User   `json:"user"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// ItineraryItem defines model for ItineraryItem.
type ItineraryItem struct {
	ActualTime  *time.Time `json:"actual_time,omitempty"`
	Altitude    int        `json:"altitude"`
	CheckedInAt *time.Time `json:"checked_in_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	Day         string     `json:"day"`
	Distance    float64    `json:"distance"`

	// EstTime 預計時間 HH:MM
	EstTime     string             `json:"est_time"`
	Id          openapi_types.UUID `json:"id"`
	ImageAsset  *string            `json:"image_asset,omitempty"`
	IsCheckedIn bool               `json:"is_checked_in"`
	Name        string             `json:"name"`
	Note        string             `json:"note"`
	TripId      openapi_types.UUID `json:"trip_id"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// ItineraryItemRequest defines model for ItineraryItemRequest.
type ItineraryItemRequest struct {
	Altitude   *int     `json:"altitude,omitempty"`
	Day        string   `json:"day"`
	Distance   *float64 `json:"distance,omitempty"`
	EstTime    string   `json:"est_time"`
	ImageAsset *string  `json:"image_asset,omitempty"`
	Name       string   `json:"name"`
	Note       *string  `json:"note,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// Trip defines model for Trip.
type Trip struct {
	CoverImage  *string             `json:"cover_image,omitempty"`
	CreatedAt   time.Time           `json:"created_at"`
	DayNames    []string            `json:"day_names"`
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	Id          openapi_types.UUID  `json:"id"`
	IsActive    bool                `json:"is_active"`
	Name        string              `json:"name"`
	StartDate   openapi_types.Date  `json:"start_date"`
	UpdatedAt   time.Time           `json:"updated_at"`

	// UserId 建立此行程的使用者 ID
	UserId openapi_types.UUID `json:"user_id"`
}

// TripCreateRequest defines model for TripCreateRequest.
type TripCreateRequest struct {
	CoverImage  *string             `json:"cover_image,omitempty"`
	DayNames    *[]string           `json:"day_names,omitempty"`
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	Name        string              `json:"name"`
	StartDate   openapi_types.Date  `json:"start_date"`
}

// TripMember defines model for TripMember.
type TripMember struct {
	JoinedAt     time.Time          `json:"joined_at"`
	TripId       openapi_types.UUID `json:"trip_id"`
	UserId       openapi_types.UUID `json:"user_id"`
	UserMetadata User               `json:"user_metadata"`
}

// TripUpdateRequest defines model for TripUpdateRequest.
type TripUpdateRequest struct {
	CoverImage  *string             `json:"cover_image,omitempty"`
	DayNames    *[]string           `json:"day_names,omitempty"`
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	IsActive    *bool               `json:"is_active,omitempty"`
	Name        *string             `json:"name,omitempty"`
	StartDate   *openapi_types.Date `json:"start_date,omitempty"`
}

// User defines model for User.
type User struct {
	Avatar      string              `json:"avatar"`
	CreatedAt   time.Time           `json:"created_at"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	IsActive    bool                `json:"is_active"`
	IsVerified  bool                `json:"is_verified"`

	// Role 使用者角色代碼 (e.g. ADMIN, LEADER, MEMBER)
	Role string `json:"role"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateTripJSONRequestBody defines body for CreateTrip for application/json ContentType.
type CreateTripJSONRequestBody = TripCreateRequest

// UpdateTripJSONRequestBody defines body for UpdateTrip for application/json ContentType.
type UpdateTripJSONRequestBody = TripUpdateRequest

// AddItineraryItemJSONRequestBody defines body for AddItineraryItem for application/json ContentType.
type AddItineraryItemJSONRequestBody = ItineraryItemRequest

// UpdateItineraryItemJSONRequestBody defines body for UpdateItineraryItem for application/json ContentType.
type UpdateItineraryItemJSONRequestBody = ItineraryItemRequest

// AddTripMemberJSONRequestBody defines body for AddTripMember for application/json ContentType.
type AddTripMemberJSONRequestBody = AddMemberRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// User Login
	// (POST /auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Get Current User Profile
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// User Registration
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// Health Check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List Trips
	// (GET /trips)
	ListTrips(w http.ResponseWriter, r *http.Request)
	// Create Trip
	// (POST /trips)
	CreateTrip(w http.ResponseWriter, r *http.Request)
	// Delete Trip
	// (DELETE /trips/{tripId})
	DeleteTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Get Trip
	// (GET /trips/{tripId})
	GetTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Update Trip
	// (PUT /trips/{tripId})
	UpdateTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// List Itinerary
	// (GET /trips/{tripId}/itinerary)
	ListItinerary(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Add Itinerary Item
	// (POST /trips/{tripId}/itinerary)
	AddItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Delete Itinerary Item
	// (DELETE /trips/{tripId}/itinerary/{itemId})
	DeleteItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// Update Itinerary Item
	// (PUT /trips/{tripId}/itinerary/{itemId})
	UpdateItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// List Trip Members
	// (GET /trips/{tripId}/members)
	ListTripMembers(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Add Trip Member
	// (POST /trips/{tripId}/members)
	AddTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Remove Trip Member
	// (DELETE /trips/{tripId}/members/{userId})
	RemoveTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, userId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// User Login
// (POST /auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Current User Profile
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User Registration
// (POST /auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health Check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Trips
// (GET /trips)
func (_ Unimplemented) ListTrips(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Trip
// (POST /trips)
func (_ Unimplemented) CreateTrip(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Trip
// (DELETE /trips/{tripId})
func (_ Unimplemented) DeleteTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Trip
// (GET /trips/{tripId})
func (_ Unimplemented) GetTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Trip
// (PUT /trips/{tripId})
func (_ Unimplemented) UpdateTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Itinerary
// (GET /trips/{tripId}/itinerary)
func (_ Unimplemented) ListItinerary(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Itinerary Item
// (POST /trips/{tripId}/itinerary)
func (_ Unimplemented) AddItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Itinerary Item
// (DELETE /trips/{tripId}/itinerary/{itemId})
func (_ Unimplemented) DeleteItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Itinerary Item
// (PUT /trips/{tripId}/itinerary/{itemId})
func (_ Unimplemented) UpdateItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Trip Members
// (GET /trips/{tripId}/members)
func (_ Unimplemented) ListTripMembers(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Trip Member
// (POST /trips/{tripId}/members)
func (_ Unimplemented) AddTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove Trip Member
// (DELETE /trips/{tripId}/members/{userId})
func (_ Unimplemented) RemoveTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, userId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTrips operation middleware
func (siw *ServerInterfaceWrapper) ListTrips(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrips(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTrip operation middleware
func (siw *ServerInterfaceWrapper) CreateTrip(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrip(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrip operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrip operation middleware
func (siw *ServerInterfaceWrapper) GetTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTrip operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItinerary operation middleware
func (siw *ServerInterfaceWrapper) ListItinerary(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItinerary(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddItineraryItem operation middleware
func (siw *ServerInterfaceWrapper) AddItineraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddItineraryItem(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItineraryItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItineraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItineraryItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItineraryItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItineraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItineraryItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTripMembers operation middleware
func (siw *ServerInterfaceWrapper) ListTripMembers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTripMembers(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTripMember operation middleware
func (siw *ServerInterfaceWrapper) AddTripMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTripMember(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveTripMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveTripMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveTripMember(w, r, tripId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips", wrapper.ListTrips)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips", wrapper.CreateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}", wrapper.DeleteTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}", wrapper.GetTrip)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/trips/{tripId}", wrapper.UpdateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/itinerary", wrapper.ListItinerary)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/itinerary", wrapper.AddItineraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/itinerary/{itemId}", wrapper.DeleteItineraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/trips/{tripId}/itinerary/{itemId}", wrapper.UpdateItineraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/members", wrapper.ListTripMembers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/members", wrapper.AddTripMember)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/members/{userId}", wrapper.RemoveTripMember)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xab1PbyB3+Khr1XoQZg01y7aR+0+ESeiETOjeETF5Q17OxFluJ9ed2V/Qo9UxKycVA",
	"UtKm8UGOJoHLHwKlkHC9cIHQL4Nk86pfobO7ki1ZEpYAm+ZeYaTV7m+f5/k9+9uVJsScpuiaClWCxfSE",
	"iHMFqAD2s0+SBqFyA6Ih+KUBMaHXdKTpEBEZshZQAXKR/hjVkAKImLavJEQyrkMxLWKCZDUvlkoJEcEv",
	"DRlBSUyP2K0y9WbajZswR8RSQuwzSGEIYl1TMfSPR7RbUKU/JIhzSNaJrKliWrx8fVjoy+UgxsIwa+Eb",
	"PyEaGCL65CcIjopp8WfJxrST9pyT12ib5liJ3SPrICjkfoQ0FB6zAjEGeXYDfgUUvUifttafC/0UBMF8",
	"97b6w8Pa8lptZcf8eqYldE53QZFcgqB4GHyYAGJgbyTarSC0xiDCDFt301RPb0+qZYD2II0+giIdILIK",
	"EUDjAwQq/kBBjhigmCWyAj3qkgCB3exqQlSNYhHcoIERZMCAOYAikYkhsR7sm7JKYJ5ynBBzBZi7BaWs",
	"rGYBOfogOQQBgdJhffiekcC4KybXdRkToOaapqwZdPx6N6pBM5I2h5jUEfLmw8GzB7WVsrUweVB5KFy6",
	"lB4cFBOiDgiBiN7+3ZmRVHdv5lcjqe5fZv54diTVfS7TlR5Jdf88wy59EhS0LHnCMgxZCmymgDzMAowh",
	"A6QlfjLONphwoXJD04oQqLSJChQYiJeqkeAbBMl6NmLAhi7FJLBJ77xbe0ROrh2ziyKXGl0821NoRsGj",
	"Kk+ELVMp1KkPT4Y2KPK4cvPqyM99TFE0kRbMUhC8V7S8rB5/AaT5h/HvNeRVZf1itBXT1UtQrEMwL2Ny",
	"yHotyVgvgvGsg54iq1egmicFMX02IOQTnJ1rpPOx55rwBh409WEk6/755rQxiLJMS5Hc6IhuzsJiA8oE",
	"KjjYk/gFgBAYZ4+5HTtCaFCVsjQOX2BRVqmo5o2zIEfkMRjTiDEBiIRGdwKWy6sv29K9a5258766Nmut",
	"P68t3auuzFYfT+1/+E/17yu123eEgYtiotWsg9zcGazuEK4JulFykx/PtKlcL7D2obnapN026S6WzkJd",
	"WAFf1X0klfJke2/imHppIsjPSBi+fO/iB/amJqsx1ReroGgoNVpbBRIgAQKOtjupFx4N0TYm2DxCGFTX",
	"mFo/ailG9K42K9WH7jUcJEEwBghAgZM+0hLUtKwfZyE/maVCxtkxiORRGUrBDZBWDNi41K279upvtem3",
	"+zvfVZd3hTOwJ98j9F0cHPhNQrjS33exfyghDPYPftY/1BXN0J3ZeoBKODR4Ld0duh2nhxV/DlGdwJyB",
	"ZDJ+leYq5/gGBAiiPoNKy/nv1w6sl68PUxNjrSkw7G5jLgVCdLFEO5bVUY2noEpAju+pGMviVUNRZDJI",
	"ldicS6I5P23N/8X6sVJd2DHfvOFLoznz2pqeFboFc+9edW1D6PtigI4ok6K3O/tG/QjA3veXEqKmQxXo",
	"spgWz/Wkes7xTWWBzTYJDFJIFmmxzOSucR/xhkWjufNif/ulOVcx974RLl8frh/Y0PQAtN2AJKZ51c1y",
	"h7MJMflMk8YdJKDKege6XpRz7KnkTcxdhLtlKy/1VPUlr2ZoDcUu8GMUNr2zqdSJje054mJjB6FklR+Y",
	"M08p6p+mek9sbO9ZVcDg5vZWbeGpVa6YG19Xl3cP7m3UVp9ziRuKAtC4mGaeJjAEqX5AHtM8o/yLGdqQ",
	"S4E7UR4GyICzX330gzl935aEk/fVx1O1rbtWZcGniM8huWAgBFVSl0Wb+LHXWR80nBEevB1kp9mxFlcd",
	"dVR45gjVqSXrUdljQmJ6xGs/I5lSxk3g55AINpgCI/MLpI3KfE8fQieyt5bhyc3PL63KZp1MriUfk84u",
	"tY3p3bwRjpThvR3LcBsqV4anOqchLhiaaGuz1ptJ4cz+3qz5ctI+jrae7Zq7czztqQu8e2uuz5uLK11B",
	"HsBh5tQGa6fATqRDncBaXbaevqALjmAt3jdnF6z5DfPBS2v9O3N7++BPs/sfFoOMgJ9zt9MDmk7SA1OR",
	"xcsibcKGPyxcKMDcLRcseBwTqNjA0Lodt3BIq/xXe3dbrpgzz8w7LyhrfC0vf1NbWvEvmzImw6znY2JT",
	"L+IPA4mdufjq+oA15dsn5uSWJ/BTM854RknxFBxAHR45dZlSIsQIbc4qm3zGPpL4vp+B1x738x8udNj/",
	"uDBCV1CGjw1Op93PnPuz9WjbKWvqKjwRtXDMBZvZZrnUsz45Qf8MSCU+cBGSgJ2QWV49WHgeoqCL7CF7",
	"HB0goEACEWYB0vqbleXO6VVa5MOJzQpIuDBtdUiW8anl0wDYOL0s8ijY0hbnAnYJU0vWP2cOFh7wnoQz",
	"5tyqtThtTv/b3HlPy4q5DX6ni3cREAnHbX/7Pl+84tHI0Q2jMXFoTTv9o/mvx3z02uut6veb4dXs6dKX",
	"6lCyn4gO1ufNuUp7yKalcCjTuhFUs3z7fd3bQ9jlx2kdJ7g9K4n3bLDDe+VQcTESTk5ivL/2SIwDGH1Z",
	"SMrOG90W9aGtwZA6sP5e+GMxmUg1p/fDkZjFZ21ppbpx+2DnibsKjeI8sWtGN/hR60arsmkuP2mK1Edt",
	"nyR5Mfi4HSbw64UOl6tNmgpbyjg/roq1VWV5mLKq71ZquxvxlNUnSQ1hCTb5cfwkOUFzLEblGS5DXiSd",
	"ihITgR3zmZ1GkRuF5pB1xZreo4tKebP2+q0N9FFK1ZaiiFLKhFLN16+fINX/T26W6qCb+WqnU1SwXRwd",
	"xdYU9n4fRyqS6GwfLrU4NRu0O/wp1UuuDyEiF0sesNpXI9HQhAbm8cokJ0bbvYQz+zsvBPaaV9j/sFid",
	"fH8webu2Nru/9w/r4eOuoCrKhczHXUL5PtM/hdM+R2KhZ37s+JqTFlpBNd4CTi1ZW4/4M877Cf6dvDW/",
	"wTv57+49q1xxGHc2Zl0Rdnou+cQvv1yajWVSyQkDQ9Sq8tq8y+Oqvtox774POfwbgoo2Bjuv3uC1mE+r",
	"U2VX9dVOtLKLtXPLrcXSxZta5YpzLB1HGJyRVtpgPaIxhyRvLFe0HCgKEhyDRU1XaEomRAMV7U9B0slk",
	"kTYoaJikz6fOp5JAl5NjvSKNwx6oucer7G2TUNcObnBmv4iijHqfodODKrFtQPitkUqd/YVAr2pI/oPz",
	"ms/uhb3l8/fBUQAqyEN7Hi4JYrGUKf0vAAD//2l+7BByNAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
