// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AddMemberRequest defines model for AddMemberRequest.
type AddMemberRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// Token JWT Access Token
	Token string `json:"token"`
	User  User   `json:"user"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// Favorite defines model for Favorite.
type Favorite struct {
	CreatedAt time.Time          `json:"created_at"`
	CreatedBy openapi_types.UUID `json:"created_by"`
	Id        openapi_types.UUID `json:"id"`
	TargetId  openapi_types.UUID `json:"target_id"`
	Type      string             `json:"type"`
	UpdatedAt time.Time          `json:"updated_at"`
	UpdatedBy openapi_types.UUID `json:"updated_by"`
}

// FavoriteRequest defines model for FavoriteRequest.
type FavoriteRequest struct {
	TargetId openapi_types.UUID `json:"target_id"`
	Type     string             `json:"type"`
}

// GearLibraryItem defines model for GearLibraryItem.
type GearLibraryItem struct {
	Category   string             `json:"category"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	IsArchived bool               `json:"is_archived"`
	Name       string             `json:"name"`
	Notes      *string            `json:"notes,omitempty"`
	UpdatedAt  time.Time          `json:"updated_at"`
	UserId     openapi_types.UUID `json:"user_id"`
	Weight     float64            `json:"weight"`
}

// GearLibraryItemRequest defines model for GearLibraryItemRequest.
type GearLibraryItemRequest struct {
	Category   string  `json:"category"`
	IsArchived *bool   `json:"is_archived,omitempty"`
	Name       string  `json:"name"`
	Notes      *string `json:"notes,omitempty"`
	Weight     float64 `json:"weight"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// ItineraryItem defines model for ItineraryItem.
type ItineraryItem struct {
	ActualTime  *time.Time `json:"actual_time,omitempty"`
	Altitude    int        `json:"altitude"`
	CheckedInAt *time.Time `json:"checked_in_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	Day         string     `json:"day"`
	Distance    float64    `json:"distance"`

	// EstTime 預計時間 HH:MM
	EstTime     string             `json:"est_time"`
	Id          openapi_types.UUID `json:"id"`
	ImageAsset  *string            `json:"image_asset,omitempty"`
	IsCheckedIn bool               `json:"is_checked_in"`
	Name        string             `json:"name"`
	Note        string             `json:"note"`
	TripId      openapi_types.UUID `json:"trip_id"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// ItineraryItemRequest defines model for ItineraryItemRequest.
type ItineraryItemRequest struct {
	Altitude   *int     `json:"altitude,omitempty"`
	Day        string   `json:"day"`
	Distance   *float64 `json:"distance,omitempty"`
	EstTime    string   `json:"est_time"`
	ImageAsset *string  `json:"image_asset,omitempty"`
	Name       string   `json:"name"`
	Note       *string  `json:"note,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MealLibraryItem defines model for MealLibraryItem.
type MealLibraryItem struct {
	Calories   float64            `json:"calories"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	IsArchived bool               `json:"is_archived"`
	Name       string             `json:"name"`
	Notes      *string            `json:"notes,omitempty"`
	UpdatedAt  time.Time          `json:"updated_at"`
	UserId     openapi_types.UUID `json:"user_id"`
	Weight     float64            `json:"weight"`
}

// MealLibraryItemRequest defines model for MealLibraryItemRequest.
type MealLibraryItemRequest struct {
	Calories   float64 `json:"calories"`
	IsArchived *bool   `json:"is_archived,omitempty"`
	Name       string  `json:"name"`
	Notes      *string `json:"notes,omitempty"`
	Weight     float64 `json:"weight"`
}

// Message defines model for Message.
type Message struct {
	Avatar      *string             `json:"avatar,omitempty"`
	Category    string              `json:"category"`
	Content     string              `json:"content"`
	CreatedAt   time.Time           `json:"created_at"`
	DisplayName string              `json:"display_name"`
	Id          openapi_types.UUID  `json:"id"`
	ParentId    *openapi_types.UUID `json:"parent_id,omitempty"`
	Replies     *[]Message          `json:"replies,omitempty"`
	Timestamp   time.Time           `json:"timestamp"`
	TripId      openapi_types.UUID  `json:"trip_id"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
	UserId      openapi_types.UUID  `json:"user_id"`
}

// MessageRequest defines model for MessageRequest.
type MessageRequest struct {
	Category *string             `json:"category,omitempty"`
	Content  string              `json:"content"`
	ParentId *openapi_types.UUID `json:"parent_id,omitempty"`
}

// Poll defines model for Poll.
type Poll struct {
	AllowMultipleVotes bool               `json:"allow_multiple_votes"`
	CreatedAt          time.Time          `json:"created_at"`
	CreatedBy          openapi_types.UUID `json:"created_by"`
	Deadline           *time.Time         `json:"deadline,omitempty"`
	Description        string             `json:"description"`
	Id                 openapi_types.UUID `json:"id"`
	IsAllowAddOption   bool               `json:"is_allow_add_option"`
	MaxOptionLimit     int                `json:"max_option_limit"`
	Options            []PollOption       `json:"options"`
	ResultDisplayType  string             `json:"result_display_type"`
	Status             string             `json:"status"`
	Title              string             `json:"title"`
	TripId             openapi_types.UUID `json:"trip_id"`
	UpdatedAt          time.Time          `json:"updated_at"`
	UpdatedBy          openapi_types.UUID `json:"updated_by"`
}

// PollOption defines model for PollOption.
type PollOption struct {
	CreatedAt time.Time             `json:"created_at"`
	CreatedBy openapi_types.UUID    `json:"created_by"`
	Id        openapi_types.UUID    `json:"id"`
	PollId    openapi_types.UUID    `json:"poll_id"`
	Text      string                `json:"text"`
	UpdatedAt time.Time             `json:"updated_at"`
	UpdatedBy openapi_types.UUID    `json:"updated_by"`
	VoteCount int                   `json:"vote_count"`
	Voters    *[]openapi_types.UUID `json:"voters,omitempty"`
}

// PollOptionRequest defines model for PollOptionRequest.
type PollOptionRequest struct {
	Text string `json:"text"`
}

// PollRequest defines model for PollRequest.
type PollRequest struct {
	AllowMultipleVotes *bool      `json:"allow_multiple_votes,omitempty"`
	Deadline           *time.Time `json:"deadline,omitempty"`
	Description        string     `json:"description"`
	IsAllowAddOption   *bool      `json:"is_allow_add_option,omitempty"`
	MaxOptionLimit     *int       `json:"max_option_limit,omitempty"`
	ResultDisplayType  *string    `json:"result_display_type,omitempty"`
	Title              string     `json:"title"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// Trip defines model for Trip.
type Trip struct {
	CoverImage  *string             `json:"cover_image,omitempty"`
	CreatedAt   time.Time           `json:"created_at"`
	DayNames    []string            `json:"day_names"`
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	Id          openapi_types.UUID  `json:"id"`
	IsActive    bool                `json:"is_active"`
	Name        string              `json:"name"`
	StartDate   openapi_types.Date  `json:"start_date"`
	UpdatedAt   time.Time           `json:"updated_at"`

	// UserId 建立此行程的使用者 ID
	UserId openapi_types.UUID `json:"user_id"`
}

// TripCreateRequest defines model for TripCreateRequest.
type TripCreateRequest struct {
	CoverImage  *string             `json:"cover_image,omitempty"`
	DayNames    *[]string           `json:"day_names,omitempty"`
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	Name        string              `json:"name"`
	StartDate   openapi_types.Date  `json:"start_date"`
}

// TripGearItem defines model for TripGearItem.
type TripGearItem struct {
	Category      string              `json:"category"`
	CreatedAt     time.Time           `json:"created_at"`
	Id            openapi_types.UUID  `json:"id"`
	IsChecked     bool                `json:"is_checked"`
	LibraryItemId *openapi_types.UUID `json:"library_item_id,omitempty"`
	Name          string              `json:"name"`
	OrderIndex    *int                `json:"order_index,omitempty"`
	Quantity      int                 `json:"quantity"`
	TripId        openapi_types.UUID  `json:"trip_id"`
	UpdatedAt     time.Time           `json:"updated_at"`
	Weight        float64             `json:"weight"`
}

// TripGearItemRequest defines model for TripGearItemRequest.
type TripGearItemRequest struct {
	Category      string              `json:"category"`
	IsChecked     *bool               `json:"is_checked,omitempty"`
	LibraryItemId *openapi_types.UUID `json:"library_item_id,omitempty"`
	Name          string              `json:"name"`
	OrderIndex    *int                `json:"order_index,omitempty"`
	Quantity      *int                `json:"quantity,omitempty"`
	Weight        float64             `json:"weight"`
}

// TripMealItem defines model for TripMealItem.
type TripMealItem struct {
	Calories      float64             `json:"calories"`
	CreatedAt     time.Time           `json:"created_at"`
	Day           string              `json:"day"`
	Id            openapi_types.UUID  `json:"id"`
	LibraryItemId *openapi_types.UUID `json:"library_item_id,omitempty"`
	MealType      string              `json:"meal_type"`
	Name          string              `json:"name"`
	Note          *string             `json:"note,omitempty"`
	Quantity      int                 `json:"quantity"`
	TripId        openapi_types.UUID  `json:"trip_id"`
	UpdatedAt     time.Time           `json:"updated_at"`
	Weight        float64             `json:"weight"`
}

// TripMealItemRequest defines model for TripMealItemRequest.
type TripMealItemRequest struct {
	Calories      float64             `json:"calories"`
	Day           string              `json:"day"`
	LibraryItemId *openapi_types.UUID `json:"library_item_id,omitempty"`
	MealType      string              `json:"meal_type"`
	Name          string              `json:"name"`
	Note          *string             `json:"note,omitempty"`
	Quantity      *int                `json:"quantity,omitempty"`
	Weight        float64             `json:"weight"`
}

// TripMember defines model for TripMember.
type TripMember struct {
	JoinedAt     time.Time          `json:"joined_at"`
	TripId       openapi_types.UUID `json:"trip_id"`
	UserId       openapi_types.UUID `json:"user_id"`
	UserMetadata User               `json:"user_metadata"`
}

// TripUpdateRequest defines model for TripUpdateRequest.
type TripUpdateRequest struct {
	CoverImage  *string             `json:"cover_image,omitempty"`
	DayNames    *[]string           `json:"day_names,omitempty"`
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	IsActive    *bool               `json:"is_active,omitempty"`
	Name        *string             `json:"name,omitempty"`
	StartDate   *openapi_types.Date `json:"start_date,omitempty"`
}

// User defines model for User.
type User struct {
	Avatar      string              `json:"avatar"`
	CreatedAt   time.Time           `json:"created_at"`
	CreatedBy   *openapi_types.UUID `json:"created_by"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	IsActive    bool                `json:"is_active"`
	IsVerified  bool                `json:"is_verified"`

	// Role 使用者角色代碼 (e.g. ADMIN, LEADER, MEMBER)
	Role      string              `json:"role"`
	UpdatedAt time.Time           `json:"updated_at"`
	UpdatedBy *openapi_types.UUID `json:"updated_by"`
}

// ListGearLibraryParams defines parameters for ListGearLibrary.
type ListGearLibraryParams struct {
	IncludeArchived *bool `form:"include_archived,omitempty" json:"include_archived,omitempty"`
}

// ListMealLibraryParams defines parameters for ListMealLibrary.
type ListMealLibraryParams struct {
	IncludeArchived *bool `form:"include_archived,omitempty" json:"include_archived,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// AddFavoriteJSONRequestBody defines body for AddFavorite for application/json ContentType.
type AddFavoriteJSONRequestBody = FavoriteRequest

// CreateGearLibraryItemJSONRequestBody defines body for CreateGearLibraryItem for application/json ContentType.
type CreateGearLibraryItemJSONRequestBody = GearLibraryItemRequest

// UpdateGearLibraryItemJSONRequestBody defines body for UpdateGearLibraryItem for application/json ContentType.
type UpdateGearLibraryItemJSONRequestBody = GearLibraryItemRequest

// CreateMealLibraryItemJSONRequestBody defines body for CreateMealLibraryItem for application/json ContentType.
type CreateMealLibraryItemJSONRequestBody = MealLibraryItemRequest

// UpdateMealLibraryItemJSONRequestBody defines body for UpdateMealLibraryItem for application/json ContentType.
type UpdateMealLibraryItemJSONRequestBody = MealLibraryItemRequest

// CreateTripJSONRequestBody defines body for CreateTrip for application/json ContentType.
type CreateTripJSONRequestBody = TripCreateRequest

// UpdateTripJSONRequestBody defines body for UpdateTrip for application/json ContentType.
type UpdateTripJSONRequestBody = TripUpdateRequest

// AddTripGearItemJSONRequestBody defines body for AddTripGearItem for application/json ContentType.
type AddTripGearItemJSONRequestBody = TripGearItemRequest

// UpdateTripGearItemJSONRequestBody defines body for UpdateTripGearItem for application/json ContentType.
type UpdateTripGearItemJSONRequestBody = TripGearItemRequest

// AddItineraryItemJSONRequestBody defines body for AddItineraryItem for application/json ContentType.
type AddItineraryItemJSONRequestBody = ItineraryItemRequest

// UpdateItineraryItemJSONRequestBody defines body for UpdateItineraryItem for application/json ContentType.
type UpdateItineraryItemJSONRequestBody = ItineraryItemRequest

// AddTripMealItemJSONRequestBody defines body for AddTripMealItem for application/json ContentType.
type AddTripMealItemJSONRequestBody = TripMealItemRequest

// UpdateTripMealItemJSONRequestBody defines body for UpdateTripMealItem for application/json ContentType.
type UpdateTripMealItemJSONRequestBody = TripMealItemRequest

// AddTripMemberJSONRequestBody defines body for AddTripMember for application/json ContentType.
type AddTripMemberJSONRequestBody = AddMemberRequest

// AddTripMessageJSONRequestBody defines body for AddTripMessage for application/json ContentType.
type AddTripMessageJSONRequestBody = MessageRequest

// UpdateTripMessageJSONRequestBody defines body for UpdateTripMessage for application/json ContentType.
type UpdateTripMessageJSONRequestBody = MessageRequest

// CreateTripPollJSONRequestBody defines body for CreateTripPoll for application/json ContentType.
type CreateTripPollJSONRequestBody = PollRequest

// AddPollOptionJSONRequestBody defines body for AddPollOption for application/json ContentType.
type AddPollOptionJSONRequestBody = PollOptionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// User Login
	// (POST /auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Get Current User Profile
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// User Registration
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// List Favorites
	// (GET /favorites)
	ListFavorites(w http.ResponseWriter, r *http.Request)
	// Add to Favorites
	// (POST /favorites)
	AddFavorite(w http.ResponseWriter, r *http.Request)
	// Remove from Favorites
	// (DELETE /favorites/{targetId})
	RemoveFavorite(w http.ResponseWriter, r *http.Request, targetId openapi_types.UUID)
	// List Gear Library Items
	// (GET /gear-library)
	ListGearLibrary(w http.ResponseWriter, r *http.Request, params ListGearLibraryParams)
	// Create Gear Library Item
	// (POST /gear-library)
	CreateGearLibraryItem(w http.ResponseWriter, r *http.Request)
	// Delete Gear Library Item
	// (DELETE /gear-library/{itemId})
	DeleteGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Get Gear Library Item
	// (GET /gear-library/{itemId})
	GetGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Update Gear Library Item
	// (PUT /gear-library/{itemId})
	UpdateGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Health Check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List Meal Library Items
	// (GET /meal-library)
	ListMealLibrary(w http.ResponseWriter, r *http.Request, params ListMealLibraryParams)
	// Create Meal Library Item
	// (POST /meal-library)
	CreateMealLibraryItem(w http.ResponseWriter, r *http.Request)
	// Delete Meal Library Item
	// (DELETE /meal-library/{itemId})
	DeleteMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Get Meal Library Item
	// (GET /meal-library/{itemId})
	GetMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Update Meal Library Item
	// (PUT /meal-library/{itemId})
	UpdateMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// List Trips
	// (GET /trips)
	ListTrips(w http.ResponseWriter, r *http.Request)
	// Create Trip
	// (POST /trips)
	CreateTrip(w http.ResponseWriter, r *http.Request)
	// Delete Trip
	// (DELETE /trips/{tripId})
	DeleteTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Get Trip
	// (GET /trips/{tripId})
	GetTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Update Trip
	// (PUT /trips/{tripId})
	UpdateTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Get Trip Gear Items
	// (GET /trips/{tripId}/gear)
	ListTripGearItems(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Add Trip Gear Item
	// (POST /trips/{tripId}/gear)
	AddTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Delete Trip Gear Item
	// (DELETE /trips/{tripId}/gear/{itemId})
	DeleteTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// Update Trip Gear Item
	// (PUT /trips/{tripId}/gear/{itemId})
	UpdateTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// List Itinerary
	// (GET /trips/{tripId}/itinerary)
	ListItinerary(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Add Itinerary Item
	// (POST /trips/{tripId}/itinerary)
	AddItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Delete Itinerary Item
	// (DELETE /trips/{tripId}/itinerary/{itemId})
	DeleteItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// Update Itinerary Item
	// (PUT /trips/{tripId}/itinerary/{itemId})
	UpdateItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// Get Trip Meal Items
	// (GET /trips/{tripId}/meals)
	ListTripMealItems(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Add Trip Meal Item
	// (POST /trips/{tripId}/meals)
	AddTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Delete Trip Meal Item
	// (DELETE /trips/{tripId}/meals/{itemId})
	DeleteTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// Update Trip Meal Item
	// (PUT /trips/{tripId}/meals/{itemId})
	UpdateTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// List Trip Members
	// (GET /trips/{tripId}/members)
	ListTripMembers(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Add Trip Member
	// (POST /trips/{tripId}/members)
	AddTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Remove Trip Member
	// (DELETE /trips/{tripId}/members/{userId})
	RemoveTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, userId openapi_types.UUID)
	// Get Trip Messages
	// (GET /trips/{tripId}/messages)
	ListTripMessages(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Add Trip Message
	// (POST /trips/{tripId}/messages)
	AddTripMessage(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Delete Trip Message
	// (DELETE /trips/{tripId}/messages/{messageId})
	DeleteTripMessage(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, messageId openapi_types.UUID)
	// Update Trip Message
	// (PUT /trips/{tripId}/messages/{messageId})
	UpdateTripMessage(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, messageId openapi_types.UUID)
	// List Trip Polls
	// (GET /trips/{tripId}/polls)
	ListTripPolls(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Create Trip Poll
	// (POST /trips/{tripId}/polls)
	CreateTripPoll(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Delete Trip Poll
	// (DELETE /trips/{tripId}/polls/{pollId})
	DeleteTripPoll(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, pollId openapi_types.UUID)
	// Get Trip Poll
	// (GET /trips/{tripId}/polls/{pollId})
	GetTripPoll(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, pollId openapi_types.UUID)
	// Add Poll Option
	// (POST /trips/{tripId}/polls/{pollId}/options)
	AddPollOption(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, pollId openapi_types.UUID)
	// Vote for Poll Option
	// (POST /trips/{tripId}/polls/{pollId}/options/{optionId}/vote)
	VotePollOption(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, pollId openapi_types.UUID, optionId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// User Login
// (POST /auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Current User Profile
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User Registration
// (POST /auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Favorites
// (GET /favorites)
func (_ Unimplemented) ListFavorites(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add to Favorites
// (POST /favorites)
func (_ Unimplemented) AddFavorite(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove from Favorites
// (DELETE /favorites/{targetId})
func (_ Unimplemented) RemoveFavorite(w http.ResponseWriter, r *http.Request, targetId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Gear Library Items
// (GET /gear-library)
func (_ Unimplemented) ListGearLibrary(w http.ResponseWriter, r *http.Request, params ListGearLibraryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Gear Library Item
// (POST /gear-library)
func (_ Unimplemented) CreateGearLibraryItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Gear Library Item
// (DELETE /gear-library/{itemId})
func (_ Unimplemented) DeleteGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Gear Library Item
// (GET /gear-library/{itemId})
func (_ Unimplemented) GetGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Gear Library Item
// (PUT /gear-library/{itemId})
func (_ Unimplemented) UpdateGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health Check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Meal Library Items
// (GET /meal-library)
func (_ Unimplemented) ListMealLibrary(w http.ResponseWriter, r *http.Request, params ListMealLibraryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Meal Library Item
// (POST /meal-library)
func (_ Unimplemented) CreateMealLibraryItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Meal Library Item
// (DELETE /meal-library/{itemId})
func (_ Unimplemented) DeleteMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Meal Library Item
// (GET /meal-library/{itemId})
func (_ Unimplemented) GetMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Meal Library Item
// (PUT /meal-library/{itemId})
func (_ Unimplemented) UpdateMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Trips
// (GET /trips)
func (_ Unimplemented) ListTrips(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Trip
// (POST /trips)
func (_ Unimplemented) CreateTrip(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Trip
// (DELETE /trips/{tripId})
func (_ Unimplemented) DeleteTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Trip
// (GET /trips/{tripId})
func (_ Unimplemented) GetTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Trip
// (PUT /trips/{tripId})
func (_ Unimplemented) UpdateTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Trip Gear Items
// (GET /trips/{tripId}/gear)
func (_ Unimplemented) ListTripGearItems(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Trip Gear Item
// (POST /trips/{tripId}/gear)
func (_ Unimplemented) AddTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Trip Gear Item
// (DELETE /trips/{tripId}/gear/{itemId})
func (_ Unimplemented) DeleteTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Trip Gear Item
// (PUT /trips/{tripId}/gear/{itemId})
func (_ Unimplemented) UpdateTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Itinerary
// (GET /trips/{tripId}/itinerary)
func (_ Unimplemented) ListItinerary(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Itinerary Item
// (POST /trips/{tripId}/itinerary)
func (_ Unimplemented) AddItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Itinerary Item
// (DELETE /trips/{tripId}/itinerary/{itemId})
func (_ Unimplemented) DeleteItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Itinerary Item
// (PUT /trips/{tripId}/itinerary/{itemId})
func (_ Unimplemented) UpdateItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Trip Meal Items
// (GET /trips/{tripId}/meals)
func (_ Unimplemented) ListTripMealItems(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Trip Meal Item
// (POST /trips/{tripId}/meals)
func (_ Unimplemented) AddTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Trip Meal Item
// (DELETE /trips/{tripId}/meals/{itemId})
func (_ Unimplemented) DeleteTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Trip Meal Item
// (PUT /trips/{tripId}/meals/{itemId})
func (_ Unimplemented) UpdateTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Trip Members
// (GET /trips/{tripId}/members)
func (_ Unimplemented) ListTripMembers(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Trip Member
// (POST /trips/{tripId}/members)
func (_ Unimplemented) AddTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove Trip Member
// (DELETE /trips/{tripId}/members/{userId})
func (_ Unimplemented) RemoveTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, userId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Trip Messages
// (GET /trips/{tripId}/messages)
func (_ Unimplemented) ListTripMessages(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Trip Message
// (POST /trips/{tripId}/messages)
func (_ Unimplemented) AddTripMessage(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Trip Message
// (DELETE /trips/{tripId}/messages/{messageId})
func (_ Unimplemented) DeleteTripMessage(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, messageId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Trip Message
// (PUT /trips/{tripId}/messages/{messageId})
func (_ Unimplemented) UpdateTripMessage(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, messageId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Trip Polls
// (GET /trips/{tripId}/polls)
func (_ Unimplemented) ListTripPolls(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Trip Poll
// (POST /trips/{tripId}/polls)
func (_ Unimplemented) CreateTripPoll(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Trip Poll
// (DELETE /trips/{tripId}/polls/{pollId})
func (_ Unimplemented) DeleteTripPoll(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, pollId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Trip Poll
// (GET /trips/{tripId}/polls/{pollId})
func (_ Unimplemented) GetTripPoll(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, pollId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Poll Option
// (POST /trips/{tripId}/polls/{pollId}/options)
func (_ Unimplemented) AddPollOption(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, pollId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Vote for Poll Option
// (POST /trips/{tripId}/polls/{pollId}/options/{optionId}/vote)
func (_ Unimplemented) VotePollOption(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, pollId openapi_types.UUID, optionId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFavorites operation middleware
func (siw *ServerInterfaceWrapper) ListFavorites(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFavorites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddFavorite operation middleware
func (siw *ServerInterfaceWrapper) AddFavorite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddFavorite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveFavorite operation middleware
func (siw *ServerInterfaceWrapper) RemoveFavorite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "targetId" -------------
	var targetId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "targetId", chi.URLParam(r, "targetId"), &targetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "targetId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveFavorite(w, r, targetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGearLibrary operation middleware
func (siw *ServerInterfaceWrapper) ListGearLibrary(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGearLibraryParams

	// ------------- Optional query parameter "include_archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_archived", r.URL.Query(), &params.IncludeArchived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_archived", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGearLibrary(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGearLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) CreateGearLibraryItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGearLibraryItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGearLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteGearLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGearLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGearLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) GetGearLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGearLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGearLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateGearLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGearLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMealLibrary operation middleware
func (siw *ServerInterfaceWrapper) ListMealLibrary(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMealLibraryParams

	// ------------- Optional query parameter "include_archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_archived", r.URL.Query(), &params.IncludeArchived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_archived", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMealLibrary(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMealLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) CreateMealLibraryItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMealLibraryItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMealLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteMealLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMealLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMealLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) GetMealLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMealLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMealLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateMealLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMealLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTrips operation middleware
func (siw *ServerInterfaceWrapper) ListTrips(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrips(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTrip operation middleware
func (siw *ServerInterfaceWrapper) CreateTrip(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrip(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrip operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrip operation middleware
func (siw *ServerInterfaceWrapper) GetTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTrip operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTripGearItems operation middleware
func (siw *ServerInterfaceWrapper) ListTripGearItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTripGearItems(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTripGearItem operation middleware
func (siw *ServerInterfaceWrapper) AddTripGearItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTripGearItem(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTripGearItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteTripGearItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTripGearItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTripGearItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateTripGearItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTripGearItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItinerary operation middleware
func (siw *ServerInterfaceWrapper) ListItinerary(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItinerary(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddItineraryItem operation middleware
func (siw *ServerInterfaceWrapper) AddItineraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddItineraryItem(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItineraryItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItineraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItineraryItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItineraryItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItineraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItineraryItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTripMealItems operation middleware
func (siw *ServerInterfaceWrapper) ListTripMealItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTripMealItems(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTripMealItem operation middleware
func (siw *ServerInterfaceWrapper) AddTripMealItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTripMealItem(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTripMealItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteTripMealItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTripMealItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTripMealItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateTripMealItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTripMealItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTripMembers operation middleware
func (siw *ServerInterfaceWrapper) ListTripMembers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTripMembers(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTripMember operation middleware
func (siw *ServerInterfaceWrapper) AddTripMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTripMember(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveTripMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveTripMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveTripMember(w, r, tripId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTripMessages operation middleware
func (siw *ServerInterfaceWrapper) ListTripMessages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTripMessages(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTripMessage operation middleware
func (siw *ServerInterfaceWrapper) AddTripMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTripMessage(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTripMessage operation middleware
func (siw *ServerInterfaceWrapper) DeleteTripMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "messageId" -------------
	var messageId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTripMessage(w, r, tripId, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTripMessage operation middleware
func (siw *ServerInterfaceWrapper) UpdateTripMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "messageId" -------------
	var messageId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "messageId", chi.URLParam(r, "messageId"), &messageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "messageId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTripMessage(w, r, tripId, messageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTripPolls operation middleware
func (siw *ServerInterfaceWrapper) ListTripPolls(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTripPolls(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTripPoll operation middleware
func (siw *ServerInterfaceWrapper) CreateTripPoll(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTripPoll(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTripPoll operation middleware
func (siw *ServerInterfaceWrapper) DeleteTripPoll(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "pollId" -------------
	var pollId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "pollId", chi.URLParam(r, "pollId"), &pollId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pollId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTripPoll(w, r, tripId, pollId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTripPoll operation middleware
func (siw *ServerInterfaceWrapper) GetTripPoll(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "pollId" -------------
	var pollId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "pollId", chi.URLParam(r, "pollId"), &pollId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pollId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTripPoll(w, r, tripId, pollId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddPollOption operation middleware
func (siw *ServerInterfaceWrapper) AddPollOption(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "pollId" -------------
	var pollId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "pollId", chi.URLParam(r, "pollId"), &pollId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pollId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddPollOption(w, r, tripId, pollId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VotePollOption operation middleware
func (siw *ServerInterfaceWrapper) VotePollOption(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "pollId" -------------
	var pollId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "pollId", chi.URLParam(r, "pollId"), &pollId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pollId", Err: err})
		return
	}

	// ------------- Path parameter "optionId" -------------
	var optionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "optionId", chi.URLParam(r, "optionId"), &optionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "optionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VotePollOption(w, r, tripId, pollId, optionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/favorites", wrapper.ListFavorites)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/favorites", wrapper.AddFavorite)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/favorites/{targetId}", wrapper.RemoveFavorite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/gear-library", wrapper.ListGearLibrary)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/gear-library", wrapper.CreateGearLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/gear-library/{itemId}", wrapper.DeleteGearLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/gear-library/{itemId}", wrapper.GetGearLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/gear-library/{itemId}", wrapper.UpdateGearLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/meal-library", wrapper.ListMealLibrary)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/meal-library", wrapper.CreateMealLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/meal-library/{itemId}", wrapper.DeleteMealLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/meal-library/{itemId}", wrapper.GetMealLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/meal-library/{itemId}", wrapper.UpdateMealLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips", wrapper.ListTrips)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips", wrapper.CreateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}", wrapper.DeleteTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}", wrapper.GetTrip)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/trips/{tripId}", wrapper.UpdateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/gear", wrapper.ListTripGearItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/gear", wrapper.AddTripGearItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/gear/{itemId}", wrapper.DeleteTripGearItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/trips/{tripId}/gear/{itemId}", wrapper.UpdateTripGearItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/itinerary", wrapper.ListItinerary)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/itinerary", wrapper.AddItineraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/itinerary/{itemId}", wrapper.DeleteItineraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/trips/{tripId}/itinerary/{itemId}", wrapper.UpdateItineraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/meals", wrapper.ListTripMealItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/meals", wrapper.AddTripMealItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/meals/{itemId}", wrapper.DeleteTripMealItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/trips/{tripId}/meals/{itemId}", wrapper.UpdateTripMealItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/members", wrapper.ListTripMembers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/members", wrapper.AddTripMember)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/members/{userId}", wrapper.RemoveTripMember)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/messages", wrapper.ListTripMessages)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/messages", wrapper.AddTripMessage)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/messages/{messageId}", wrapper.DeleteTripMessage)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/trips/{tripId}/messages/{messageId}", wrapper.UpdateTripMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/polls", wrapper.ListTripPolls)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/polls", wrapper.CreateTripPoll)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/polls/{pollId}", wrapper.DeleteTripPoll)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/polls/{pollId}", wrapper.GetTripPoll)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/polls/{pollId}/options", wrapper.AddPollOption)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/polls/{pollId}/options/{optionId}/vote", wrapper.VotePollOption)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xda3PUxpr+Kyrt+WCqBmYM52zl+MuWT0ISp/AeipDNB9brEqO2rUSXidTj4PW6yhB8",
	"GGMSswtMMHG4BYiBNeaSBGMT58espZn5dP7CVl+kkTTdusxFY/vkk8czUqv7fZ/36affvmhWLBpaydCB",
	"Di1xaFa0ilNAk/DHYVkeBdpZYJ4CX5SBBdF3JdMoARMqAF8BNElR0YcJw9QkKA7Rb3IinCkBcUi0oKno",
	"k+LcXE40wRdlxQSyOHSGXjXmXWac/QwUoTiXE4fLcOoUsEqGboHW50Hjc6CjDzKwiqZSgoqhi0PiR5+e",
	"FoaLRWBZwml8Rcvzc2LZAia68w8mmBCHxH/KN5udp23Of4KuCdcV0hJxAawqHzdNw+TXWQOWJU3iH8A5",
	"SSup6G5n/YFwHBlBsF+/rP1yrX7/aX1t2/7b5VjTucWxavK+NG2YCmRUomgCCQJ5XIIBb8kSBIehogGW",
	"xdx7zs4E7imXFZl1uSInugxK5iSA40mvxl/MMtxZklM3yL0nUYNCZieXeHWnl+f8hg1YLFDDwKOjHMcN",
	"tPaspknnTgB9Ek6JQ8cKcS1saRyroh8AyTyhnDUlc2YEAo0BNAmCScOcYTqtHRQmbLJijUtmcUqZBrLv",
	"0WcNQwWSji7QJY2NJN2ApOp6WVWlsyg8oVkGuS5hzgJmUrd9CZTJqVDZRhnVyLtYLyM+ZqPTfRRtq1de",
	"rumUoJ1C6PU1L4HruVD1I8AHwD8V4r0mgwmprEJxaEJSraYHGF70FXy0UMiJmqK7/w/mOvFxlA80RVe0",
	"siYOFeL8wXUAy7AfAkmN6vQsKMGyFew/jM9ZAJoGpoV7RP+lhSODRwqx/EYf0iyDVdMRqOiAH/tSEZYl",
	"dRyHAi9AYh0gqVCBZdkfq4oOwSSyck4sToHi50AeV/SoKIx9SDtEJEtsUpMVC0p6ESSK25wILOhZKKhi",
	"Gnev1tcqzsqFRvWa8OGHQ6OjYk4sSRACE/38HwNnCocHx/7lTOHwn8f+6+iZwuFjY4eGzhQO/2kMf/WH",
	"TthTkybBuGRZACaKEsUab3qiDb5l/gBNpZSUKtNTMbM/p08kzvV403ORD40+P9MmhK2Qjk0DocTl0uhg",
	"6AEiO4VbEEetvk8JipDT2F5imfeEManonQ9bUPxZ1peGGUSl92WycY6vFFZdR4Gkxmgq1TDp5wT+/F1l",
	"9UtlUTd1orJCYIhQWVGYiFAq/0iii5qIbWdvVB6i3GkJSiZ7+BI5tjF0CHTYtXGPrFglVZoZ50ZUQriX",
	"JBPovJFjrGdMUFKpYRQINCsug+Ka1RuEipJpSjP4f0UDFpS0UnIb9FYRpKGNaPXQ5ISA1wIDLxcffkME",
	"kBGB0q6MtXwAjQncTiATMpT7UFbjThqqypI8qvHluFZWoVJSwfi0SyKttJRBTksGkqwqegfDmYDEn+2o",
	"48WGkWR53AgX5zOKJp2jv4+riqZAtnIkVyQPa+Sqv5KnMiLbBFZZheMu9rk5u+ZAtjXSFaj2Y1TQjaSg",
	"RwOkEWxnMTyTY2Odbc9cc4SePuUYhGHT/byo/KsHsL2aRS4Zqpo4GwrOwf7kkHMicul40SjrnEBEv5vB",
	"OEyY3XXDjwVJ1zq07YFqdCtl3cQJP2lNDR/omeJ0YzgrjcrgPT9i3MzuROK1bgaMz6by+KqxqN2762iz",
	"y/fBi8PM3l2iCSSVq75cTk6l+8P+o5zotwrLnafApGLBiKnGsB72VeIoo/JdHOL7nvRO6gF/SBKymn7a",
	"VEoMrjWmkajU6CClVylNXK0gAcUQTgvCY6sGdHkc1aOlYknCKYVAKkJlGqTMS1hQMiG3dt0eZQQTvvb2",
	"Vu3pkrP+oH7vSm1tqXbr4u6vv9Wur9XnF4SR98RcO2qkJT3ha6DfSn7np8tQILi+i6/nD0uC2O0R7lLh",
	"jJuKTJnUSIUXdoLCVwTPvh8Aydxz86s0180OMJXkrMaRN9tNNnCD1DBlhCddBuciCMfX731RlnSowBm2",
	"6Or1kKLDDGNzQBExj+u1MOCa9JHsIq1b07k+kMQrmm6CJmUcdwQpr2WDvvzkIOuuPkwnI6+OAknt21wC",
	"b1oqYcR1AxQakFR+HiJ2Fiq2/APCL2Q+rWmsyDkNH+OkJRkXjr2YzaBo84X/YCELVAX4pnu81BYEs+aj",
	"FLjhQwKX3IKEzwxFTxkOqcItxUQhvlYDUJIlKLW3dJQxQ9BsYPgJPFN9ggNsX4vthKOzHmvxFut+YrEg",
	"GDUD2PUEaHw6KW4eMEWmoztjacUanwamMqHwxgKmoTKWN3lj2/qP/1NffLm7/UPt/lthAByZPCIMvzc6",
	"8q854cTx4feOn8oJo8dH/3L81KFsUvzpJrTwLa6BQ7N9FDjBYbbfWtQ03UnBogAAxbKpwJmPEQkR8J4F",
	"kgnM4TKKGfe/990Wf/TpaTT+xFcjl+FfmxabgrAkzqGCFX3CINyiQ6lI1oRh/IkflzVNgaMoxMIkIdo3",
	"F52b3zhvqrWVbfvFC5LVsC8/dhaXhMOCvXOl9nRDGD454k2V+IujP3hLGOm6RTxZBXSppIhD4rEjhSPH",
	"yKK4KdzavFSGU3nVmCSr0EqGBVuBh2qz8HB385G9XLV3vhU++vS0t00Axb2ErhuRxSGyagiTAnE6sOBf",
	"DHnGtQSdPZVKJVUp4rvyn1mEHkk3ENdJBFYlzQWhhcBHMrZ4GShu3tFCoWvPDmyswM9mWcmpXLUv30FW",
	"/2NhsGvPDu6QYDzc3nxVX7njVKr2xt9q9982rmzUnzwgEC9rmoRGn5isBWxBvBJ/0kLhiPwvjqELCRQI",
	"R04CBgyI92s3frEXv6aQcBmpduti/dUlp7rSgogPAHy3bJpAhx4seuQfKiBaTEM8QipPK5m1d5zVJy46",
	"qiRyhNrFe86NSoCExKEzQfo5MzY35nfgBwAK1JgCduZJ05hQyKiF406Tzgrwg5vsmnGqzz1nEiy1eNKd",
	"YOhheIfnMBJF+GBmEU5N5YvwQnYYIoBBgfZ0yXlxQRjY3VmyH12gm6Ccu2/tt8sk7BELvH5pr9+0V9cO",
	"sTiAmJm4lo2dCbqdxoohAz8BOIvzzuqic/2X+rfLzuaCXX3W2j0oFnzfK7pDLki07sLb0NU67RtJFIFm",
	"NOmCE9bpwhhZQfCbwXVA0+pjeIaeFa7280uNuwu1757Zl+8iQsH1bDH0sCx7Le9NqIY3XGUcqk2/cv3o",
	"t08zWMMo/sq5sen2lvFuRlf8mXHF+gPqFLwX0V5dI8/d3VxPB41hWRagEQuOQIjmZ8nGsxF5jtRMBRBE",
	"AWfntle72o/bjZUHDKrXjGngQ1BJMiUNkJUWZ2ZFJBaxhnQTF0OiWwcxjIKcz6Nx03FjLYj5I8PY2L20",
	"5gl9xipmcWd382u78rz++CWxR+2n+caVi+kcRiwlTJiGlshrk0AyD9NUWgputeeXdre26j98b19Ysbee",
	"2pVv6/fWhAFE88/P2+s30SXLG4355cb5byimz3/j/LZziEnBvo1oHN9+UQbmTNO5il5UyzLwL8luOjVu",
	"loLh1R4QfXhfZXK+/+62feEVsWhPmB7VTKBVE0ZwW5r4COCBz/pO9bl9/7YfBfVLr+ytp4hgwh4mU8th",
	"e/SmF+Bsacy4M2jxPdfXeL0AMWDX+oQ0gCC+aYUEHxFh0sjPonCI4/rKk8bKAz9chAHn+oaz/JO98ajx",
	"9Dr5vZUc3sPltUInnv5JpbIif1L/pOR/jJHRuHjP+d/LjZWrtddr9bcbiToJFzZp/E0Mmsbfuaguwa4+",
	"292cpwTw+JXz1QJrvL1n/FfoQ4STYb4vwjvDBxpFLVd7hg80ok8FjlKZ1Tt89xPqIPy9AzsZQyZC+omP",
	"vdUFZQtQ7KWW/OBepS6ClbRd1RTeis9Vts6T+86dh8LwyRHBWf3aXlpxbm7YVx856z/Ym5uN80u7v66y",
	"GI1s8O9l8jB0hAAzh4fri2saSqqQm4V3p0Dxc595rBkL2YsYRgOS2rbwb/xwp7b42BP+TFHv2/d4YER9",
	"eGNvSlFPzdY7aY/qx5X2AY8nk/akwnHSPmyV3vAqZx9txtK+BQHR0p4YsJ/SvgUSfESEaSG1tKetZav4",
	"VpT8ruLrj1+6CGlDxadwbQIVT2Odq+L3jP8KfQhmbCd/MGem4tvBB1LxqcARq+IpOKJUfD/xsbd6m2wB",
	"2j8V3w40qYpP2StBUynFTf05lf+m228qVTLXUrt1ka5Y4avU07jkLLQj3hSWQDASqRioeN+WB7QhQV2D",
	"ut4krouYPyQ+qz4nLeZITGy83kR66+6njCUlAUZMipgYJ+s5/gz0KfVsGC5e1Odn0Z9EIpSDIKKW6HMS",
	"TBzix+0/zUlKEgbs5SfO6qK9+LO9vVWfX7CXN9zsOo/Tid0QreMlGm1pUY4bI3VnbfGN/ewWeXr98ava",
	"T8/5a7b6675CRsGegbbsyNlIWHI9HSEiqY+j5GPmDu5NTxJc2p+xXOSCq8sakZTXG4hRgZi4W8CTkTHS",
	"0NuNTZaEkexzxJIw/zZKa7+wTmIR6m1FTrkELWC2jKeyqPxph6vIjEE4GYocdhhDJy4TShe5VHgCdViW",
	"A1bd/xwW3kHcBz3cxCgPk37ndHU5XbemuNqA7LAshyDLQSyHBpMlbHduuwRNl9tRI/J1c9bYzu2BZHDA",
	"NP2AjlOpdrDCIxGMEmg2BJJbFzkIaSq3g4WQPUSrhexotUUk7kVCbTMqfKqyHXJV3LO9EwlNXq7ROyH8",
	"QEnK4CsEUiY46/fWahvzje3b/kxnEtGYOi/pN37S3CTVGMGasgRg0Ab7WwEyz7HPWAKGMBWtAVOQVRIq",
	"SivYvLqyOMWK4ZMUU+xxMCQdf1+QmNtjk/dd6nGooduRX7GgSJIu47qa9GYH0NV7ic0KGbJZi/TqI4Kp",
	"VGqH1jQgqVa6XByZQ47JxbmnDR28XJx3rFfKXFzAbPsoF4fn/Zm5OIKdOC3mrqCMScZ5Zt3/ybjwSVt9",
	"SMY1QRotxLq82HGvJOM8zPIgy2PCNtNxkaso+4HuvZOO694KvHYSDx0s1UwGpMT5OA5Emvm4gwWRPcSs",
	"heyYdb/k4zpYBtgBv2pn6WsWYrUmMuG1ezFrAEdpgQdPYLrHaiZLywWM1btsHHW8a/N0CTm3jpQShYHd",
	"7YcCPsFN2P11tXZhq3Fhvv50aXfne+farUN8jYgts78VYssL3fsiD+mRotEHn2CncYmsucfs4j3n1Q1y",
	"j3umEDnFxLm5QQr5+9srTqXqetxdZnIowboVH3zaFoMUNYmGwxjf+dmyBcz401BIvWo/btuXtjjDG3K6",
	"R/boZXfvpFn9OGAlsgvD1/nhFnfYCr7UqVTbGSXQ81bawAZ+D1zCbMmNlfravPP9b/bCj/azNxGdGC30",
	"IPVi3BcQRmdIiM32V27E815IBtHvk01U0YZzez1izf3d7YXeopj5HlCKyOh0iB+BGUj3HsPU1wO6COKh",
	"NILu8rP0U4opLw6g/fmQTDHN7gy9dvW+PyTG6eKKcVLe+gMXse0nOOKgkSDDwXG3P7dxsNy9N+ixkAk9",
	"9i+n0Sa8g4mKNpivZKhp58ScyzdqD/mpipO4xIMk8fB7g9MeiIqNtG9mwJpZD9d9AQwRlMTtkqT5rOpz",
	"DkKaeyWxRfe3xvO/DjRjgUfwGL0jk7oga3XX5g5LgQKCCToea+Vn0Z9ESo0DyKZGyxKQ7B6btGW/qrP2",
	"RVmU5xMcC0I8S44FqVcuNc5vNu4u8HZoHlAvF7JiFl/PRg9iybZnc0mtrfxFRxST973APjL3j2vIQeGw",
	"LPtedn4gcNibfjX4mu8+9K7URXELSoibo/vYPEE56WrdGQOE6IXz9bUX/oIOdet07jaiZFiWcYAIHjg7",
	"i5P8LPmAvpqmb5jjxM3lG7WfH5G99sQOwkB96aH9mrbDXt6of/Wrs/qVvVx1fqk4lerub8+c62/+/vaK",
	"c/eNc+2W83DdXlppXFhGo6gXW/YzxpzavxkQHKDQYxfsWnz/9S5krIQjSxigE73kdKedK2jYiX+vLc07",
	"C0uHuOFGfnfjzH79svbzVef7O+Tm/5s/78Wc/QABrba+2N2AcypVlxDSRB6CpjBhmInCDxdsTruwDVbp",
	"hFGUVEEG00A1ShryVk4smyp9z9ZQPq+iC6YMCw69U3inkJdKSn56UETVoU8Ll/gxPpFT8GLJaoKNHtaJ",
	"oBi8B7US6JAiRPj3cqFw9J8F9K1hKv/pvkOFloJfodJaBklnSLo0CWg7fEFpMW44CUzL0CU1cPxq87bA",
	"wasRd/uPffLn0nwHPs2Nzf1/AAAA//8E1zaVwZwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
