// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AddMemberRequest defines model for AddMemberRequest.
type AddMemberRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// Token JWT Access Token
	Token string `json:"token"`
	User  User   `json:"user"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// GearLibraryItem defines model for GearLibraryItem.
type GearLibraryItem struct {
	Category   string             `json:"category"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	IsArchived bool               `json:"is_archived"`
	Name       string             `json:"name"`
	Notes      *string            `json:"notes,omitempty"`
	UpdatedAt  time.Time          `json:"updated_at"`
	UserId     openapi_types.UUID `json:"user_id"`
	Weight     float64            `json:"weight"`
}

// GearLibraryItemRequest defines model for GearLibraryItemRequest.
type GearLibraryItemRequest struct {
	Category   string  `json:"category"`
	IsArchived *bool   `json:"is_archived,omitempty"`
	Name       string  `json:"name"`
	Notes      *string `json:"notes,omitempty"`
	Weight     float64 `json:"weight"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

// ItineraryItem defines model for ItineraryItem.
type ItineraryItem struct {
	ActualTime  *time.Time `json:"actual_time,omitempty"`
	Altitude    int        `json:"altitude"`
	CheckedInAt *time.Time `json:"checked_in_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	Day         string     `json:"day"`
	Distance    float64    `json:"distance"`

	// EstTime 預計時間 HH:MM
	EstTime     string             `json:"est_time"`
	Id          openapi_types.UUID `json:"id"`
	ImageAsset  *string            `json:"image_asset,omitempty"`
	IsCheckedIn bool               `json:"is_checked_in"`
	Name        string             `json:"name"`
	Note        string             `json:"note"`
	TripId      openapi_types.UUID `json:"trip_id"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// ItineraryItemRequest defines model for ItineraryItemRequest.
type ItineraryItemRequest struct {
	Altitude   *int     `json:"altitude,omitempty"`
	Day        string   `json:"day"`
	Distance   *float64 `json:"distance,omitempty"`
	EstTime    string   `json:"est_time"`
	ImageAsset *string  `json:"image_asset,omitempty"`
	Name       string   `json:"name"`
	Note       *string  `json:"note,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MealLibraryItem defines model for MealLibraryItem.
type MealLibraryItem struct {
	Calories   float64            `json:"calories"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	IsArchived bool               `json:"is_archived"`
	Name       string             `json:"name"`
	Notes      *string            `json:"notes,omitempty"`
	UpdatedAt  time.Time          `json:"updated_at"`
	UserId     openapi_types.UUID `json:"user_id"`
	Weight     float64            `json:"weight"`
}

// MealLibraryItemRequest defines model for MealLibraryItemRequest.
type MealLibraryItemRequest struct {
	Calories   float64 `json:"calories"`
	IsArchived *bool   `json:"is_archived,omitempty"`
	Name       string  `json:"name"`
	Notes      *string `json:"notes,omitempty"`
	Weight     float64 `json:"weight"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// Trip defines model for Trip.
type Trip struct {
	CoverImage  *string             `json:"cover_image,omitempty"`
	CreatedAt   time.Time           `json:"created_at"`
	DayNames    []string            `json:"day_names"`
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	Id          openapi_types.UUID  `json:"id"`
	IsActive    bool                `json:"is_active"`
	Name        string              `json:"name"`
	StartDate   openapi_types.Date  `json:"start_date"`
	UpdatedAt   time.Time           `json:"updated_at"`

	// UserId 建立此行程的使用者 ID
	UserId openapi_types.UUID `json:"user_id"`
}

// TripCreateRequest defines model for TripCreateRequest.
type TripCreateRequest struct {
	CoverImage  *string             `json:"cover_image,omitempty"`
	DayNames    *[]string           `json:"day_names,omitempty"`
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	Name        string              `json:"name"`
	StartDate   openapi_types.Date  `json:"start_date"`
}

// TripGearItem defines model for TripGearItem.
type TripGearItem struct {
	Category      string              `json:"category"`
	CreatedAt     time.Time           `json:"created_at"`
	Id            openapi_types.UUID  `json:"id"`
	IsChecked     bool                `json:"is_checked"`
	LibraryItemId *openapi_types.UUID `json:"library_item_id,omitempty"`
	Name          string              `json:"name"`
	OrderIndex    *int                `json:"order_index,omitempty"`
	Quantity      int                 `json:"quantity"`
	TripId        openapi_types.UUID  `json:"trip_id"`
	UpdatedAt     time.Time           `json:"updated_at"`
	Weight        float64             `json:"weight"`
}

// TripGearItemRequest defines model for TripGearItemRequest.
type TripGearItemRequest struct {
	Category      string              `json:"category"`
	IsChecked     *bool               `json:"is_checked,omitempty"`
	LibraryItemId *openapi_types.UUID `json:"library_item_id,omitempty"`
	Name          string              `json:"name"`
	OrderIndex    *int                `json:"order_index,omitempty"`
	Quantity      *int                `json:"quantity,omitempty"`
	Weight        float64             `json:"weight"`
}

// TripMealItem defines model for TripMealItem.
type TripMealItem struct {
	Calories      float64             `json:"calories"`
	CreatedAt     time.Time           `json:"created_at"`
	Day           string              `json:"day"`
	Id            openapi_types.UUID  `json:"id"`
	LibraryItemId *openapi_types.UUID `json:"library_item_id,omitempty"`
	MealType      string              `json:"meal_type"`
	Name          string              `json:"name"`
	Note          *string             `json:"note,omitempty"`
	Quantity      int                 `json:"quantity"`
	TripId        openapi_types.UUID  `json:"trip_id"`
	UpdatedAt     time.Time           `json:"updated_at"`
	Weight        float64             `json:"weight"`
}

// TripMealItemRequest defines model for TripMealItemRequest.
type TripMealItemRequest struct {
	Calories      float64             `json:"calories"`
	Day           string              `json:"day"`
	LibraryItemId *openapi_types.UUID `json:"library_item_id,omitempty"`
	MealType      string              `json:"meal_type"`
	Name          string              `json:"name"`
	Note          *string             `json:"note,omitempty"`
	Quantity      *int                `json:"quantity,omitempty"`
	Weight        float64             `json:"weight"`
}

// TripMember defines model for TripMember.
type TripMember struct {
	JoinedAt     time.Time          `json:"joined_at"`
	TripId       openapi_types.UUID `json:"trip_id"`
	UserId       openapi_types.UUID `json:"user_id"`
	UserMetadata User               `json:"user_metadata"`
}

// TripUpdateRequest defines model for TripUpdateRequest.
type TripUpdateRequest struct {
	CoverImage  *string             `json:"cover_image,omitempty"`
	DayNames    *[]string           `json:"day_names,omitempty"`
	Description *string             `json:"description,omitempty"`
	EndDate     *openapi_types.Date `json:"end_date,omitempty"`
	IsActive    *bool               `json:"is_active,omitempty"`
	Name        *string             `json:"name,omitempty"`
	StartDate   *openapi_types.Date `json:"start_date,omitempty"`
}

// User defines model for User.
type User struct {
	Avatar      string              `json:"avatar"`
	CreatedAt   time.Time           `json:"created_at"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	IsActive    bool                `json:"is_active"`
	IsVerified  bool                `json:"is_verified"`

	// Role 使用者角色代碼 (e.g. ADMIN, LEADER, MEMBER)
	Role string `json:"role"`
}

// ListGearLibraryParams defines parameters for ListGearLibrary.
type ListGearLibraryParams struct {
	IncludeArchived *bool `form:"include_archived,omitempty" json:"include_archived,omitempty"`
}

// ListMealLibraryParams defines parameters for ListMealLibrary.
type ListMealLibraryParams struct {
	IncludeArchived *bool `form:"include_archived,omitempty" json:"include_archived,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateGearLibraryItemJSONRequestBody defines body for CreateGearLibraryItem for application/json ContentType.
type CreateGearLibraryItemJSONRequestBody = GearLibraryItemRequest

// UpdateGearLibraryItemJSONRequestBody defines body for UpdateGearLibraryItem for application/json ContentType.
type UpdateGearLibraryItemJSONRequestBody = GearLibraryItemRequest

// CreateMealLibraryItemJSONRequestBody defines body for CreateMealLibraryItem for application/json ContentType.
type CreateMealLibraryItemJSONRequestBody = MealLibraryItemRequest

// UpdateMealLibraryItemJSONRequestBody defines body for UpdateMealLibraryItem for application/json ContentType.
type UpdateMealLibraryItemJSONRequestBody = MealLibraryItemRequest

// CreateTripJSONRequestBody defines body for CreateTrip for application/json ContentType.
type CreateTripJSONRequestBody = TripCreateRequest

// UpdateTripJSONRequestBody defines body for UpdateTrip for application/json ContentType.
type UpdateTripJSONRequestBody = TripUpdateRequest

// AddTripGearItemJSONRequestBody defines body for AddTripGearItem for application/json ContentType.
type AddTripGearItemJSONRequestBody = TripGearItemRequest

// UpdateTripGearItemJSONRequestBody defines body for UpdateTripGearItem for application/json ContentType.
type UpdateTripGearItemJSONRequestBody = TripGearItemRequest

// AddItineraryItemJSONRequestBody defines body for AddItineraryItem for application/json ContentType.
type AddItineraryItemJSONRequestBody = ItineraryItemRequest

// UpdateItineraryItemJSONRequestBody defines body for UpdateItineraryItem for application/json ContentType.
type UpdateItineraryItemJSONRequestBody = ItineraryItemRequest

// AddTripMealItemJSONRequestBody defines body for AddTripMealItem for application/json ContentType.
type AddTripMealItemJSONRequestBody = TripMealItemRequest

// UpdateTripMealItemJSONRequestBody defines body for UpdateTripMealItem for application/json ContentType.
type UpdateTripMealItemJSONRequestBody = TripMealItemRequest

// AddTripMemberJSONRequestBody defines body for AddTripMember for application/json ContentType.
type AddTripMemberJSONRequestBody = AddMemberRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// User Login
	// (POST /auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Get Current User Profile
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// User Registration
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// List Gear Library Items
	// (GET /gear-library)
	ListGearLibrary(w http.ResponseWriter, r *http.Request, params ListGearLibraryParams)
	// Create Gear Library Item
	// (POST /gear-library)
	CreateGearLibraryItem(w http.ResponseWriter, r *http.Request)
	// Delete Gear Library Item
	// (DELETE /gear-library/{itemId})
	DeleteGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Get Gear Library Item
	// (GET /gear-library/{itemId})
	GetGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Update Gear Library Item
	// (PUT /gear-library/{itemId})
	UpdateGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Health Check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List Meal Library Items
	// (GET /meal-library)
	ListMealLibrary(w http.ResponseWriter, r *http.Request, params ListMealLibraryParams)
	// Create Meal Library Item
	// (POST /meal-library)
	CreateMealLibraryItem(w http.ResponseWriter, r *http.Request)
	// Delete Meal Library Item
	// (DELETE /meal-library/{itemId})
	DeleteMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Get Meal Library Item
	// (GET /meal-library/{itemId})
	GetMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// Update Meal Library Item
	// (PUT /meal-library/{itemId})
	UpdateMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID)
	// List Trips
	// (GET /trips)
	ListTrips(w http.ResponseWriter, r *http.Request)
	// Create Trip
	// (POST /trips)
	CreateTrip(w http.ResponseWriter, r *http.Request)
	// Delete Trip
	// (DELETE /trips/{tripId})
	DeleteTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Get Trip
	// (GET /trips/{tripId})
	GetTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Update Trip
	// (PUT /trips/{tripId})
	UpdateTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Get Trip Gear Items
	// (GET /trips/{tripId}/gear)
	ListTripGearItems(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Add Trip Gear Item
	// (POST /trips/{tripId}/gear)
	AddTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Delete Trip Gear Item
	// (DELETE /trips/{tripId}/gear/{itemId})
	DeleteTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// Update Trip Gear Item
	// (PUT /trips/{tripId}/gear/{itemId})
	UpdateTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// List Itinerary
	// (GET /trips/{tripId}/itinerary)
	ListItinerary(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Add Itinerary Item
	// (POST /trips/{tripId}/itinerary)
	AddItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Delete Itinerary Item
	// (DELETE /trips/{tripId}/itinerary/{itemId})
	DeleteItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// Update Itinerary Item
	// (PUT /trips/{tripId}/itinerary/{itemId})
	UpdateItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// Get Trip Meal Items
	// (GET /trips/{tripId}/meals)
	ListTripMealItems(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Add Trip Meal Item
	// (POST /trips/{tripId}/meals)
	AddTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Delete Trip Meal Item
	// (DELETE /trips/{tripId}/meals/{itemId})
	DeleteTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// Update Trip Meal Item
	// (PUT /trips/{tripId}/meals/{itemId})
	UpdateTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID)
	// List Trip Members
	// (GET /trips/{tripId}/members)
	ListTripMembers(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Add Trip Member
	// (POST /trips/{tripId}/members)
	AddTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID)
	// Remove Trip Member
	// (DELETE /trips/{tripId}/members/{userId})
	RemoveTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, userId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// User Login
// (POST /auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Current User Profile
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// User Registration
// (POST /auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Gear Library Items
// (GET /gear-library)
func (_ Unimplemented) ListGearLibrary(w http.ResponseWriter, r *http.Request, params ListGearLibraryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Gear Library Item
// (POST /gear-library)
func (_ Unimplemented) CreateGearLibraryItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Gear Library Item
// (DELETE /gear-library/{itemId})
func (_ Unimplemented) DeleteGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Gear Library Item
// (GET /gear-library/{itemId})
func (_ Unimplemented) GetGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Gear Library Item
// (PUT /gear-library/{itemId})
func (_ Unimplemented) UpdateGearLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health Check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Meal Library Items
// (GET /meal-library)
func (_ Unimplemented) ListMealLibrary(w http.ResponseWriter, r *http.Request, params ListMealLibraryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Meal Library Item
// (POST /meal-library)
func (_ Unimplemented) CreateMealLibraryItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Meal Library Item
// (DELETE /meal-library/{itemId})
func (_ Unimplemented) DeleteMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Meal Library Item
// (GET /meal-library/{itemId})
func (_ Unimplemented) GetMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Meal Library Item
// (PUT /meal-library/{itemId})
func (_ Unimplemented) UpdateMealLibraryItem(w http.ResponseWriter, r *http.Request, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Trips
// (GET /trips)
func (_ Unimplemented) ListTrips(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Trip
// (POST /trips)
func (_ Unimplemented) CreateTrip(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Trip
// (DELETE /trips/{tripId})
func (_ Unimplemented) DeleteTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Trip
// (GET /trips/{tripId})
func (_ Unimplemented) GetTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Trip
// (PUT /trips/{tripId})
func (_ Unimplemented) UpdateTrip(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Trip Gear Items
// (GET /trips/{tripId}/gear)
func (_ Unimplemented) ListTripGearItems(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Trip Gear Item
// (POST /trips/{tripId}/gear)
func (_ Unimplemented) AddTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Trip Gear Item
// (DELETE /trips/{tripId}/gear/{itemId})
func (_ Unimplemented) DeleteTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Trip Gear Item
// (PUT /trips/{tripId}/gear/{itemId})
func (_ Unimplemented) UpdateTripGearItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Itinerary
// (GET /trips/{tripId}/itinerary)
func (_ Unimplemented) ListItinerary(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Itinerary Item
// (POST /trips/{tripId}/itinerary)
func (_ Unimplemented) AddItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Itinerary Item
// (DELETE /trips/{tripId}/itinerary/{itemId})
func (_ Unimplemented) DeleteItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Itinerary Item
// (PUT /trips/{tripId}/itinerary/{itemId})
func (_ Unimplemented) UpdateItineraryItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get Trip Meal Items
// (GET /trips/{tripId}/meals)
func (_ Unimplemented) ListTripMealItems(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Trip Meal Item
// (POST /trips/{tripId}/meals)
func (_ Unimplemented) AddTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete Trip Meal Item
// (DELETE /trips/{tripId}/meals/{itemId})
func (_ Unimplemented) DeleteTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update Trip Meal Item
// (PUT /trips/{tripId}/meals/{itemId})
func (_ Unimplemented) UpdateTripMealItem(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List Trip Members
// (GET /trips/{tripId}/members)
func (_ Unimplemented) ListTripMembers(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add Trip Member
// (POST /trips/{tripId}/members)
func (_ Unimplemented) AddTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove Trip Member
// (DELETE /trips/{tripId}/members/{userId})
func (_ Unimplemented) RemoveTripMember(w http.ResponseWriter, r *http.Request, tripId openapi_types.UUID, userId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGearLibrary operation middleware
func (siw *ServerInterfaceWrapper) ListGearLibrary(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGearLibraryParams

	// ------------- Optional query parameter "include_archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_archived", r.URL.Query(), &params.IncludeArchived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_archived", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGearLibrary(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGearLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) CreateGearLibraryItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGearLibraryItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGearLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteGearLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGearLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGearLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) GetGearLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGearLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGearLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateGearLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGearLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMealLibrary operation middleware
func (siw *ServerInterfaceWrapper) ListMealLibrary(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMealLibraryParams

	// ------------- Optional query parameter "include_archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_archived", r.URL.Query(), &params.IncludeArchived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_archived", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMealLibrary(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMealLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) CreateMealLibraryItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMealLibraryItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMealLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteMealLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMealLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMealLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) GetMealLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMealLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMealLibraryItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateMealLibraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMealLibraryItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTrips operation middleware
func (siw *ServerInterfaceWrapper) ListTrips(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrips(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTrip operation middleware
func (siw *ServerInterfaceWrapper) CreateTrip(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrip(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrip operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrip operation middleware
func (siw *ServerInterfaceWrapper) GetTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTrip operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTripGearItems operation middleware
func (siw *ServerInterfaceWrapper) ListTripGearItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTripGearItems(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTripGearItem operation middleware
func (siw *ServerInterfaceWrapper) AddTripGearItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTripGearItem(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTripGearItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteTripGearItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTripGearItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTripGearItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateTripGearItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTripGearItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItinerary operation middleware
func (siw *ServerInterfaceWrapper) ListItinerary(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItinerary(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddItineraryItem operation middleware
func (siw *ServerInterfaceWrapper) AddItineraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddItineraryItem(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItineraryItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItineraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItineraryItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItineraryItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItineraryItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItineraryItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTripMealItems operation middleware
func (siw *ServerInterfaceWrapper) ListTripMealItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTripMealItems(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTripMealItem operation middleware
func (siw *ServerInterfaceWrapper) AddTripMealItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTripMealItem(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTripMealItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteTripMealItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTripMealItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTripMealItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateTripMealItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTripMealItem(w, r, tripId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTripMembers operation middleware
func (siw *ServerInterfaceWrapper) ListTripMembers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTripMembers(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTripMember operation middleware
func (siw *ServerInterfaceWrapper) AddTripMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTripMember(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveTripMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveTripMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveTripMember(w, r, tripId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/gear-library", wrapper.ListGearLibrary)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/gear-library", wrapper.CreateGearLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/gear-library/{itemId}", wrapper.DeleteGearLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/gear-library/{itemId}", wrapper.GetGearLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/gear-library/{itemId}", wrapper.UpdateGearLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/meal-library", wrapper.ListMealLibrary)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/meal-library", wrapper.CreateMealLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/meal-library/{itemId}", wrapper.DeleteMealLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/meal-library/{itemId}", wrapper.GetMealLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/meal-library/{itemId}", wrapper.UpdateMealLibraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips", wrapper.ListTrips)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips", wrapper.CreateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}", wrapper.DeleteTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}", wrapper.GetTrip)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/trips/{tripId}", wrapper.UpdateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/gear", wrapper.ListTripGearItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/gear", wrapper.AddTripGearItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/gear/{itemId}", wrapper.DeleteTripGearItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/trips/{tripId}/gear/{itemId}", wrapper.UpdateTripGearItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/itinerary", wrapper.ListItinerary)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/itinerary", wrapper.AddItineraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/itinerary/{itemId}", wrapper.DeleteItineraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/trips/{tripId}/itinerary/{itemId}", wrapper.UpdateItineraryItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/meals", wrapper.ListTripMealItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/meals", wrapper.AddTripMealItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/meals/{itemId}", wrapper.DeleteTripMealItem)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/trips/{tripId}/meals/{itemId}", wrapper.UpdateTripMealItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}/members", wrapper.ListTripMembers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips/{tripId}/members", wrapper.AddTripMember)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}/members/{userId}", wrapper.RemoveTripMember)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdXVPcRtb+Kyq9ubCrBjPYyVvZudkisTchZbZcjlO58LJUe9QMivUxllokrJcqTHAM",
	"xgnedTwxDrGDv4LNEojJJgQc8meQZrjav7DVH9JII/VImm/YXIXMtLpPn/Ocp58+3SNfFfO6WtQ1qCFT",
	"zF0Vzfw4VAH5c1CShqF6CRrn4RULmgh/VjT0IjSQDEkLqAJZwX+M6YYKkJhjn2RENFmEYk40kSFrBXFq",
	"KiMa8IolG1AScxdZqxGvmX7pI5hH4lRGHLTQ+HloFnXNhOHxkH4ZavgPCZp5Qy4iWdfEnPjehxeEwXwe",
	"mqZwgbQIjZ8RLRMa+MnXDDgm5sT/669Ou5/Nuf8D3KbWVsR6JB1EmXzGMHSDb7MKTRMUyBfwE6AWFfy0",
	"s/5EOIOdINg/vyz/dKfyaK2yumt/djPWdW53UZa8A4FxVr5kAGNyCEE1bEseIFjQjUniy1oP5Q0IEJRG",
	"AQpEVAII9iFZhVFelaVAW8uSpchm5igw8uPyBJR8Q1/SdQUCDTfQgAojjdJ0RE3XLEUBl7DzkGHBqAAX",
	"pdTm45iOJpzDx1AujNf0rVvYIq+xZuFsCYWM9OcOxebq9ZepBiXop0BAAtNLEHpuxvoRoIJPzkKtgMbF",
	"3BvZ+KhJcAxYChJzY0AxqxGIiKKv45PZbEZUZc39/4FMMzGuFwNV1mTVUsVcNi4e3ABEOfZdCJR6lGQi",
	"gCwzmN365SgATUDDJHzlb5o9MXAiG5v0bJBqH1GWDiFZg/zcB3lkAWWUpAIvQWIDABQkI0vy56qsIVjA",
	"Xs6I+XGYvwylUVmrl4WxgzRCRBKIJjVJNhHQ8jBR3mZEaCLPQ8E15uDb25XVOWdp5qB0R3j33dzwsJgR",
	"iwAhaOCv/3rsYrZvYOSPF7N9fxj5+8mL2b5TI8dzF7N9b4yQj15rhj1VUICjwDQhSpQlsjlajUQDfBv5",
	"BTLkYlKqTE/FUYzpjkiD6/GmFyIfGn1xZlOo9UI6Ng2kEpdL6ydDGxDZLNyCOArHPiUoaoIWHaUo957V",
	"C7LWvKjE+WeaH+tGEJXeh8lUqK+XKFuHIVBiNJWiG+zvBPH8XWV1S2WxMDWjsmrAUEdl1cNEHaXyvyS6",
	"mIui/HweFmQT1dl4SrJZVMDkqDf56mRPRkyhhZTiG+nN1ASTCRoeNfULhlyMAJQ+gYGtso1kuyQUMYsM",
	"KCOomtFCgH4ADANMksf8MimBaVCTRrEdIcOSSMMUTJhH8gRMyYMmAgbiWtdqMgwKTHt3p7y24Kw/qazc",
	"Kq8ulO/P7v/6W/nL1cr0dWHotJiJm3UiOvRN0O8lf/DTMSKG69ukPZ8Mg9htE+5S4YwrfVKSaCq8RBOi",
	"rwuef/HevufqOUxbRyeYQtfIURxNzsofm+rcJNUNCeNJk+AndQjHp8SvWEBDMpqM1unt3dg0rWiqu6A6",
	"dSNvhoHQpM9kF2mtKh/5QBIvZFoJmpR53BSkvJkN+PTQQNRTXShf4ahi1dq1vQtvG5ww41oBChUCZZR+",
	"2siuN7b/I8IvdP9edVbdPZSPcdKSjAvHduyeGNp86T+Q7QSqAnzTOl5qCIKd5qMUuOFDgvQcQsJHuqyl",
	"TIdU6ZaiMEHaqhABCSDQ2EGil2lVWV6dYO0IPFd9QBLsUIvthLuzNmvxkHc/MKMgCCYAAkbLBHZt4aKZ",
	"UkVrNsOyOToBDXlM5ol5Q1cizkO8zWnlu39W5l/u7z4uP3olHIMnCieEwdPDQ3/OCGfPDJ4+cz4jDJ8Z",
	"fuvM+ePJtqzubAOOyrhhCG5a/aYzOwNRCecQxgnMW4aMJt/HuUpjfAkCAxqDFoaW+39/ct363ocX8DaN",
	"tMaOId9W5zKOUFGcwh3L2phOU1BDIE+PakiUxfctVZXRMEZibS6J9r15594Xzi+l8tKu/cMPdPNv33zu",
	"zC8IfYK9d6u8tiEMnhvCI8pICXbHvvBOFtlxIla0RaiBoizmxFMnsidO0bOqcTLbfmCh8X5FL9DDoaJO",
	"eSRoFrbm+tP97Wf2Ysne+0p478ML3t0KnB4AtxuSxBwt5pPcodGEJnpLlyZdT0CN9A6KRUXOk6f6PzIp",
	"i1C2jOPSwGHBVBAzeDUkH9DTWTK9k9lsy8YO3EYhY0d5yZm7bd98iL3+enagZWMHr5VEDG5vb1WWHjpz",
	"JXvjs/KjVwe3NiovnlCIW6oK8CaNcJpAPIjxAwomzjMcf3EEN6RQoExUgBEwoNEv3/3Jnv+cQcLN+/L9",
	"2crWDae0FELEOxC9bRkG1JAHizbFh62zIdfQiFDjmZGdjo6z/MJFR4lmjlCeXXHuzgVISMxdDNLPxZGp",
	"EX8A34FIYM4USDDPGfqYTMU9J5wGK57zk5teNXJKm14wKZZCkXTr8G1M79pSf6IMH+hYhjNX+TI82zkM",
	"UcDgRFtbcH6YEY7t7y3Yz2bYzTHn21f2q0Wa9pgFfn5pr9+zl1ePR3EAdTMNbTR2ChAYfWxjFMMHfg6w",
	"pxf2d3Yqj7+xZ5bsnTV77qvKyqpwDFuzec1ev4ebLG4cTC8eXPvCXvzUubt9cO0L57e94+GFRDaR7xoT",
	"WbIMoEIEDZPkCV6vxCsWNLxzZrybySuWBP0HelXnx9WccKo1xU2egK4X5tpbeSF5zeWvrx/YM1vUoz7+",
	"4vBMOl7BzhawZQIzTRgic6lCI4CHkakMh0uc0qb96IEfBZUbW/bO2v72eijC9KCg1h/t4RXOhbgO00so",
	"9txYk9Mf6kAfz9RmH8kfttC3FhA0NmFI8BFRSxr9V3E6DElT1CYFoohtgz334mDpiR8uwjHnyw1n8Ud7",
	"49nB2pf0+zA5nCb9haETRRFY6foYghgl1kbdzxNxJ2thmng9wu80jsT+JMHBLU5FCO/ZFedfNw+Wbpd/",
	"Xq282qDtooab39vf/tye26w8f+nCJk28qUPTxDtTb0mwS9/vb08zAni+5Xx6PUoW9kz8sl3IcKpGfRne",
	"HD7wYr9Yahs+sPBMBY6iFbU6fP0jXiD8q0P0noGWtbqJj95agjoLUBKl0Da2V6mLYiXtUjVOLnJzla3z",
	"4pHz8KkweG5IcJY/txeWnHsb9u1nzvpje3v74NrC/q/LUYxGr4e3c49bcwE9cqtJ7CWW1mh/+rDw9jjM",
	"X/a5x5w0sb+oY1QIlIaF/8Hjh+X5557wjxT1vltzR0bU114LTSnqmdvaJ+2xfVxpH4h4MmlPDY6T9rVe",
	"aQ+vcm5hdljahxBQX9pTB3ZT2ocgwUdELS2klvZsttEqPoyS31V85flLFyENqPgUoU2g4lmuc1V8z8Qv",
	"24VkJn7yJ3PHVHwj+MAqPhU4YlU8A0c9Fd9NfPTWatNZgHZPxTcCTabiU65KyJCLZoxKdeb+wS5Tz5Xs",
	"m9/a15+W78+yg1W+Sr1Aeu6EdiRX/BMIRioVA4Z37RSrAQnqOtSNJg0dX26ymJU26Yw5EpM4rz2ZHr7L",
	"3mFJSYERUyKmzun0UVQH9CmLbC1cvKzvv4r/k0iEchBE1RIbJ35NosMdPs1JexKO2YsvnOV5e/7f9u5O",
	"Zfq6vbjhVtd5nE79hmmdnCQ2pEU5YayrO8vzv9jf36ejV55vlX/c5F8t6G74sh1K9g5oy6aCjYUlN9J1",
	"RCSLcT352PEAt2clCV7U7LBc5IKrxRqR9tceiDGBmHhZIIeRMdLQ+22dMz/tLM/T6rOzfd0ufc8Vhe6P",
	"YszDwjqJRaj3w7Lk1UvfIRZzW4ePspj8aYSr6IlBbTEUB6yPQCeuEsouuczxBOqgJAW8evg5rPb3YF3Q",
	"w1WM8jDpD07L6qutPOJqALKDklQDWQ5iOTSYrGC798Al6PXyd7tYN1Mn8nVzp7Gd6YFicMA13YCOM1dq",
	"4oZHIhgl0GwYJPdnOQipKrejhZAeotVs52g1JBJ7kVAbzAqfqmyEXGX3zVCJhCav1ui9X+pIScrgC+hS",
	"FjgrK6vljemD3Qf+SmcS0Zi6Lul3ftLaJNMYQUujBGDQB4dbAUa+Ba3DErAGU/U1YAqySkJFaQWbZ2sU",
	"p5gxfJLiiD0OhnTh7woSMz12eN+iFYc5uhH5FQuKJOUybqjpanYEQ91LbJbtIJuFpFcXEcykUiO0pkKg",
	"mOlqcfQMOaYW57474ujV4ryXtKSsxQXcdohqceTcP7IWR7ETp8XcG5QxxTjPrYe/GFf73pQuFOOqIK0v",
	"xFp82bFXinEeZnmQ5TFhg+W4urcou4Hu3inHte4GXiOFhyauaiYDUuJ6HAci1Xrc0YJIDzFrtnPMeljq",
	"cU1cA2yCX9VLBNEJtCZ24Z2VmDuAw6zDoycw3ZekJSvLBZzVvmocC7zr83QFOddGRonCsf3dpwJ5g5Cw",
	"/+tyeWbnYGa6srawv/eNc+f+cb5GJJ453Aox9I81dUUeshfE8XYs5DIuDRqXyKq/MZtdcbbu0mfcV1/Q",
	"fy3JubdBO/nPq1vOXMmNuHvN5HiCeys++DQsBhlqEm2HCb77r1omNOJk4OYNalf5u137xg5ne3MeqvoE",
	"7Dx6o5d3Oq3OKsAESxhp54dbzEJGmzpzpUZ2CTQicdggPRoTbpCCtpzV80ARJDgBFb2o4pTMiJahsLeM",
	"5fr7FdxgXDdR7s3sm9l+UJT7JwZEbAcbqLbH98kPPQUPO2Y1Zuw3oDiiwWfw9KCGGA0If7Gy2ZP/L+BP",
	"dUP+m/sGGdYLeYFMuA/qBaCBAmTz8EHQjHjgHDRMXQNK4Fe91ccCv+et87T/1wTVpwO/I5gamfpvAAAA",
	"//+jf14I9G4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
