// Code generated by mockery v2.53.6. DO NOT EDIT.

package gearset

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockGearSetRepository is an autogenerated mock type for the GearSetRepository type
type MockGearSetRepository struct {
	mock.Mock
}

type MockGearSetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGearSetRepository) EXPECT() *MockGearSetRepository_Expecter {
	return &MockGearSetRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, gs
func (_m *MockGearSetRepository) Create(ctx context.Context, gs *GearSet) error {
	ret := _m.Called(ctx, gs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *GearSet) error); ok {
		r0 = rf(ctx, gs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGearSetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGearSetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - gs *GearSet
func (_e *MockGearSetRepository_Expecter) Create(ctx interface{}, gs interface{}) *MockGearSetRepository_Create_Call {
	return &MockGearSetRepository_Create_Call{Call: _e.mock.On("Create", ctx, gs)}
}

func (_c *MockGearSetRepository_Create_Call) Run(run func(ctx context.Context, gs *GearSet)) *MockGearSetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*GearSet))
	})
	return _c
}

func (_c *MockGearSetRepository_Create_Call) Return(_a0 error) *MockGearSetRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGearSetRepository_Create_Call) RunAndReturn(run func(context.Context, *GearSet) error) *MockGearSetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockGearSetRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGearSetRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGearSetRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGearSetRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockGearSetRepository_Delete_Call {
	return &MockGearSetRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockGearSetRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGearSetRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGearSetRepository_Delete_Call) Return(_a0 error) *MockGearSetRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGearSetRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockGearSetRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockGearSetRepository) GetByID(ctx context.Context, id uuid.UUID) (*GearSet, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *GearSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*GearSet, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *GearSet); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GearSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGearSetRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockGearSetRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGearSetRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockGearSetRepository_GetByID_Call {
	return &MockGearSetRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockGearSetRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGearSetRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGearSetRepository_GetByID_Call) Return(_a0 *GearSet, _a1 error) *MockGearSetRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGearSetRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*GearSet, error)) *MockGearSetRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset, search, userID
func (_m *MockGearSetRepository) List(ctx context.Context, limit int, offset int, search string, userID *string) ([]*GearSet, int, error) {
	ret := _m.Called(ctx, limit, offset, search, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*GearSet
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, *string) ([]*GearSet, int, error)); ok {
		return rf(ctx, limit, offset, search, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, *string) []*GearSet); ok {
		r0 = rf(ctx, limit, offset, search, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GearSet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, *string) int); ok {
		r1 = rf(ctx, limit, offset, search, userID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, *string) error); ok {
		r2 = rf(ctx, limit, offset, search, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockGearSetRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGearSetRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
//   - search string
//   - userID *string
func (_e *MockGearSetRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}, search interface{}, userID interface{}) *MockGearSetRepository_List_Call {
	return &MockGearSetRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset, search, userID)}
}

func (_c *MockGearSetRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int, search string, userID *string)) *MockGearSetRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string), args[4].(*string))
	})
	return _c
}

func (_c *MockGearSetRepository_List_Call) Return(_a0 []*GearSet, _a1 int, _a2 error) *MockGearSetRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockGearSetRepository_List_Call) RunAndReturn(run func(context.Context, int, int, string, *string) ([]*GearSet, int, error)) *MockGearSetRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, gs
func (_m *MockGearSetRepository) Update(ctx context.Context, gs *GearSet) error {
	ret := _m.Called(ctx, gs)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *GearSet) error); ok {
		r0 = rf(ctx, gs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGearSetRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGearSetRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - gs *GearSet
func (_e *MockGearSetRepository_Expecter) Update(ctx interface{}, gs interface{}) *MockGearSetRepository_Update_Call {
	return &MockGearSetRepository_Update_Call{Call: _e.mock.On("Update", ctx, gs)}
}

func (_c *MockGearSetRepository_Update_Call) Run(run func(ctx context.Context, gs *GearSet)) *MockGearSetRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*GearSet))
	})
	return _c
}

func (_c *MockGearSetRepository_Update_Call) Return(_a0 error) *MockGearSetRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGearSetRepository_Update_Call) RunAndReturn(run func(context.Context, *GearSet) error) *MockGearSetRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGearSetRepository creates a new instance of MockGearSetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGearSetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGearSetRepository {
	mock := &MockGearSetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
