package gearset

import (
	"context"
	"log/slog"
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

func (m *MockRepository) Create(ctx context.Context, gs *GearSet) error {
	ret := m.Called(ctx, gs)
	return ret.Error(0)
}

func (m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*GearSet, error) {
	ret := m.Called(ctx, id)
	return ret.Get(0).(*GearSet), ret.Error(1)
}

func (m *MockRepository) Update(ctx context.Context, gs *GearSet) error {
	ret := m.Called(ctx, gs)
	return ret.Error(0)
}

func (m *MockRepository) List(ctx context.Context, limit, offset int, search string, userID *string) ([]*GearSet, int, error) {
	ret := m.Called(ctx, limit, offset, search, userID)
	return ret.Get(0).([]*GearSet), ret.Int(1), ret.Error(2)
}

func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := m.Called(ctx, id)
	return ret.Error(0)
}

func TestGearSetService_Create_UUIDv7(t *testing.T) {
	mockRepo := new(MockRepository)
	service := NewGearSetService(slog.Default(), mockRepo)

	// Expect the mock to be called with a GearSet
	// We capture the passed GearSet to verify its ID
	var capturedGS *GearSet
	mockRepo.On("Create", mock.Anything, mock.AnythingOfType("*gearset.GearSet")).Run(func(args mock.Arguments) {
		capturedGS = args.Get(1).(*GearSet)
	}).Return(nil)

	gs := &GearSet{
		Title:      "Test Gear Set",
		Author:     "user-1",
		Visibility: VisibilityPublic,
	}

	createdGS, err := service.Create(context.Background(), gs)

	assert.NoError(t, err)
	assert.NotNil(t, createdGS)

	// Verify the mock was called
	mockRepo.AssertExpectations(t)

	// Verify the ID is a UUID v7
	assert.NotEqual(t, uuid.Nil, capturedGS.ID)
	assert.Equal(t, uuid.Version(7), capturedGS.ID.Version(), "UUID must be version 7")
}
