// Code generated by mockery v2.53.6. DO NOT EDIT.

package log

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLogRepository is an autogenerated mock type for the LogRepository type
type MockLogRepository struct {
	mock.Mock
}

type MockLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogRepository) EXPECT() *MockLogRepository_Expecter {
	return &MockLogRepository_Expecter{mock: &_m.Mock}
}

// BatchCreate provides a mock function with given fields: ctx, deviceID, deviceName, entries
func (_m *MockLogRepository) BatchCreate(ctx context.Context, deviceID string, deviceName string, entries []LogEntry) (int, error) {
	ret := _m.Called(ctx, deviceID, deviceName, entries)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []LogEntry) (int, error)); ok {
		return rf(ctx, deviceID, deviceName, entries)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []LogEntry) int); ok {
		r0 = rf(ctx, deviceID, deviceName, entries)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []LogEntry) error); ok {
		r1 = rf(ctx, deviceID, deviceName, entries)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLogRepository_BatchCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreate'
type MockLogRepository_BatchCreate_Call struct {
	*mock.Call
}

// BatchCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceID string
//   - deviceName string
//   - entries []LogEntry
func (_e *MockLogRepository_Expecter) BatchCreate(ctx interface{}, deviceID interface{}, deviceName interface{}, entries interface{}) *MockLogRepository_BatchCreate_Call {
	return &MockLogRepository_BatchCreate_Call{Call: _e.mock.On("BatchCreate", ctx, deviceID, deviceName, entries)}
}

func (_c *MockLogRepository_BatchCreate_Call) Run(run func(ctx context.Context, deviceID string, deviceName string, entries []LogEntry)) *MockLogRepository_BatchCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]LogEntry))
	})
	return _c
}

func (_c *MockLogRepository_BatchCreate_Call) Return(_a0 int, _a1 error) *MockLogRepository_BatchCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLogRepository_BatchCreate_Call) RunAndReturn(run func(context.Context, string, string, []LogEntry) (int, error)) *MockLogRepository_BatchCreate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogRepository creates a new instance of MockLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogRepository {
	mock := &MockLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
