// Code generated by mockery v2.53.6. DO NOT EDIT.

package heartbeat

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHeartbeatRepository is an autogenerated mock type for the HeartbeatRepository type
type MockHeartbeatRepository struct {
	mock.Mock
}

type MockHeartbeatRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHeartbeatRepository) EXPECT() *MockHeartbeatRepository_Expecter {
	return &MockHeartbeatRepository_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockHeartbeatRepository) GetByUserID(ctx context.Context, userID string) (*Heartbeat, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *Heartbeat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Heartbeat, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Heartbeat); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Heartbeat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHeartbeatRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockHeartbeatRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockHeartbeatRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockHeartbeatRepository_GetByUserID_Call {
	return &MockHeartbeatRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockHeartbeatRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockHeartbeatRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockHeartbeatRepository_GetByUserID_Call) Return(_a0 *Heartbeat, _a1 error) *MockHeartbeatRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHeartbeatRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) (*Heartbeat, error)) *MockHeartbeatRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, hb
func (_m *MockHeartbeatRepository) Upsert(ctx context.Context, hb *Heartbeat) error {
	ret := _m.Called(ctx, hb)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Heartbeat) error); ok {
		r0 = rf(ctx, hb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHeartbeatRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockHeartbeatRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - hb *Heartbeat
func (_e *MockHeartbeatRepository_Expecter) Upsert(ctx interface{}, hb interface{}) *MockHeartbeatRepository_Upsert_Call {
	return &MockHeartbeatRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, hb)}
}

func (_c *MockHeartbeatRepository_Upsert_Call) Run(run func(ctx context.Context, hb *Heartbeat)) *MockHeartbeatRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Heartbeat))
	})
	return _c
}

func (_c *MockHeartbeatRepository_Upsert_Call) Return(_a0 error) *MockHeartbeatRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHeartbeatRepository_Upsert_Call) RunAndReturn(run func(context.Context, *Heartbeat) error) *MockHeartbeatRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHeartbeatRepository creates a new instance of MockHeartbeatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHeartbeatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHeartbeatRepository {
	mock := &MockHeartbeatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
