// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	trip "summitmate/internal/trip"
)

// MockTripAccessChecker is an autogenerated mock type for the TripAccessChecker type
type MockTripAccessChecker struct {
	mock.Mock
}

type MockTripAccessChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripAccessChecker) EXPECT() *MockTripAccessChecker_Expecter {
	return &MockTripAccessChecker_Expecter{mock: &_m.Mock}
}

// RequireMember provides a mock function with given fields: ctx, tripID, userID
func (_m *MockTripAccessChecker) RequireMember(ctx context.Context, tripID string, userID string) error {
	ret := _m.Called(ctx, tripID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RequireMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tripID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripAccessChecker_RequireMember_Call is a *mock.Call that shadows Run/Return methods with type-safe versions
type MockTripAccessChecker_RequireMember_Call struct {
	*mock.Call
}

func (_e *MockTripAccessChecker_Expecter) RequireMember(ctx interface{}, tripID interface{}, userID interface{}) *MockTripAccessChecker_RequireMember_Call {
	return &MockTripAccessChecker_RequireMember_Call{Call: _e.mock.On("RequireMember", ctx, tripID, userID)}
}

func (_c *MockTripAccessChecker_RequireMember_Call) Run(run func(ctx context.Context, tripID string, userID string)) *MockTripAccessChecker_RequireMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripAccessChecker_RequireMember_Call) Return(_a0 error) *MockTripAccessChecker_RequireMember_Call {
	_c.Call.Return(_a0)
	return _c
}

// RequireMemberForTrip provides a mock function with given fields: ctx, t, userID
func (_m *MockTripAccessChecker) RequireMemberForTrip(ctx context.Context, t *trip.Trip, userID string) error {
	ret := _m.Called(ctx, t, userID)

	if len(ret) == 0 {
		panic("no return value specified for RequireMemberForTrip")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.Trip, string) error); ok {
		r0 = rf(ctx, t, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripAccessChecker_RequireMemberForTrip_Call is a *mock.Call that shadows Run/Return methods with type-safe versions
type MockTripAccessChecker_RequireMemberForTrip_Call struct {
	*mock.Call
}

func (_e *MockTripAccessChecker_Expecter) RequireMemberForTrip(ctx interface{}, t interface{}, userID interface{}) *MockTripAccessChecker_RequireMemberForTrip_Call {
	return &MockTripAccessChecker_RequireMemberForTrip_Call{Call: _e.mock.On("RequireMemberForTrip", ctx, t, userID)}
}

func (_c *MockTripAccessChecker_RequireMemberForTrip_Call) Run(run func(ctx context.Context, t *trip.Trip, userID string)) *MockTripAccessChecker_RequireMemberForTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*trip.Trip), args[2].(string))
	})
	return _c
}

func (_c *MockTripAccessChecker_RequireMemberForTrip_Call) Return(_a0 error) *MockTripAccessChecker_RequireMemberForTrip_Call {
	_c.Call.Return(_a0)
	return _c
}

// RequireOwner provides a mock function with given fields: t, userID
func (_m *MockTripAccessChecker) RequireOwner(t *trip.Trip, userID string) error {
	ret := _m.Called(t, userID)

	if len(ret) == 0 {
		panic("no return value specified for RequireOwner")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*trip.Trip, string) error); ok {
		r0 = rf(t, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripAccessChecker_RequireOwner_Call is a *mock.Call that shadows Run/Return methods with type-safe versions
type MockTripAccessChecker_RequireOwner_Call struct {
	*mock.Call
}

func (_e *MockTripAccessChecker_Expecter) RequireOwner(t interface{}, userID interface{}) *MockTripAccessChecker_RequireOwner_Call {
	return &MockTripAccessChecker_RequireOwner_Call{Call: _e.mock.On("RequireOwner", t, userID)}
}

func (_c *MockTripAccessChecker_RequireOwner_Call) Run(run func(t *trip.Trip, userID string)) *MockTripAccessChecker_RequireOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*trip.Trip), args[1].(string))
	})
	return _c
}

func (_c *MockTripAccessChecker_RequireOwner_Call) Return(_a0 error) *MockTripAccessChecker_RequireOwner_Call {
	_c.Call.Return(_a0)
	return _c
}

// RequireOwnerByID provides a mock function with given fields: ctx, tripID, userID
func (_m *MockTripAccessChecker) RequireOwnerByID(ctx context.Context, tripID string, userID string) error {
	ret := _m.Called(ctx, tripID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RequireOwnerByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tripID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripAccessChecker_RequireOwnerByID_Call is a *mock.Call that shadows Run/Return methods with type-safe versions
type MockTripAccessChecker_RequireOwnerByID_Call struct {
	*mock.Call
}

func (_e *MockTripAccessChecker_Expecter) RequireOwnerByID(ctx interface{}, tripID interface{}, userID interface{}) *MockTripAccessChecker_RequireOwnerByID_Call {
	return &MockTripAccessChecker_RequireOwnerByID_Call{Call: _e.mock.On("RequireOwnerByID", ctx, tripID, userID)}
}

func (_c *MockTripAccessChecker_RequireOwnerByID_Call) Run(run func(ctx context.Context, tripID string, userID string)) *MockTripAccessChecker_RequireOwnerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripAccessChecker_RequireOwnerByID_Call) Return(_a0 error) *MockTripAccessChecker_RequireOwnerByID_Call {
	_c.Call.Return(_a0)
	return _c
}

// RequireRole provides a mock function with given fields: ctx, t, userID, allowedRoles
func (_m *MockTripAccessChecker) RequireRole(ctx context.Context, t *trip.Trip, userID string, allowedRoles ...string) error {
	_va := make([]interface{}, len(allowedRoles))
	for _i := range allowedRoles {
		_va[_i] = allowedRoles[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, t, userID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RequireRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.Trip, string, ...string) error); ok {
		r0 = rf(ctx, t, userID, allowedRoles...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockTripAccessChecker creates a new instance of MockTripAccessChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripAccessChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripAccessChecker {
	mock := &MockTripAccessChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
