// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	trip "summitmate/internal/trip"

	mock "github.com/stretchr/testify/mock"
)

// MockTripMealRepository is an autogenerated mock type for the TripMealRepository type
type MockTripMealRepository struct {
	mock.Mock
}

type MockTripMealRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripMealRepository) EXPECT() *MockTripMealRepository_Expecter {
	return &MockTripMealRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *MockTripMealRepository) Create(ctx context.Context, item *trip.TripMealItem) (*trip.TripMealItem, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *trip.TripMealItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.TripMealItem) (*trip.TripMealItem, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *trip.TripMealItem) *trip.TripMealItem); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.TripMealItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *trip.TripMealItem) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripMealRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTripMealRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *trip.TripMealItem
func (_e *MockTripMealRepository_Expecter) Create(ctx interface{}, item interface{}) *MockTripMealRepository_Create_Call {
	return &MockTripMealRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *MockTripMealRepository_Create_Call) Run(run func(ctx context.Context, item *trip.TripMealItem)) *MockTripMealRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*trip.TripMealItem))
	})
	return _c
}

func (_c *MockTripMealRepository_Create_Call) Return(_a0 *trip.TripMealItem, _a1 error) *MockTripMealRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripMealRepository_Create_Call) RunAndReturn(run func(context.Context, *trip.TripMealItem) (*trip.TripMealItem, error)) *MockTripMealRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, tripID
func (_m *MockTripMealRepository) Delete(ctx context.Context, id string, tripID string) error {
	ret := _m.Called(ctx, id, tripID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, tripID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripMealRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTripMealRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - tripID string
func (_e *MockTripMealRepository_Expecter) Delete(ctx interface{}, id interface{}, tripID interface{}) *MockTripMealRepository_Delete_Call {
	return &MockTripMealRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, tripID)}
}

func (_c *MockTripMealRepository_Delete_Call) Run(run func(ctx context.Context, id string, tripID string)) *MockTripMealRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripMealRepository_Delete_Call) Return(_a0 error) *MockTripMealRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripMealRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTripMealRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id, tripID
func (_m *MockTripMealRepository) GetByID(ctx context.Context, id string, tripID string) (*trip.TripMealItem, error) {
	ret := _m.Called(ctx, id, tripID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *trip.TripMealItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*trip.TripMealItem, error)); ok {
		return rf(ctx, id, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *trip.TripMealItem); ok {
		r0 = rf(ctx, id, tripID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.TripMealItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripMealRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTripMealRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - tripID string
func (_e *MockTripMealRepository_Expecter) GetByID(ctx interface{}, id interface{}, tripID interface{}) *MockTripMealRepository_GetByID_Call {
	return &MockTripMealRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, tripID)}
}

func (_c *MockTripMealRepository_GetByID_Call) Run(run func(ctx context.Context, id string, tripID string)) *MockTripMealRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripMealRepository_GetByID_Call) Return(_a0 *trip.TripMealItem, _a1 error) *MockTripMealRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripMealRepository_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*trip.TripMealItem, error)) *MockTripMealRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTripID provides a mock function with given fields: ctx, tripID
func (_m *MockTripMealRepository) ListByTripID(ctx context.Context, tripID string) ([]*trip.TripMealItem, error) {
	ret := _m.Called(ctx, tripID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTripID")
	}

	var r0 []*trip.TripMealItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*trip.TripMealItem, error)); ok {
		return rf(ctx, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*trip.TripMealItem); ok {
		r0 = rf(ctx, tripID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trip.TripMealItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripMealRepository_ListByTripID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTripID'
type MockTripMealRepository_ListByTripID_Call struct {
	*mock.Call
}

// ListByTripID is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
func (_e *MockTripMealRepository_Expecter) ListByTripID(ctx interface{}, tripID interface{}) *MockTripMealRepository_ListByTripID_Call {
	return &MockTripMealRepository_ListByTripID_Call{Call: _e.mock.On("ListByTripID", ctx, tripID)}
}

func (_c *MockTripMealRepository_ListByTripID_Call) Run(run func(ctx context.Context, tripID string)) *MockTripMealRepository_ListByTripID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripMealRepository_ListByTripID_Call) Return(_a0 []*trip.TripMealItem, _a1 error) *MockTripMealRepository_ListByTripID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripMealRepository_ListByTripID_Call) RunAndReturn(run func(context.Context, string) ([]*trip.TripMealItem, error)) *MockTripMealRepository_ListByTripID_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceAll provides a mock function with given fields: ctx, tripID, items
func (_m *MockTripMealRepository) ReplaceAll(ctx context.Context, tripID string, items []*trip.TripMealItem) error {
	ret := _m.Called(ctx, tripID, items)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*trip.TripMealItem) error); ok {
		r0 = rf(ctx, tripID, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripMealRepository_ReplaceAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceAll'
type MockTripMealRepository_ReplaceAll_Call struct {
	*mock.Call
}

// ReplaceAll is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - items []*trip.TripMealItem
func (_e *MockTripMealRepository_Expecter) ReplaceAll(ctx interface{}, tripID interface{}, items interface{}) *MockTripMealRepository_ReplaceAll_Call {
	return &MockTripMealRepository_ReplaceAll_Call{Call: _e.mock.On("ReplaceAll", ctx, tripID, items)}
}

func (_c *MockTripMealRepository_ReplaceAll_Call) Run(run func(ctx context.Context, tripID string, items []*trip.TripMealItem)) *MockTripMealRepository_ReplaceAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]*trip.TripMealItem))
	})
	return _c
}

func (_c *MockTripMealRepository_ReplaceAll_Call) Return(_a0 error) *MockTripMealRepository_ReplaceAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripMealRepository_ReplaceAll_Call) RunAndReturn(run func(context.Context, string, []*trip.TripMealItem) error) *MockTripMealRepository_ReplaceAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, item
func (_m *MockTripMealRepository) Update(ctx context.Context, item *trip.TripMealItem) (*trip.TripMealItem, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *trip.TripMealItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.TripMealItem) (*trip.TripMealItem, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *trip.TripMealItem) *trip.TripMealItem); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.TripMealItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *trip.TripMealItem) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripMealRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTripMealRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - item *trip.TripMealItem
func (_e *MockTripMealRepository_Expecter) Update(ctx interface{}, item interface{}) *MockTripMealRepository_Update_Call {
	return &MockTripMealRepository_Update_Call{Call: _e.mock.On("Update", ctx, item)}
}

func (_c *MockTripMealRepository_Update_Call) Run(run func(ctx context.Context, item *trip.TripMealItem)) *MockTripMealRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*trip.TripMealItem))
	})
	return _c
}

func (_c *MockTripMealRepository_Update_Call) Return(_a0 *trip.TripMealItem, _a1 error) *MockTripMealRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripMealRepository_Update_Call) RunAndReturn(run func(context.Context, *trip.TripMealItem) (*trip.TripMealItem, error)) *MockTripMealRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTripMealRepository creates a new instance of MockTripMealRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripMealRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripMealRepository {
	mock := &MockTripMealRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
