// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	trip "summitmate/internal/trip"
)

// MockTripRepository is an autogenerated mock type for the TripRepository type
type MockTripRepository struct {
	mock.Mock
}

type MockTripRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripRepository) EXPECT() *MockTripRepository_Expecter {
	return &MockTripRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockTripRepository) Create(ctx context.Context, _a1 *trip.Trip) (*trip.Trip, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.Trip) (*trip.Trip, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *trip.Trip) *trip.Trip); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *trip.Trip) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTripRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *trip.Trip
func (_e *MockTripRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockTripRepository_Create_Call {
	return &MockTripRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockTripRepository_Create_Call) Run(run func(ctx context.Context, _a1 *trip.Trip)) *MockTripRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*trip.Trip))
	})
	return _c
}

func (_c *MockTripRepository_Create_Call) Return(_a0 *trip.Trip, _a1 error) *MockTripRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripRepository_Create_Call) RunAndReturn(run func(context.Context, *trip.Trip) (*trip.Trip, error)) *MockTripRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function with given fields: ctx, id
func (_m *MockTripRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockTripRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTripRepository_Expecter) DeleteByID(ctx interface{}, id interface{}) *MockTripRepository_DeleteByID_Call {
	return &MockTripRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockTripRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockTripRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripRepository_DeleteByID_Call) Return(_a0 error) *MockTripRepository_DeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripRepository_DeleteByID_Call) RunAndReturn(run func(context.Context, string) error) *MockTripRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTripRepository) GetByID(ctx context.Context, id string) (*trip.Trip, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*trip.Trip, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *trip.Trip); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTripRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTripRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTripRepository_GetByID_Call {
	return &MockTripRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTripRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockTripRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripRepository_GetByID_Call) Return(_a0 *trip.Trip, _a1 error) *MockTripRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*trip.Trip, error)) *MockTripRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID, page, limit, search
func (_m *MockTripRepository) ListByUserID(ctx context.Context, userID string, page int, limit int, search string) ([]*trip.Trip, int, bool, error) {
	ret := _m.Called(ctx, userID, page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*trip.Trip
	var r1 int
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) ([]*trip.Trip, int, bool, error)); ok {
		return rf(ctx, userID, page, limit, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) []*trip.Trip); ok {
		r0 = rf(ctx, userID, page, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, string) int); ok {
		r1 = rf(ctx, userID, page, limit, search)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, string) bool); ok {
		r2 = rf(ctx, userID, page, limit, search)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, int, int, string) error); ok {
		r3 = rf(ctx, userID, page, limit, search)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockTripRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockTripRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int
//   - limit int
//   - search string
func (_e *MockTripRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, page interface{}, limit interface{}, search interface{}) *MockTripRepository_ListByUserID_Call {
	return &MockTripRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, page, limit, search)}
}

func (_c *MockTripRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID string, page int, limit int, search string)) *MockTripRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *MockTripRepository_ListByUserID_Call) Return(_a0 []*trip.Trip, _a1 int, _a2 bool, _a3 error) *MockTripRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockTripRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, string, int, int, string) ([]*trip.Trip, int, bool, error)) *MockTripRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1, lastUpdatedAt
func (_m *MockTripRepository) Update(ctx context.Context, _a1 *trip.Trip, lastUpdatedAt *time.Time) (*trip.Trip, error) {
	ret := _m.Called(ctx, _a1, lastUpdatedAt)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.Trip, *time.Time) (*trip.Trip, error)); ok {
		return rf(ctx, _a1, lastUpdatedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *trip.Trip, *time.Time) *trip.Trip); ok {
		r0 = rf(ctx, _a1, lastUpdatedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *trip.Trip, *time.Time) error); ok {
		r1 = rf(ctx, _a1, lastUpdatedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTripRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *trip.Trip
//   - lastUpdatedAt *time.Time
func (_e *MockTripRepository_Expecter) Update(ctx interface{}, _a1 interface{}, lastUpdatedAt interface{}) *MockTripRepository_Update_Call {
	return &MockTripRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1, lastUpdatedAt)}
}

func (_c *MockTripRepository_Update_Call) Run(run func(ctx context.Context, _a1 *trip.Trip, lastUpdatedAt *time.Time)) *MockTripRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*trip.Trip), args[2].(*time.Time))
	})
	return _c
}

func (_c *MockTripRepository_Update_Call) Return(_a0 *trip.Trip, _a1 error) *MockTripRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripRepository_Update_Call) RunAndReturn(run func(context.Context, *trip.Trip, *time.Time) (*trip.Trip, error)) *MockTripRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOwner provides a mock function with given fields: ctx, id, nextOwnerID
func (_m *MockTripRepository) UpdateOwner(ctx context.Context, id string, nextOwnerID string) error {
	ret := _m.Called(ctx, id, nextOwnerID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOwner")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, nextOwnerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripRepository_UpdateOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOwner'
type MockTripRepository_UpdateOwner_Call struct {
	*mock.Call
}

// UpdateOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - nextOwnerID string
func (_e *MockTripRepository_Expecter) UpdateOwner(ctx interface{}, id interface{}, nextOwnerID interface{}) *MockTripRepository_UpdateOwner_Call {
	return &MockTripRepository_UpdateOwner_Call{Call: _e.mock.On("UpdateOwner", ctx, id, nextOwnerID)}
}

func (_c *MockTripRepository_UpdateOwner_Call) Run(run func(ctx context.Context, id string, nextOwnerID string)) *MockTripRepository_UpdateOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripRepository_UpdateOwner_Call) Return(_a0 error) *MockTripRepository_UpdateOwner_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripRepository_UpdateOwner_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTripRepository_UpdateOwner_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTripRepository creates a new instance of MockTripRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripRepository {
	mock := &MockTripRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
