// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	trip "summitmate/internal/trip"

	mock "github.com/stretchr/testify/mock"
)

// MockTripMemberRepository is an autogenerated mock type for the TripMemberRepository type
type MockTripMemberRepository struct {
	mock.Mock
}

type MockTripMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripMemberRepository) EXPECT() *MockTripMemberRepository_Expecter {
	return &MockTripMemberRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, tripID, userID, role
func (_m *MockTripMemberRepository) AddMember(ctx context.Context, tripID string, userID string, role string) error {
	ret := _m.Called(ctx, tripID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, tripID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripMemberRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockTripMemberRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
//   - role string
func (_e *MockTripMemberRepository_Expecter) AddMember(ctx interface{}, tripID interface{}, userID interface{}, role interface{}) *MockTripMemberRepository_AddMember_Call {
	return &MockTripMemberRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, tripID, userID, role)}
}

func (_c *MockTripMemberRepository_AddMember_Call) Run(run func(ctx context.Context, tripID string, userID string, role string)) *MockTripMemberRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTripMemberRepository_AddMember_Call) Return(_a0 error) *MockTripMemberRepository_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripMemberRepository_AddMember_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockTripMemberRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// BatchAddMembers provides a mock function with given fields: ctx, tripID, userIDs
func (_m *MockTripMemberRepository) BatchAddMembers(ctx context.Context, tripID string, userIDs []string) error {
	ret := _m.Called(ctx, tripID, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for BatchAddMembers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, tripID, userIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripMemberRepository_BatchAddMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchAddMembers'
type MockTripMemberRepository_BatchAddMembers_Call struct {
	*mock.Call
}

// BatchAddMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userIDs []string
func (_e *MockTripMemberRepository_Expecter) BatchAddMembers(ctx interface{}, tripID interface{}, userIDs interface{}) *MockTripMemberRepository_BatchAddMembers_Call {
	return &MockTripMemberRepository_BatchAddMembers_Call{Call: _e.mock.On("BatchAddMembers", ctx, tripID, userIDs)}
}

func (_c *MockTripMemberRepository_BatchAddMembers_Call) Run(run func(ctx context.Context, tripID string, userIDs []string)) *MockTripMemberRepository_BatchAddMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockTripMemberRepository_BatchAddMembers_Call) Return(_a0 error) *MockTripMemberRepository_BatchAddMembers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripMemberRepository_BatchAddMembers_Call) RunAndReturn(run func(context.Context, string, []string) error) *MockTripMemberRepository_BatchAddMembers_Call {
	_c.Call.Return(run)
	return _c
}

// BatchRemoveMembers provides a mock function with given fields: ctx, tripID, userIDs
func (_m *MockTripMemberRepository) BatchRemoveMembers(ctx context.Context, tripID string, userIDs []string) error {
	ret := _m.Called(ctx, tripID, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for BatchRemoveMembers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, tripID, userIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripMemberRepository_BatchRemoveMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchRemoveMembers'
type MockTripMemberRepository_BatchRemoveMembers_Call struct {
	*mock.Call
}

// BatchRemoveMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userIDs []string
func (_e *MockTripMemberRepository_Expecter) BatchRemoveMembers(ctx interface{}, tripID interface{}, userIDs interface{}) *MockTripMemberRepository_BatchRemoveMembers_Call {
	return &MockTripMemberRepository_BatchRemoveMembers_Call{Call: _e.mock.On("BatchRemoveMembers", ctx, tripID, userIDs)}
}

func (_c *MockTripMemberRepository_BatchRemoveMembers_Call) Run(run func(ctx context.Context, tripID string, userIDs []string)) *MockTripMemberRepository_BatchRemoveMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockTripMemberRepository_BatchRemoveMembers_Call) Return(_a0 error) *MockTripMemberRepository_BatchRemoveMembers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripMemberRepository_BatchRemoveMembers_Call) RunAndReturn(run func(context.Context, string, []string) error) *MockTripMemberRepository_BatchRemoveMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function with given fields: ctx, tripID, userID
func (_m *MockTripMemberRepository) GetRole(ctx context.Context, tripID string, userID string) (string, error) {
	ret := _m.Called(ctx, tripID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, tripID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, tripID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tripID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripMemberRepository_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type MockTripMemberRepository_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
func (_e *MockTripMemberRepository_Expecter) GetRole(ctx interface{}, tripID interface{}, userID interface{}) *MockTripMemberRepository_GetRole_Call {
	return &MockTripMemberRepository_GetRole_Call{Call: _e.mock.On("GetRole", ctx, tripID, userID)}
}

func (_c *MockTripMemberRepository_GetRole_Call) Run(run func(ctx context.Context, tripID string, userID string)) *MockTripMemberRepository_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripMemberRepository_GetRole_Call) Return(_a0 string, _a1 error) *MockTripMemberRepository_GetRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripMemberRepository_GetRole_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockTripMemberRepository_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// IsMember provides a mock function with given fields: ctx, tripID, userID
func (_m *MockTripMemberRepository) IsMember(ctx context.Context, tripID string, userID string) (bool, error) {
	ret := _m.Called(ctx, tripID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, tripID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, tripID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tripID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripMemberRepository_IsMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMember'
type MockTripMemberRepository_IsMember_Call struct {
	*mock.Call
}

// IsMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
func (_e *MockTripMemberRepository_Expecter) IsMember(ctx interface{}, tripID interface{}, userID interface{}) *MockTripMemberRepository_IsMember_Call {
	return &MockTripMemberRepository_IsMember_Call{Call: _e.mock.On("IsMember", ctx, tripID, userID)}
}

func (_c *MockTripMemberRepository_IsMember_Call) Run(run func(ctx context.Context, tripID string, userID string)) *MockTripMemberRepository_IsMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripMemberRepository_IsMember_Call) Return(_a0 bool, _a1 error) *MockTripMemberRepository_IsMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripMemberRepository_IsMember_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockTripMemberRepository_IsMember_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTripID provides a mock function with given fields: ctx, tripID
func (_m *MockTripMemberRepository) ListByTripID(ctx context.Context, tripID string) ([]*trip.TripMember, error) {
	ret := _m.Called(ctx, tripID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTripID")
	}

	var r0 []*trip.TripMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*trip.TripMember, error)); ok {
		return rf(ctx, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*trip.TripMember); ok {
		r0 = rf(ctx, tripID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trip.TripMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripMemberRepository_ListByTripID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTripID'
type MockTripMemberRepository_ListByTripID_Call struct {
	*mock.Call
}

// ListByTripID is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
func (_e *MockTripMemberRepository_Expecter) ListByTripID(ctx interface{}, tripID interface{}) *MockTripMemberRepository_ListByTripID_Call {
	return &MockTripMemberRepository_ListByTripID_Call{Call: _e.mock.On("ListByTripID", ctx, tripID)}
}

func (_c *MockTripMemberRepository_ListByTripID_Call) Run(run func(ctx context.Context, tripID string)) *MockTripMemberRepository_ListByTripID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripMemberRepository_ListByTripID_Call) Return(_a0 []*trip.TripMember, _a1 error) *MockTripMemberRepository_ListByTripID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripMemberRepository_ListByTripID_Call) RunAndReturn(run func(context.Context, string) ([]*trip.TripMember, error)) *MockTripMemberRepository_ListByTripID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, tripID, userID
func (_m *MockTripMemberRepository) RemoveMember(ctx context.Context, tripID string, userID string) error {
	ret := _m.Called(ctx, tripID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tripID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripMemberRepository_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockTripMemberRepository_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
func (_e *MockTripMemberRepository_Expecter) RemoveMember(ctx interface{}, tripID interface{}, userID interface{}) *MockTripMemberRepository_RemoveMember_Call {
	return &MockTripMemberRepository_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, tripID, userID)}
}

func (_c *MockTripMemberRepository_RemoveMember_Call) Run(run func(ctx context.Context, tripID string, userID string)) *MockTripMemberRepository_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripMemberRepository_RemoveMember_Call) Return(_a0 error) *MockTripMemberRepository_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripMemberRepository_RemoveMember_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTripMemberRepository_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberRole provides a mock function with given fields: ctx, tripID, userID, role
func (_m *MockTripMemberRepository) UpdateMemberRole(ctx context.Context, tripID string, userID string, role string) error {
	ret := _m.Called(ctx, tripID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, tripID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripMemberRepository_UpdateMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberRole'
type MockTripMemberRepository_UpdateMemberRole_Call struct {
	*mock.Call
}

// UpdateMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
//   - role string
func (_e *MockTripMemberRepository_Expecter) UpdateMemberRole(ctx interface{}, tripID interface{}, userID interface{}, role interface{}) *MockTripMemberRepository_UpdateMemberRole_Call {
	return &MockTripMemberRepository_UpdateMemberRole_Call{Call: _e.mock.On("UpdateMemberRole", ctx, tripID, userID, role)}
}

func (_c *MockTripMemberRepository_UpdateMemberRole_Call) Run(run func(ctx context.Context, tripID string, userID string, role string)) *MockTripMemberRepository_UpdateMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTripMemberRepository_UpdateMemberRole_Call) Return(_a0 error) *MockTripMemberRepository_UpdateMemberRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripMemberRepository_UpdateMemberRole_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockTripMemberRepository_UpdateMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTripMemberRepository creates a new instance of MockTripMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripMemberRepository {
	mock := &MockTripMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
