// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	trip "summitmate/internal/trip"

	mock "github.com/stretchr/testify/mock"
)

// MockTripService is an autogenerated mock type for the TripService type
type MockTripService struct {
	mock.Mock
}

type MockTripService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripService) EXPECT() *MockTripService_Expecter {
	return &MockTripService_Expecter{mock: &_m.Mock}
}

// AddItineraryItem provides a mock function with given fields: ctx, tripID, userID, req
func (_m *MockTripService) AddItineraryItem(ctx context.Context, tripID string, userID string, req *trip.ItineraryItemRequest) (*trip.ItineraryItem, error) {
	ret := _m.Called(ctx, tripID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddItineraryItem")
	}

	var r0 *trip.ItineraryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *trip.ItineraryItemRequest) (*trip.ItineraryItem, error)); ok {
		return rf(ctx, tripID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *trip.ItineraryItemRequest) *trip.ItineraryItem); ok {
		r0 = rf(ctx, tripID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.ItineraryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *trip.ItineraryItemRequest) error); ok {
		r1 = rf(ctx, tripID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_AddItineraryItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItineraryItem'
type MockTripService_AddItineraryItem_Call struct {
	*mock.Call
}

// AddItineraryItem is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
//   - req *trip.ItineraryItemRequest
func (_e *MockTripService_Expecter) AddItineraryItem(ctx interface{}, tripID interface{}, userID interface{}, req interface{}) *MockTripService_AddItineraryItem_Call {
	return &MockTripService_AddItineraryItem_Call{Call: _e.mock.On("AddItineraryItem", ctx, tripID, userID, req)}
}

func (_c *MockTripService_AddItineraryItem_Call) Run(run func(ctx context.Context, tripID string, userID string, req *trip.ItineraryItemRequest)) *MockTripService_AddItineraryItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*trip.ItineraryItemRequest))
	})
	return _c
}

func (_c *MockTripService_AddItineraryItem_Call) Return(_a0 *trip.ItineraryItem, _a1 error) *MockTripService_AddItineraryItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_AddItineraryItem_Call) RunAndReturn(run func(context.Context, string, string, *trip.ItineraryItemRequest) (*trip.ItineraryItem, error)) *MockTripService_AddItineraryItem_Call {
	_c.Call.Return(run)
	return _c
}

// AddMealPlanDay provides a mock function with given fields: ctx, tripID, userID, name, linkedDay
func (_m *MockTripService) AddMealPlanDay(ctx context.Context, tripID string, userID string, name string, linkedDay *string) (*trip.MealPlanDay, error) {
	ret := _m.Called(ctx, tripID, userID, name, linkedDay)

	if len(ret) == 0 {
		panic("no return value specified for AddMealPlanDay")
	}

	var r0 *trip.MealPlanDay
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) (*trip.MealPlanDay, error)); ok {
		return rf(ctx, tripID, userID, name, linkedDay)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) *trip.MealPlanDay); ok {
		r0 = rf(ctx, tripID, userID, name, linkedDay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.MealPlanDay)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *string) error); ok {
		r1 = rf(ctx, tripID, userID, name, linkedDay)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_AddMealPlanDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMealPlanDay'
type MockTripService_AddMealPlanDay_Call struct {
	*mock.Call
}

// AddMealPlanDay is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
//   - name string
//   - linkedDay *string
func (_e *MockTripService_Expecter) AddMealPlanDay(ctx interface{}, tripID interface{}, userID interface{}, name interface{}, linkedDay interface{}) *MockTripService_AddMealPlanDay_Call {
	return &MockTripService_AddMealPlanDay_Call{Call: _e.mock.On("AddMealPlanDay", ctx, tripID, userID, name, linkedDay)}
}

func (_c *MockTripService_AddMealPlanDay_Call) Run(run func(ctx context.Context, tripID string, userID string, name string, linkedDay *string)) *MockTripService_AddMealPlanDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*string))
	})
	return _c
}

func (_c *MockTripService_AddMealPlanDay_Call) Return(_a0 *trip.MealPlanDay, _a1 error) *MockTripService_AddMealPlanDay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_AddMealPlanDay_Call) RunAndReturn(run func(context.Context, string, string, string, *string) (*trip.MealPlanDay, error)) *MockTripService_AddMealPlanDay_Call {
	_c.Call.Return(run)
	return _c
}

// AddMember provides a mock function with given fields: ctx, tripID, userID, targetUserID
func (_m *MockTripService) AddMember(ctx context.Context, tripID string, userID string, targetUserID string) (*trip.TripMember, error) {
	ret := _m.Called(ctx, tripID, userID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 *trip.TripMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*trip.TripMember, error)); ok {
		return rf(ctx, tripID, userID, targetUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *trip.TripMember); ok {
		r0 = rf(ctx, tripID, userID, targetUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.TripMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, tripID, userID, targetUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockTripService_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
//   - targetUserID string
func (_e *MockTripService_Expecter) AddMember(ctx interface{}, tripID interface{}, userID interface{}, targetUserID interface{}) *MockTripService_AddMember_Call {
	return &MockTripService_AddMember_Call{Call: _e.mock.On("AddMember", ctx, tripID, userID, targetUserID)}
}

func (_c *MockTripService_AddMember_Call) Run(run func(ctx context.Context, tripID string, userID string, targetUserID string)) *MockTripService_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTripService_AddMember_Call) Return(_a0 *trip.TripMember, _a1 error) *MockTripService_AddMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_AddMember_Call) RunAndReturn(run func(context.Context, string, string, string) (*trip.TripMember, error)) *MockTripService_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// BatchAddMembers provides a mock function with given fields: ctx, tripID, actionUserID, targetUserIDs
func (_m *MockTripService) BatchAddMembers(ctx context.Context, tripID string, actionUserID string, targetUserIDs []string) error {
	ret := _m.Called(ctx, tripID, actionUserID, targetUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for BatchAddMembers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = rf(ctx, tripID, actionUserID, targetUserIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripService_BatchAddMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchAddMembers'
type MockTripService_BatchAddMembers_Call struct {
	*mock.Call
}

// BatchAddMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - actionUserID string
//   - targetUserIDs []string
func (_e *MockTripService_Expecter) BatchAddMembers(ctx interface{}, tripID interface{}, actionUserID interface{}, targetUserIDs interface{}) *MockTripService_BatchAddMembers_Call {
	return &MockTripService_BatchAddMembers_Call{Call: _e.mock.On("BatchAddMembers", ctx, tripID, actionUserID, targetUserIDs)}
}

func (_c *MockTripService_BatchAddMembers_Call) Run(run func(ctx context.Context, tripID string, actionUserID string, targetUserIDs []string)) *MockTripService_BatchAddMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockTripService_BatchAddMembers_Call) Return(_a0 error) *MockTripService_BatchAddMembers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripService_BatchAddMembers_Call) RunAndReturn(run func(context.Context, string, string, []string) error) *MockTripService_BatchAddMembers_Call {
	_c.Call.Return(run)
	return _c
}

// BatchRemoveMembers provides a mock function with given fields: ctx, tripID, actionUserID, targetUserIDs
func (_m *MockTripService) BatchRemoveMembers(ctx context.Context, tripID string, actionUserID string, targetUserIDs []string) error {
	ret := _m.Called(ctx, tripID, actionUserID, targetUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for BatchRemoveMembers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) error); ok {
		r0 = rf(ctx, tripID, actionUserID, targetUserIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripService_BatchRemoveMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchRemoveMembers'
type MockTripService_BatchRemoveMembers_Call struct {
	*mock.Call
}

// BatchRemoveMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - actionUserID string
//   - targetUserIDs []string
func (_e *MockTripService_Expecter) BatchRemoveMembers(ctx interface{}, tripID interface{}, actionUserID interface{}, targetUserIDs interface{}) *MockTripService_BatchRemoveMembers_Call {
	return &MockTripService_BatchRemoveMembers_Call{Call: _e.mock.On("BatchRemoveMembers", ctx, tripID, actionUserID, targetUserIDs)}
}

func (_c *MockTripService_BatchRemoveMembers_Call) Run(run func(ctx context.Context, tripID string, actionUserID string, targetUserIDs []string)) *MockTripService_BatchRemoveMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockTripService_BatchRemoveMembers_Call) Return(_a0 error) *MockTripService_BatchRemoveMembers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripService_BatchRemoveMembers_Call) RunAndReturn(run func(context.Context, string, string, []string) error) *MockTripService_BatchRemoveMembers_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTrip provides a mock function with given fields: ctx, userID, req
func (_m *MockTripService) CreateTrip(ctx context.Context, userID string, req *trip.TripCreateRequest) (*trip.Trip, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTrip")
	}

	var r0 *trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *trip.TripCreateRequest) (*trip.Trip, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *trip.TripCreateRequest) *trip.Trip); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *trip.TripCreateRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_CreateTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTrip'
type MockTripService_CreateTrip_Call struct {
	*mock.Call
}

// CreateTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *trip.TripCreateRequest
func (_e *MockTripService_Expecter) CreateTrip(ctx interface{}, userID interface{}, req interface{}) *MockTripService_CreateTrip_Call {
	return &MockTripService_CreateTrip_Call{Call: _e.mock.On("CreateTrip", ctx, userID, req)}
}

func (_c *MockTripService_CreateTrip_Call) Run(run func(ctx context.Context, userID string, req *trip.TripCreateRequest)) *MockTripService_CreateTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*trip.TripCreateRequest))
	})
	return _c
}

func (_c *MockTripService_CreateTrip_Call) Return(_a0 *trip.Trip, _a1 error) *MockTripService_CreateTrip_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_CreateTrip_Call) RunAndReturn(run func(context.Context, string, *trip.TripCreateRequest) (*trip.Trip, error)) *MockTripService_CreateTrip_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItineraryItem provides a mock function with given fields: ctx, tripID, itemID, userID
func (_m *MockTripService) DeleteItineraryItem(ctx context.Context, tripID string, itemID string, userID string) error {
	ret := _m.Called(ctx, tripID, itemID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItineraryItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, tripID, itemID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripService_DeleteItineraryItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItineraryItem'
type MockTripService_DeleteItineraryItem_Call struct {
	*mock.Call
}

// DeleteItineraryItem is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - itemID string
//   - userID string
func (_e *MockTripService_Expecter) DeleteItineraryItem(ctx interface{}, tripID interface{}, itemID interface{}, userID interface{}) *MockTripService_DeleteItineraryItem_Call {
	return &MockTripService_DeleteItineraryItem_Call{Call: _e.mock.On("DeleteItineraryItem", ctx, tripID, itemID, userID)}
}

func (_c *MockTripService_DeleteItineraryItem_Call) Run(run func(ctx context.Context, tripID string, itemID string, userID string)) *MockTripService_DeleteItineraryItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTripService_DeleteItineraryItem_Call) Return(_a0 error) *MockTripService_DeleteItineraryItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripService_DeleteItineraryItem_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockTripService_DeleteItineraryItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMealPlanDay provides a mock function with given fields: ctx, tripID, dayID, userID
func (_m *MockTripService) DeleteMealPlanDay(ctx context.Context, tripID string, dayID string, userID string) error {
	ret := _m.Called(ctx, tripID, dayID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMealPlanDay")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, tripID, dayID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripService_DeleteMealPlanDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMealPlanDay'
type MockTripService_DeleteMealPlanDay_Call struct {
	*mock.Call
}

// DeleteMealPlanDay is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - dayID string
//   - userID string
func (_e *MockTripService_Expecter) DeleteMealPlanDay(ctx interface{}, tripID interface{}, dayID interface{}, userID interface{}) *MockTripService_DeleteMealPlanDay_Call {
	return &MockTripService_DeleteMealPlanDay_Call{Call: _e.mock.On("DeleteMealPlanDay", ctx, tripID, dayID, userID)}
}

func (_c *MockTripService_DeleteMealPlanDay_Call) Run(run func(ctx context.Context, tripID string, dayID string, userID string)) *MockTripService_DeleteMealPlanDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTripService_DeleteMealPlanDay_Call) Return(_a0 error) *MockTripService_DeleteMealPlanDay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripService_DeleteMealPlanDay_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockTripService_DeleteMealPlanDay_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTrip provides a mock function with given fields: ctx, tripID, userID
func (_m *MockTripService) DeleteTrip(ctx context.Context, tripID string, userID string) error {
	ret := _m.Called(ctx, tripID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTrip")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tripID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripService_DeleteTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTrip'
type MockTripService_DeleteTrip_Call struct {
	*mock.Call
}

// DeleteTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
func (_e *MockTripService_Expecter) DeleteTrip(ctx interface{}, tripID interface{}, userID interface{}) *MockTripService_DeleteTrip_Call {
	return &MockTripService_DeleteTrip_Call{Call: _e.mock.On("DeleteTrip", ctx, tripID, userID)}
}

func (_c *MockTripService_DeleteTrip_Call) Run(run func(ctx context.Context, tripID string, userID string)) *MockTripService_DeleteTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripService_DeleteTrip_Call) Return(_a0 error) *MockTripService_DeleteTrip_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripService_DeleteTrip_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTripService_DeleteTrip_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrip provides a mock function with given fields: ctx, tripID, userID
func (_m *MockTripService) GetTrip(ctx context.Context, tripID string, userID string) (*trip.Trip, error) {
	ret := _m.Called(ctx, tripID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTrip")
	}

	var r0 *trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*trip.Trip, error)); ok {
		return rf(ctx, tripID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *trip.Trip); ok {
		r0 = rf(ctx, tripID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tripID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_GetTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrip'
type MockTripService_GetTrip_Call struct {
	*mock.Call
}

// GetTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
func (_e *MockTripService_Expecter) GetTrip(ctx interface{}, tripID interface{}, userID interface{}) *MockTripService_GetTrip_Call {
	return &MockTripService_GetTrip_Call{Call: _e.mock.On("GetTrip", ctx, tripID, userID)}
}

func (_c *MockTripService_GetTrip_Call) Run(run func(ctx context.Context, tripID string, userID string)) *MockTripService_GetTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripService_GetTrip_Call) Return(_a0 *trip.Trip, _a1 error) *MockTripService_GetTrip_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_GetTrip_Call) RunAndReturn(run func(context.Context, string, string) (*trip.Trip, error)) *MockTripService_GetTrip_Call {
	_c.Call.Return(run)
	return _c
}

// InviteMemberByEmail provides a mock function with given fields: ctx, tripID, userID, email
func (_m *MockTripService) InviteMemberByEmail(ctx context.Context, tripID string, userID string, email string) (*trip.TripMember, error) {
	ret := _m.Called(ctx, tripID, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for InviteMemberByEmail")
	}

	var r0 *trip.TripMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*trip.TripMember, error)); ok {
		return rf(ctx, tripID, userID, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *trip.TripMember); ok {
		r0 = rf(ctx, tripID, userID, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.TripMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, tripID, userID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_InviteMemberByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteMemberByEmail'
type MockTripService_InviteMemberByEmail_Call struct {
	*mock.Call
}

// InviteMemberByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
//   - email string
func (_e *MockTripService_Expecter) InviteMemberByEmail(ctx interface{}, tripID interface{}, userID interface{}, email interface{}) *MockTripService_InviteMemberByEmail_Call {
	return &MockTripService_InviteMemberByEmail_Call{Call: _e.mock.On("InviteMemberByEmail", ctx, tripID, userID, email)}
}

func (_c *MockTripService_InviteMemberByEmail_Call) Run(run func(ctx context.Context, tripID string, userID string, email string)) *MockTripService_InviteMemberByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTripService_InviteMemberByEmail_Call) Return(_a0 *trip.TripMember, _a1 error) *MockTripService_InviteMemberByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_InviteMemberByEmail_Call) RunAndReturn(run func(context.Context, string, string, string) (*trip.TripMember, error)) *MockTripService_InviteMemberByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ListItinerary provides a mock function with given fields: ctx, tripID, userID
func (_m *MockTripService) ListItinerary(ctx context.Context, tripID string, userID string) ([]*trip.ItineraryItem, error) {
	ret := _m.Called(ctx, tripID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListItinerary")
	}

	var r0 []*trip.ItineraryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*trip.ItineraryItem, error)); ok {
		return rf(ctx, tripID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*trip.ItineraryItem); ok {
		r0 = rf(ctx, tripID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trip.ItineraryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tripID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_ListItinerary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItinerary'
type MockTripService_ListItinerary_Call struct {
	*mock.Call
}

// ListItinerary is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
func (_e *MockTripService_Expecter) ListItinerary(ctx interface{}, tripID interface{}, userID interface{}) *MockTripService_ListItinerary_Call {
	return &MockTripService_ListItinerary_Call{Call: _e.mock.On("ListItinerary", ctx, tripID, userID)}
}

func (_c *MockTripService_ListItinerary_Call) Run(run func(ctx context.Context, tripID string, userID string)) *MockTripService_ListItinerary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripService_ListItinerary_Call) Return(_a0 []*trip.ItineraryItem, _a1 error) *MockTripService_ListItinerary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_ListItinerary_Call) RunAndReturn(run func(context.Context, string, string) ([]*trip.ItineraryItem, error)) *MockTripService_ListItinerary_Call {
	_c.Call.Return(run)
	return _c
}

// ListMealPlanDays provides a mock function with given fields: ctx, tripID, userID
func (_m *MockTripService) ListMealPlanDays(ctx context.Context, tripID string, userID string) ([]*trip.MealPlanDay, error) {
	ret := _m.Called(ctx, tripID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListMealPlanDays")
	}

	var r0 []*trip.MealPlanDay
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*trip.MealPlanDay, error)); ok {
		return rf(ctx, tripID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*trip.MealPlanDay); ok {
		r0 = rf(ctx, tripID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trip.MealPlanDay)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tripID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_ListMealPlanDays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMealPlanDays'
type MockTripService_ListMealPlanDays_Call struct {
	*mock.Call
}

// ListMealPlanDays is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
func (_e *MockTripService_Expecter) ListMealPlanDays(ctx interface{}, tripID interface{}, userID interface{}) *MockTripService_ListMealPlanDays_Call {
	return &MockTripService_ListMealPlanDays_Call{Call: _e.mock.On("ListMealPlanDays", ctx, tripID, userID)}
}

func (_c *MockTripService_ListMealPlanDays_Call) Run(run func(ctx context.Context, tripID string, userID string)) *MockTripService_ListMealPlanDays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripService_ListMealPlanDays_Call) Return(_a0 []*trip.MealPlanDay, _a1 error) *MockTripService_ListMealPlanDays_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_ListMealPlanDays_Call) RunAndReturn(run func(context.Context, string, string) ([]*trip.MealPlanDay, error)) *MockTripService_ListMealPlanDays_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function with given fields: ctx, tripID, userID
func (_m *MockTripService) ListMembers(ctx context.Context, tripID string, userID string) ([]*trip.TripMember, error) {
	ret := _m.Called(ctx, tripID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []*trip.TripMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*trip.TripMember, error)); ok {
		return rf(ctx, tripID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*trip.TripMember); ok {
		r0 = rf(ctx, tripID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trip.TripMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tripID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockTripService_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
func (_e *MockTripService_Expecter) ListMembers(ctx interface{}, tripID interface{}, userID interface{}) *MockTripService_ListMembers_Call {
	return &MockTripService_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, tripID, userID)}
}

func (_c *MockTripService_ListMembers_Call) Run(run func(ctx context.Context, tripID string, userID string)) *MockTripService_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripService_ListMembers_Call) Return(_a0 []*trip.TripMember, _a1 error) *MockTripService_ListMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_ListMembers_Call) RunAndReturn(run func(context.Context, string, string) ([]*trip.TripMember, error)) *MockTripService_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// ListTrips provides a mock function with given fields: ctx, userID, page, limit, search
func (_m *MockTripService) ListTrips(ctx context.Context, userID string, page int, limit int, search string) ([]*trip.Trip, int, bool, error) {
	ret := _m.Called(ctx, userID, page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for ListTrips")
	}

	var r0 []*trip.Trip
	var r1 int
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) ([]*trip.Trip, int, bool, error)); ok {
		return rf(ctx, userID, page, limit, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, string) []*trip.Trip); ok {
		r0 = rf(ctx, userID, page, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, string) int); ok {
		r1 = rf(ctx, userID, page, limit, search)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, string) bool); ok {
		r2 = rf(ctx, userID, page, limit, search)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, int, int, string) error); ok {
		r3 = rf(ctx, userID, page, limit, search)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockTripService_ListTrips_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTrips'
type MockTripService_ListTrips_Call struct {
	*mock.Call
}

// ListTrips is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int
//   - limit int
//   - search string
func (_e *MockTripService_Expecter) ListTrips(ctx interface{}, userID interface{}, page interface{}, limit interface{}, search interface{}) *MockTripService_ListTrips_Call {
	return &MockTripService_ListTrips_Call{Call: _e.mock.On("ListTrips", ctx, userID, page, limit, search)}
}

func (_c *MockTripService_ListTrips_Call) Run(run func(ctx context.Context, userID string, page int, limit int, search string)) *MockTripService_ListTrips_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *MockTripService_ListTrips_Call) Return(_a0 []*trip.Trip, _a1 int, _a2 bool, _a3 error) *MockTripService_ListTrips_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockTripService_ListTrips_Call) RunAndReturn(run func(context.Context, string, int, int, string) ([]*trip.Trip, int, bool, error)) *MockTripService_ListTrips_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, tripID, actionUserID, targetUserID
func (_m *MockTripService) RemoveMember(ctx context.Context, tripID string, actionUserID string, targetUserID string) error {
	ret := _m.Called(ctx, tripID, actionUserID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, tripID, actionUserID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripService_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockTripService_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - actionUserID string
//   - targetUserID string
func (_e *MockTripService_Expecter) RemoveMember(ctx interface{}, tripID interface{}, actionUserID interface{}, targetUserID interface{}) *MockTripService_RemoveMember_Call {
	return &MockTripService_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, tripID, actionUserID, targetUserID)}
}

func (_c *MockTripService_RemoveMember_Call) Run(run func(ctx context.Context, tripID string, actionUserID string, targetUserID string)) *MockTripService_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTripService_RemoveMember_Call) Return(_a0 error) *MockTripService_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripService_RemoveMember_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockTripService_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItineraryItem provides a mock function with given fields: ctx, tripID, itemID, userID, req
func (_m *MockTripService) UpdateItineraryItem(ctx context.Context, tripID string, itemID string, userID string, req *trip.ItineraryItemRequest) (*trip.ItineraryItem, error) {
	ret := _m.Called(ctx, tripID, itemID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItineraryItem")
	}

	var r0 *trip.ItineraryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *trip.ItineraryItemRequest) (*trip.ItineraryItem, error)); ok {
		return rf(ctx, tripID, itemID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *trip.ItineraryItemRequest) *trip.ItineraryItem); ok {
		r0 = rf(ctx, tripID, itemID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.ItineraryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *trip.ItineraryItemRequest) error); ok {
		r1 = rf(ctx, tripID, itemID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_UpdateItineraryItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItineraryItem'
type MockTripService_UpdateItineraryItem_Call struct {
	*mock.Call
}

// UpdateItineraryItem is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - itemID string
//   - userID string
//   - req *trip.ItineraryItemRequest
func (_e *MockTripService_Expecter) UpdateItineraryItem(ctx interface{}, tripID interface{}, itemID interface{}, userID interface{}, req interface{}) *MockTripService_UpdateItineraryItem_Call {
	return &MockTripService_UpdateItineraryItem_Call{Call: _e.mock.On("UpdateItineraryItem", ctx, tripID, itemID, userID, req)}
}

func (_c *MockTripService_UpdateItineraryItem_Call) Run(run func(ctx context.Context, tripID string, itemID string, userID string, req *trip.ItineraryItemRequest)) *MockTripService_UpdateItineraryItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*trip.ItineraryItemRequest))
	})
	return _c
}

func (_c *MockTripService_UpdateItineraryItem_Call) Return(_a0 *trip.ItineraryItem, _a1 error) *MockTripService_UpdateItineraryItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_UpdateItineraryItem_Call) RunAndReturn(run func(context.Context, string, string, string, *trip.ItineraryItemRequest) (*trip.ItineraryItem, error)) *MockTripService_UpdateItineraryItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMealPlanDay provides a mock function with given fields: ctx, tripID, dayID, userID, name, linkedDay
func (_m *MockTripService) UpdateMealPlanDay(ctx context.Context, tripID string, dayID string, userID string, name string, linkedDay *string) (*trip.MealPlanDay, error) {
	ret := _m.Called(ctx, tripID, dayID, userID, name, linkedDay)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMealPlanDay")
	}

	var r0 *trip.MealPlanDay
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *string) (*trip.MealPlanDay, error)); ok {
		return rf(ctx, tripID, dayID, userID, name, linkedDay)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *string) *trip.MealPlanDay); ok {
		r0 = rf(ctx, tripID, dayID, userID, name, linkedDay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.MealPlanDay)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *string) error); ok {
		r1 = rf(ctx, tripID, dayID, userID, name, linkedDay)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_UpdateMealPlanDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMealPlanDay'
type MockTripService_UpdateMealPlanDay_Call struct {
	*mock.Call
}

// UpdateMealPlanDay is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - dayID string
//   - userID string
//   - name string
//   - linkedDay *string
func (_e *MockTripService_Expecter) UpdateMealPlanDay(ctx interface{}, tripID interface{}, dayID interface{}, userID interface{}, name interface{}, linkedDay interface{}) *MockTripService_UpdateMealPlanDay_Call {
	return &MockTripService_UpdateMealPlanDay_Call{Call: _e.mock.On("UpdateMealPlanDay", ctx, tripID, dayID, userID, name, linkedDay)}
}

func (_c *MockTripService_UpdateMealPlanDay_Call) Run(run func(ctx context.Context, tripID string, dayID string, userID string, name string, linkedDay *string)) *MockTripService_UpdateMealPlanDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(*string))
	})
	return _c
}

func (_c *MockTripService_UpdateMealPlanDay_Call) Return(_a0 *trip.MealPlanDay, _a1 error) *MockTripService_UpdateMealPlanDay_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_UpdateMealPlanDay_Call) RunAndReturn(run func(context.Context, string, string, string, string, *string) (*trip.MealPlanDay, error)) *MockTripService_UpdateMealPlanDay_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTrip provides a mock function with given fields: ctx, tripID, userID, req
func (_m *MockTripService) UpdateTrip(ctx context.Context, tripID string, userID string, req *trip.TripUpdateRequest) (*trip.Trip, error) {
	ret := _m.Called(ctx, tripID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTrip")
	}

	var r0 *trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *trip.TripUpdateRequest) (*trip.Trip, error)); ok {
		return rf(ctx, tripID, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *trip.TripUpdateRequest) *trip.Trip); ok {
		r0 = rf(ctx, tripID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *trip.TripUpdateRequest) error); ok {
		r1 = rf(ctx, tripID, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_UpdateTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTrip'
type MockTripService_UpdateTrip_Call struct {
	*mock.Call
}

// UpdateTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - userID string
//   - req *trip.TripUpdateRequest
func (_e *MockTripService_Expecter) UpdateTrip(ctx interface{}, tripID interface{}, userID interface{}, req interface{}) *MockTripService_UpdateTrip_Call {
	return &MockTripService_UpdateTrip_Call{Call: _e.mock.On("UpdateTrip", ctx, tripID, userID, req)}
}

func (_c *MockTripService_UpdateTrip_Call) Run(run func(ctx context.Context, tripID string, userID string, req *trip.TripUpdateRequest)) *MockTripService_UpdateTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*trip.TripUpdateRequest))
	})
	return _c
}

func (_c *MockTripService_UpdateTrip_Call) Return(_a0 *trip.Trip, _a1 error) *MockTripService_UpdateTrip_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_UpdateTrip_Call) RunAndReturn(run func(context.Context, string, string, *trip.TripUpdateRequest) (*trip.Trip, error)) *MockTripService_UpdateTrip_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTripService creates a new instance of MockTripService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripService {
	mock := &MockTripService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
