// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	trip "summitmate/internal/trip"

	mock "github.com/stretchr/testify/mock"
)

// MockTripMealPlanDayRepository is an autogenerated mock type for the TripMealPlanDayRepository type
type MockTripMealPlanDayRepository struct {
	mock.Mock
}

type MockTripMealPlanDayRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripMealPlanDayRepository) EXPECT() *MockTripMealPlanDayRepository_Expecter {
	return &MockTripMealPlanDayRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *MockTripMealPlanDayRepository) Create(ctx context.Context, item *trip.MealPlanDay) (*trip.MealPlanDay, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *trip.MealPlanDay
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.MealPlanDay) (*trip.MealPlanDay, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *trip.MealPlanDay) *trip.MealPlanDay); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.MealPlanDay)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *trip.MealPlanDay) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripMealPlanDayRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTripMealPlanDayRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *trip.MealPlanDay
func (_e *MockTripMealPlanDayRepository_Expecter) Create(ctx interface{}, item interface{}) *MockTripMealPlanDayRepository_Create_Call {
	return &MockTripMealPlanDayRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *MockTripMealPlanDayRepository_Create_Call) Run(run func(ctx context.Context, item *trip.MealPlanDay)) *MockTripMealPlanDayRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*trip.MealPlanDay))
	})
	return _c
}

func (_c *MockTripMealPlanDayRepository_Create_Call) Return(_a0 *trip.MealPlanDay, _a1 error) *MockTripMealPlanDayRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripMealPlanDayRepository_Create_Call) RunAndReturn(run func(context.Context, *trip.MealPlanDay) (*trip.MealPlanDay, error)) *MockTripMealPlanDayRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, tripID
func (_m *MockTripMealPlanDayRepository) Delete(ctx context.Context, id string, tripID string) error {
	ret := _m.Called(ctx, id, tripID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, tripID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripMealPlanDayRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTripMealPlanDayRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - tripID string
func (_e *MockTripMealPlanDayRepository_Expecter) Delete(ctx interface{}, id interface{}, tripID interface{}) *MockTripMealPlanDayRepository_Delete_Call {
	return &MockTripMealPlanDayRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id, tripID)}
}

func (_c *MockTripMealPlanDayRepository_Delete_Call) Run(run func(ctx context.Context, id string, tripID string)) *MockTripMealPlanDayRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripMealPlanDayRepository_Delete_Call) Return(_a0 error) *MockTripMealPlanDayRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripMealPlanDayRepository_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTripMealPlanDayRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id, tripID
func (_m *MockTripMealPlanDayRepository) GetByID(ctx context.Context, id string, tripID string) (*trip.MealPlanDay, error) {
	ret := _m.Called(ctx, id, tripID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *trip.MealPlanDay
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*trip.MealPlanDay, error)); ok {
		return rf(ctx, id, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *trip.MealPlanDay); ok {
		r0 = rf(ctx, id, tripID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.MealPlanDay)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripMealPlanDayRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTripMealPlanDayRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - tripID string
func (_e *MockTripMealPlanDayRepository_Expecter) GetByID(ctx interface{}, id interface{}, tripID interface{}) *MockTripMealPlanDayRepository_GetByID_Call {
	return &MockTripMealPlanDayRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, tripID)}
}

func (_c *MockTripMealPlanDayRepository_GetByID_Call) Run(run func(ctx context.Context, id string, tripID string)) *MockTripMealPlanDayRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripMealPlanDayRepository_GetByID_Call) Return(_a0 *trip.MealPlanDay, _a1 error) *MockTripMealPlanDayRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripMealPlanDayRepository_GetByID_Call) RunAndReturn(run func(context.Context, string, string) (*trip.MealPlanDay, error)) *MockTripMealPlanDayRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTripID provides a mock function with given fields: ctx, tripID
func (_m *MockTripMealPlanDayRepository) ListByTripID(ctx context.Context, tripID string) ([]*trip.MealPlanDay, error) {
	ret := _m.Called(ctx, tripID)

	if len(ret) == 0 {
		panic("no return value specified for ListByTripID")
	}

	var r0 []*trip.MealPlanDay
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*trip.MealPlanDay, error)); ok {
		return rf(ctx, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*trip.MealPlanDay); ok {
		r0 = rf(ctx, tripID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trip.MealPlanDay)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripMealPlanDayRepository_ListByTripID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTripID'
type MockTripMealPlanDayRepository_ListByTripID_Call struct {
	*mock.Call
}

// ListByTripID is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
func (_e *MockTripMealPlanDayRepository_Expecter) ListByTripID(ctx interface{}, tripID interface{}) *MockTripMealPlanDayRepository_ListByTripID_Call {
	return &MockTripMealPlanDayRepository_ListByTripID_Call{Call: _e.mock.On("ListByTripID", ctx, tripID)}
}

func (_c *MockTripMealPlanDayRepository_ListByTripID_Call) Run(run func(ctx context.Context, tripID string)) *MockTripMealPlanDayRepository_ListByTripID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripMealPlanDayRepository_ListByTripID_Call) Return(_a0 []*trip.MealPlanDay, _a1 error) *MockTripMealPlanDayRepository_ListByTripID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripMealPlanDayRepository_ListByTripID_Call) RunAndReturn(run func(context.Context, string) ([]*trip.MealPlanDay, error)) *MockTripMealPlanDayRepository_ListByTripID_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceAll provides a mock function with given fields: ctx, tripID, days
func (_m *MockTripMealPlanDayRepository) ReplaceAll(ctx context.Context, tripID string, days []*trip.MealPlanDay) error {
	ret := _m.Called(ctx, tripID, days)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*trip.MealPlanDay) error); ok {
		r0 = rf(ctx, tripID, days)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripMealPlanDayRepository_ReplaceAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceAll'
type MockTripMealPlanDayRepository_ReplaceAll_Call struct {
	*mock.Call
}

// ReplaceAll is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - days []*trip.MealPlanDay
func (_e *MockTripMealPlanDayRepository_Expecter) ReplaceAll(ctx interface{}, tripID interface{}, days interface{}) *MockTripMealPlanDayRepository_ReplaceAll_Call {
	return &MockTripMealPlanDayRepository_ReplaceAll_Call{Call: _e.mock.On("ReplaceAll", ctx, tripID, days)}
}

func (_c *MockTripMealPlanDayRepository_ReplaceAll_Call) Run(run func(ctx context.Context, tripID string, days []*trip.MealPlanDay)) *MockTripMealPlanDayRepository_ReplaceAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]*trip.MealPlanDay))
	})
	return _c
}

func (_c *MockTripMealPlanDayRepository_ReplaceAll_Call) Return(_a0 error) *MockTripMealPlanDayRepository_ReplaceAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripMealPlanDayRepository_ReplaceAll_Call) RunAndReturn(run func(context.Context, string, []*trip.MealPlanDay) error) *MockTripMealPlanDayRepository_ReplaceAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, item
func (_m *MockTripMealPlanDayRepository) Update(ctx context.Context, item *trip.MealPlanDay) (*trip.MealPlanDay, error) {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *trip.MealPlanDay
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.MealPlanDay) (*trip.MealPlanDay, error)); ok {
		return rf(ctx, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *trip.MealPlanDay) *trip.MealPlanDay); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.MealPlanDay)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *trip.MealPlanDay) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripMealPlanDayRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTripMealPlanDayRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - item *trip.MealPlanDay
func (_e *MockTripMealPlanDayRepository_Expecter) Update(ctx interface{}, item interface{}) *MockTripMealPlanDayRepository_Update_Call {
	return &MockTripMealPlanDayRepository_Update_Call{Call: _e.mock.On("Update", ctx, item)}
}

func (_c *MockTripMealPlanDayRepository_Update_Call) Run(run func(ctx context.Context, item *trip.MealPlanDay)) *MockTripMealPlanDayRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*trip.MealPlanDay))
	})
	return _c
}

func (_c *MockTripMealPlanDayRepository_Update_Call) Return(_a0 *trip.MealPlanDay, _a1 error) *MockTripMealPlanDayRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripMealPlanDayRepository_Update_Call) RunAndReturn(run func(context.Context, *trip.MealPlanDay) (*trip.MealPlanDay, error)) *MockTripMealPlanDayRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTripMealPlanDayRepository creates a new instance of MockTripMealPlanDayRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripMealPlanDayRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripMealPlanDayRepository {
	mock := &MockTripMealPlanDayRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
