// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	groupevent "summitmate/internal/groupevent"

	mock "github.com/stretchr/testify/mock"
)

// MockGroupEventService is an autogenerated mock type for the GroupEventService type
type MockGroupEventService struct {
	mock.Mock
}

type MockGroupEventService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupEventService) EXPECT() *MockGroupEventService_Expecter {
	return &MockGroupEventService_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function with given fields: ctx, comment
func (_m *MockGroupEventService) AddComment(ctx context.Context, comment *groupevent.GroupEventComment) error {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *groupevent.GroupEventComment) error); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupEventService_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockGroupEventService_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - ctx context.Context
//   - comment *groupevent.GroupEventComment
func (_e *MockGroupEventService_Expecter) AddComment(ctx interface{}, comment interface{}) *MockGroupEventService_AddComment_Call {
	return &MockGroupEventService_AddComment_Call{Call: _e.mock.On("AddComment", ctx, comment)}
}

func (_c *MockGroupEventService_AddComment_Call) Run(run func(ctx context.Context, comment *groupevent.GroupEventComment)) *MockGroupEventService_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*groupevent.GroupEventComment))
	})
	return _c
}

func (_c *MockGroupEventService_AddComment_Call) Return(_a0 error) *MockGroupEventService_AddComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupEventService_AddComment_Call) RunAndReturn(run func(context.Context, *groupevent.GroupEventComment) error) *MockGroupEventService_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyToEvent provides a mock function with given fields: ctx, app
func (_m *MockGroupEventService) ApplyToEvent(ctx context.Context, app *groupevent.GroupEventApplication) error {
	ret := _m.Called(ctx, app)

	if len(ret) == 0 {
		panic("no return value specified for ApplyToEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *groupevent.GroupEventApplication) error); ok {
		r0 = rf(ctx, app)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupEventService_ApplyToEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyToEvent'
type MockGroupEventService_ApplyToEvent_Call struct {
	*mock.Call
}

// ApplyToEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - app *groupevent.GroupEventApplication
func (_e *MockGroupEventService_Expecter) ApplyToEvent(ctx interface{}, app interface{}) *MockGroupEventService_ApplyToEvent_Call {
	return &MockGroupEventService_ApplyToEvent_Call{Call: _e.mock.On("ApplyToEvent", ctx, app)}
}

func (_c *MockGroupEventService_ApplyToEvent_Call) Run(run func(ctx context.Context, app *groupevent.GroupEventApplication)) *MockGroupEventService_ApplyToEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*groupevent.GroupEventApplication))
	})
	return _c
}

func (_c *MockGroupEventService_ApplyToEvent_Call) Return(_a0 error) *MockGroupEventService_ApplyToEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupEventService_ApplyToEvent_Call) RunAndReturn(run func(context.Context, *groupevent.GroupEventApplication) error) *MockGroupEventService_ApplyToEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CancelApplication provides a mock function with given fields: ctx, appID, userID
func (_m *MockGroupEventService) CancelApplication(ctx context.Context, appID string, userID string) error {
	ret := _m.Called(ctx, appID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelApplication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, appID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupEventService_CancelApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelApplication'
type MockGroupEventService_CancelApplication_Call struct {
	*mock.Call
}

// CancelApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - userID string
func (_e *MockGroupEventService_Expecter) CancelApplication(ctx interface{}, appID interface{}, userID interface{}) *MockGroupEventService_CancelApplication_Call {
	return &MockGroupEventService_CancelApplication_Call{Call: _e.mock.On("CancelApplication", ctx, appID, userID)}
}

func (_c *MockGroupEventService_CancelApplication_Call) Run(run func(ctx context.Context, appID string, userID string)) *MockGroupEventService_CancelApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGroupEventService_CancelApplication_Call) Return(_a0 error) *MockGroupEventService_CancelApplication_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupEventService_CancelApplication_Call) RunAndReturn(run func(context.Context, string, string) error) *MockGroupEventService_CancelApplication_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvent provides a mock function with given fields: ctx, event
func (_m *MockGroupEventService) CreateEvent(ctx context.Context, event *groupevent.GroupEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *groupevent.GroupEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupEventService_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockGroupEventService_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *groupevent.GroupEvent
func (_e *MockGroupEventService_Expecter) CreateEvent(ctx interface{}, event interface{}) *MockGroupEventService_CreateEvent_Call {
	return &MockGroupEventService_CreateEvent_Call{Call: _e.mock.On("CreateEvent", ctx, event)}
}

func (_c *MockGroupEventService_CreateEvent_Call) Run(run func(ctx context.Context, event *groupevent.GroupEvent)) *MockGroupEventService_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*groupevent.GroupEvent))
	})
	return _c
}

func (_c *MockGroupEventService_CreateEvent_Call) Return(_a0 error) *MockGroupEventService_CreateEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupEventService_CreateEvent_Call) RunAndReturn(run func(context.Context, *groupevent.GroupEvent) error) *MockGroupEventService_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function with given fields: ctx, commentID, userID
func (_m *MockGroupEventService) DeleteComment(ctx context.Context, commentID string, userID string) error {
	ret := _m.Called(ctx, commentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, commentID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupEventService_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockGroupEventService_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID string
//   - userID string
func (_e *MockGroupEventService_Expecter) DeleteComment(ctx interface{}, commentID interface{}, userID interface{}) *MockGroupEventService_DeleteComment_Call {
	return &MockGroupEventService_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, commentID, userID)}
}

func (_c *MockGroupEventService_DeleteComment_Call) Run(run func(ctx context.Context, commentID string, userID string)) *MockGroupEventService_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGroupEventService_DeleteComment_Call) Return(_a0 error) *MockGroupEventService_DeleteComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupEventService_DeleteComment_Call) RunAndReturn(run func(context.Context, string, string) error) *MockGroupEventService_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvent provides a mock function with given fields: ctx, id, userID
func (_m *MockGroupEventService) DeleteEvent(ctx context.Context, id string, userID string) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupEventService_DeleteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvent'
type MockGroupEventService_DeleteEvent_Call struct {
	*mock.Call
}

// DeleteEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockGroupEventService_Expecter) DeleteEvent(ctx interface{}, id interface{}, userID interface{}) *MockGroupEventService_DeleteEvent_Call {
	return &MockGroupEventService_DeleteEvent_Call{Call: _e.mock.On("DeleteEvent", ctx, id, userID)}
}

func (_c *MockGroupEventService_DeleteEvent_Call) Run(run func(ctx context.Context, id string, userID string)) *MockGroupEventService_DeleteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGroupEventService_DeleteEvent_Call) Return(_a0 error) *MockGroupEventService_DeleteEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupEventService_DeleteEvent_Call) RunAndReturn(run func(context.Context, string, string) error) *MockGroupEventService_DeleteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplication provides a mock function with given fields: ctx, id
func (_m *MockGroupEventService) GetApplication(ctx context.Context, id string) (*groupevent.GroupEventApplication, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetApplication")
	}

	var r0 *groupevent.GroupEventApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*groupevent.GroupEventApplication, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *groupevent.GroupEventApplication); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupevent.GroupEventApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupEventService_GetApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplication'
type MockGroupEventService_GetApplication_Call struct {
	*mock.Call
}

// GetApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockGroupEventService_Expecter) GetApplication(ctx interface{}, id interface{}) *MockGroupEventService_GetApplication_Call {
	return &MockGroupEventService_GetApplication_Call{Call: _e.mock.On("GetApplication", ctx, id)}
}

func (_c *MockGroupEventService_GetApplication_Call) Run(run func(ctx context.Context, id string)) *MockGroupEventService_GetApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGroupEventService_GetApplication_Call) Return(_a0 *groupevent.GroupEventApplication, _a1 error) *MockGroupEventService_GetApplication_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupEventService_GetApplication_Call) RunAndReturn(run func(context.Context, string) (*groupevent.GroupEventApplication, error)) *MockGroupEventService_GetApplication_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvent provides a mock function with given fields: ctx, id, userID
func (_m *MockGroupEventService) GetEvent(ctx context.Context, id string, userID string) (*groupevent.GroupEvent, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 *groupevent.GroupEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*groupevent.GroupEvent, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *groupevent.GroupEvent); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupevent.GroupEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupEventService_GetEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvent'
type MockGroupEventService_GetEvent_Call struct {
	*mock.Call
}

// GetEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockGroupEventService_Expecter) GetEvent(ctx interface{}, id interface{}, userID interface{}) *MockGroupEventService_GetEvent_Call {
	return &MockGroupEventService_GetEvent_Call{Call: _e.mock.On("GetEvent", ctx, id, userID)}
}

func (_c *MockGroupEventService_GetEvent_Call) Run(run func(ctx context.Context, id string, userID string)) *MockGroupEventService_GetEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGroupEventService_GetEvent_Call) Return(_a0 *groupevent.GroupEvent, _a1 error) *MockGroupEventService_GetEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupEventService_GetEvent_Call) RunAndReturn(run func(context.Context, string, string) (*groupevent.GroupEvent, error)) *MockGroupEventService_GetEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ListApplications provides a mock function with given fields: ctx, id, userID
func (_m *MockGroupEventService) ListApplications(ctx context.Context, id string, userID string) ([]*groupevent.GroupEventApplication, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListApplications")
	}

	var r0 []*groupevent.GroupEventApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*groupevent.GroupEventApplication, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*groupevent.GroupEventApplication); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*groupevent.GroupEventApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupEventService_ListApplications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApplications'
type MockGroupEventService_ListApplications_Call struct {
	*mock.Call
}

// ListApplications is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockGroupEventService_Expecter) ListApplications(ctx interface{}, id interface{}, userID interface{}) *MockGroupEventService_ListApplications_Call {
	return &MockGroupEventService_ListApplications_Call{Call: _e.mock.On("ListApplications", ctx, id, userID)}
}

func (_c *MockGroupEventService_ListApplications_Call) Run(run func(ctx context.Context, id string, userID string)) *MockGroupEventService_ListApplications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGroupEventService_ListApplications_Call) Return(_a0 []*groupevent.GroupEventApplication, _a1 error) *MockGroupEventService_ListApplications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupEventService_ListApplications_Call) RunAndReturn(run func(context.Context, string, string) ([]*groupevent.GroupEventApplication, error)) *MockGroupEventService_ListApplications_Call {
	_c.Call.Return(run)
	return _c
}

// ListComments provides a mock function with given fields: ctx, eventID
func (_m *MockGroupEventService) ListComments(ctx context.Context, eventID string) ([]*groupevent.GroupEventComment, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ListComments")
	}

	var r0 []*groupevent.GroupEventComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*groupevent.GroupEventComment, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*groupevent.GroupEventComment); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*groupevent.GroupEventComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupEventService_ListComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComments'
type MockGroupEventService_ListComments_Call struct {
	*mock.Call
}

// ListComments is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *MockGroupEventService_Expecter) ListComments(ctx interface{}, eventID interface{}) *MockGroupEventService_ListComments_Call {
	return &MockGroupEventService_ListComments_Call{Call: _e.mock.On("ListComments", ctx, eventID)}
}

func (_c *MockGroupEventService_ListComments_Call) Run(run func(ctx context.Context, eventID string)) *MockGroupEventService_ListComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGroupEventService_ListComments_Call) Return(_a0 []*groupevent.GroupEventComment, _a1 error) *MockGroupEventService_ListComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupEventService_ListComments_Call) RunAndReturn(run func(context.Context, string) ([]*groupevent.GroupEventComment, error)) *MockGroupEventService_ListComments_Call {
	_c.Call.Return(run)
	return _c
}

// ListEvents provides a mock function with given fields: ctx, status, category, creatorID, page, limit, search, userID
func (_m *MockGroupEventService) ListEvents(ctx context.Context, status *string, category *groupevent.Category, creatorID *string, page int, limit int, search string, userID string) ([]*groupevent.GroupEvent, int, bool, error) {
	ret := _m.Called(ctx, status, category, creatorID, page, limit, search, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListEvents")
	}

	var r0 []*groupevent.GroupEvent
	var r1 int
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, *groupevent.Category, *string, int, int, string, string) ([]*groupevent.GroupEvent, int, bool, error)); ok {
		return rf(ctx, status, category, creatorID, page, limit, search, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string, *groupevent.Category, *string, int, int, string, string) []*groupevent.GroupEvent); ok {
		r0 = rf(ctx, status, category, creatorID, page, limit, search, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*groupevent.GroupEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string, *groupevent.Category, *string, int, int, string, string) int); ok {
		r1 = rf(ctx, status, category, creatorID, page, limit, search, userID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *string, *groupevent.Category, *string, int, int, string, string) bool); ok {
		r2 = rf(ctx, status, category, creatorID, page, limit, search, userID)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, *string, *groupevent.Category, *string, int, int, string, string) error); ok {
		r3 = rf(ctx, status, category, creatorID, page, limit, search, userID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockGroupEventService_ListEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEvents'
type MockGroupEventService_ListEvents_Call struct {
	*mock.Call
}

// ListEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - status *string
//   - category *groupevent.Category
//   - creatorID *string
//   - page int
//   - limit int
//   - search string
//   - userID string
func (_e *MockGroupEventService_Expecter) ListEvents(ctx interface{}, status interface{}, category interface{}, creatorID interface{}, page interface{}, limit interface{}, search interface{}, userID interface{}) *MockGroupEventService_ListEvents_Call {
	return &MockGroupEventService_ListEvents_Call{Call: _e.mock.On("ListEvents", ctx, status, category, creatorID, page, limit, search, userID)}
}

func (_c *MockGroupEventService_ListEvents_Call) Run(run func(ctx context.Context, status *string, category *groupevent.Category, creatorID *string, page int, limit int, search string, userID string)) *MockGroupEventService_ListEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string), args[2].(*groupevent.Category), args[3].(*string), args[4].(int), args[5].(int), args[6].(string), args[7].(string))
	})
	return _c
}

func (_c *MockGroupEventService_ListEvents_Call) Return(_a0 []*groupevent.GroupEvent, _a1 int, _a2 bool, _a3 error) *MockGroupEventService_ListEvents_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockGroupEventService_ListEvents_Call) RunAndReturn(run func(context.Context, *string, *groupevent.Category, *string, int, int, string, string) ([]*groupevent.GroupEvent, int, bool, error)) *MockGroupEventService_ListEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListMyEvents provides a mock function with given fields: ctx, userID, listType, page, limit
func (_m *MockGroupEventService) ListMyEvents(ctx context.Context, userID string, listType string, page int, limit int) ([]*groupevent.GroupEvent, int, bool, error) {
	ret := _m.Called(ctx, userID, listType, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListMyEvents")
	}

	var r0 []*groupevent.GroupEvent
	var r1 int
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]*groupevent.GroupEvent, int, bool, error)); ok {
		return rf(ctx, userID, listType, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*groupevent.GroupEvent); ok {
		r0 = rf(ctx, userID, listType, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*groupevent.GroupEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) int); ok {
		r1 = rf(ctx, userID, listType, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, int) bool); ok {
		r2 = rf(ctx, userID, listType, page, limit)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string, int, int) error); ok {
		r3 = rf(ctx, userID, listType, page, limit)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockGroupEventService_ListMyEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMyEvents'
type MockGroupEventService_ListMyEvents_Call struct {
	*mock.Call
}

// ListMyEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - listType string
//   - page int
//   - limit int
func (_e *MockGroupEventService_Expecter) ListMyEvents(ctx interface{}, userID interface{}, listType interface{}, page interface{}, limit interface{}) *MockGroupEventService_ListMyEvents_Call {
	return &MockGroupEventService_ListMyEvents_Call{Call: _e.mock.On("ListMyEvents", ctx, userID, listType, page, limit)}
}

func (_c *MockGroupEventService_ListMyEvents_Call) Run(run func(ctx context.Context, userID string, listType string, page int, limit int)) *MockGroupEventService_ListMyEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockGroupEventService_ListMyEvents_Call) Return(_a0 []*groupevent.GroupEvent, _a1 int, _a2 bool, _a3 error) *MockGroupEventService_ListMyEvents_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockGroupEventService_ListMyEvents_Call) RunAndReturn(run func(context.Context, string, string, int, int) ([]*groupevent.GroupEvent, int, bool, error)) *MockGroupEventService_ListMyEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessApplication provides a mock function with given fields: ctx, appID, status, rejectionReason, executorID
func (_m *MockGroupEventService) ProcessApplication(ctx context.Context, appID string, status string, rejectionReason string, executorID string) error {
	ret := _m.Called(ctx, appID, status, rejectionReason, executorID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessApplication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, appID, status, rejectionReason, executorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupEventService_ProcessApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessApplication'
type MockGroupEventService_ProcessApplication_Call struct {
	*mock.Call
}

// ProcessApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - status string
//   - rejectionReason string
//   - executorID string
func (_e *MockGroupEventService_Expecter) ProcessApplication(ctx interface{}, appID interface{}, status interface{}, rejectionReason interface{}, executorID interface{}) *MockGroupEventService_ProcessApplication_Call {
	return &MockGroupEventService_ProcessApplication_Call{Call: _e.mock.On("ProcessApplication", ctx, appID, status, rejectionReason, executorID)}
}

func (_c *MockGroupEventService_ProcessApplication_Call) Run(run func(ctx context.Context, appID string, status string, rejectionReason string, executorID string)) *MockGroupEventService_ProcessApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockGroupEventService_ProcessApplication_Call) Return(_a0 error) *MockGroupEventService_ProcessApplication_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupEventService_ProcessApplication_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MockGroupEventService_ProcessApplication_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleLike provides a mock function with given fields: ctx, eventID, userID
func (_m *MockGroupEventService) ToggleLike(ctx context.Context, eventID string, userID string) (bool, error) {
	ret := _m.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ToggleLike")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, eventID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, eventID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, eventID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupEventService_ToggleLike_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleLike'
type MockGroupEventService_ToggleLike_Call struct {
	*mock.Call
}

// ToggleLike is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - userID string
func (_e *MockGroupEventService_Expecter) ToggleLike(ctx interface{}, eventID interface{}, userID interface{}) *MockGroupEventService_ToggleLike_Call {
	return &MockGroupEventService_ToggleLike_Call{Call: _e.mock.On("ToggleLike", ctx, eventID, userID)}
}

func (_c *MockGroupEventService_ToggleLike_Call) Run(run func(ctx context.Context, eventID string, userID string)) *MockGroupEventService_ToggleLike_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGroupEventService_ToggleLike_Call) Return(_a0 bool, _a1 error) *MockGroupEventService_ToggleLike_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupEventService_ToggleLike_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockGroupEventService_ToggleLike_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvent provides a mock function with given fields: ctx, event, userID
func (_m *MockGroupEventService) UpdateEvent(ctx context.Context, event *groupevent.GroupEvent, userID string) (*groupevent.GroupEvent, error) {
	ret := _m.Called(ctx, event, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 *groupevent.GroupEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *groupevent.GroupEvent, string) (*groupevent.GroupEvent, error)); ok {
		return rf(ctx, event, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *groupevent.GroupEvent, string) *groupevent.GroupEvent); ok {
		r0 = rf(ctx, event, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*groupevent.GroupEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *groupevent.GroupEvent, string) error); ok {
		r1 = rf(ctx, event, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupEventService_UpdateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvent'
type MockGroupEventService_UpdateEvent_Call struct {
	*mock.Call
}

// UpdateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *groupevent.GroupEvent
//   - userID string
func (_e *MockGroupEventService_Expecter) UpdateEvent(ctx interface{}, event interface{}, userID interface{}) *MockGroupEventService_UpdateEvent_Call {
	return &MockGroupEventService_UpdateEvent_Call{Call: _e.mock.On("UpdateEvent", ctx, event, userID)}
}

func (_c *MockGroupEventService_UpdateEvent_Call) Run(run func(ctx context.Context, event *groupevent.GroupEvent, userID string)) *MockGroupEventService_UpdateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*groupevent.GroupEvent), args[2].(string))
	})
	return _c
}

func (_c *MockGroupEventService_UpdateEvent_Call) Return(_a0 *groupevent.GroupEvent, _a1 error) *MockGroupEventService_UpdateEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupEventService_UpdateEvent_Call) RunAndReturn(run func(context.Context, *groupevent.GroupEvent, string) (*groupevent.GroupEvent, error)) *MockGroupEventService_UpdateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTripLink provides a mock function with given fields: ctx, eventID, tripID, userID
func (_m *MockGroupEventService) UpdateTripLink(ctx context.Context, eventID string, tripID *string, userID string) error {
	ret := _m.Called(ctx, eventID, tripID, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTripLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, string) error); ok {
		r0 = rf(ctx, eventID, tripID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupEventService_UpdateTripLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTripLink'
type MockGroupEventService_UpdateTripLink_Call struct {
	*mock.Call
}

// UpdateTripLink is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - tripID *string
//   - userID string
func (_e *MockGroupEventService_Expecter) UpdateTripLink(ctx interface{}, eventID interface{}, tripID interface{}, userID interface{}) *MockGroupEventService_UpdateTripLink_Call {
	return &MockGroupEventService_UpdateTripLink_Call{Call: _e.mock.On("UpdateTripLink", ctx, eventID, tripID, userID)}
}

func (_c *MockGroupEventService_UpdateTripLink_Call) Run(run func(ctx context.Context, eventID string, tripID *string, userID string)) *MockGroupEventService_UpdateTripLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(string))
	})
	return _c
}

func (_c *MockGroupEventService_UpdateTripLink_Call) Return(_a0 error) *MockGroupEventService_UpdateTripLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupEventService_UpdateTripLink_Call) RunAndReturn(run func(context.Context, string, *string, string) error) *MockGroupEventService_UpdateTripLink_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTripSnapshot provides a mock function with given fields: ctx, eventID, userID
func (_m *MockGroupEventService) UpdateTripSnapshot(ctx context.Context, eventID string, userID string) error {
	ret := _m.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTripSnapshot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, eventID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupEventService_UpdateTripSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTripSnapshot'
type MockGroupEventService_UpdateTripSnapshot_Call struct {
	*mock.Call
}

// UpdateTripSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - userID string
func (_e *MockGroupEventService_Expecter) UpdateTripSnapshot(ctx interface{}, eventID interface{}, userID interface{}) *MockGroupEventService_UpdateTripSnapshot_Call {
	return &MockGroupEventService_UpdateTripSnapshot_Call{Call: _e.mock.On("UpdateTripSnapshot", ctx, eventID, userID)}
}

func (_c *MockGroupEventService_UpdateTripSnapshot_Call) Run(run func(ctx context.Context, eventID string, userID string)) *MockGroupEventService_UpdateTripSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGroupEventService_UpdateTripSnapshot_Call) Return(_a0 error) *MockGroupEventService_UpdateTripSnapshot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupEventService_UpdateTripSnapshot_Call) RunAndReturn(run func(context.Context, string, string) error) *MockGroupEventService_UpdateTripSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupEventService creates a new instance of MockGroupEventService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupEventService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupEventService {
	mock := &MockGroupEventService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
