// Code generated by mockery v2.53.6. DO NOT EDIT.

package favorite

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFavoriteRepository is an autogenerated mock type for the FavoriteRepository type
type MockFavoriteRepository struct {
	mock.Mock
}

type MockFavoriteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFavoriteRepository) EXPECT() *MockFavoriteRepository_Expecter {
	return &MockFavoriteRepository_Expecter{mock: &_m.Mock}
}

// BatchUpdate provides a mock function with given fields: ctx, userID, items
func (_m *MockFavoriteRepository) BatchUpdate(ctx context.Context, userID string, items []BatchFavoriteItem) error {
	ret := _m.Called(ctx, userID, items)

	if len(ret) == 0 {
		panic("no return value specified for BatchUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []BatchFavoriteItem) error); ok {
		r0 = rf(ctx, userID, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFavoriteRepository_BatchUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchUpdate'
type MockFavoriteRepository_BatchUpdate_Call struct {
	*mock.Call
}

// BatchUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - items []BatchFavoriteItem
func (_e *MockFavoriteRepository_Expecter) BatchUpdate(ctx interface{}, userID interface{}, items interface{}) *MockFavoriteRepository_BatchUpdate_Call {
	return &MockFavoriteRepository_BatchUpdate_Call{Call: _e.mock.On("BatchUpdate", ctx, userID, items)}
}

func (_c *MockFavoriteRepository_BatchUpdate_Call) Run(run func(ctx context.Context, userID string, items []BatchFavoriteItem)) *MockFavoriteRepository_BatchUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]BatchFavoriteItem))
	})
	return _c
}

func (_c *MockFavoriteRepository_BatchUpdate_Call) Return(_a0 error) *MockFavoriteRepository_BatchUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFavoriteRepository_BatchUpdate_Call) RunAndReturn(run func(context.Context, string, []BatchFavoriteItem) error) *MockFavoriteRepository_BatchUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, fav
func (_m *MockFavoriteRepository) Create(ctx context.Context, fav *Favorite) error {
	ret := _m.Called(ctx, fav)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Favorite) error); ok {
		r0 = rf(ctx, fav)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFavoriteRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFavoriteRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - fav *Favorite
func (_e *MockFavoriteRepository_Expecter) Create(ctx interface{}, fav interface{}) *MockFavoriteRepository_Create_Call {
	return &MockFavoriteRepository_Create_Call{Call: _e.mock.On("Create", ctx, fav)}
}

func (_c *MockFavoriteRepository_Create_Call) Run(run func(ctx context.Context, fav *Favorite)) *MockFavoriteRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Favorite))
	})
	return _c
}

func (_c *MockFavoriteRepository_Create_Call) Return(_a0 error) *MockFavoriteRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFavoriteRepository_Create_Call) RunAndReturn(run func(context.Context, *Favorite) error) *MockFavoriteRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByTargetAndUser provides a mock function with given fields: ctx, targetID, userID, favType
func (_m *MockFavoriteRepository) DeleteByTargetAndUser(ctx context.Context, targetID string, userID string, favType string) error {
	ret := _m.Called(ctx, targetID, userID, favType)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTargetAndUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, targetID, userID, favType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFavoriteRepository_DeleteByTargetAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByTargetAndUser'
type MockFavoriteRepository_DeleteByTargetAndUser_Call struct {
	*mock.Call
}

// DeleteByTargetAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - targetID string
//   - userID string
//   - favType string
func (_e *MockFavoriteRepository_Expecter) DeleteByTargetAndUser(ctx interface{}, targetID interface{}, userID interface{}, favType interface{}) *MockFavoriteRepository_DeleteByTargetAndUser_Call {
	return &MockFavoriteRepository_DeleteByTargetAndUser_Call{Call: _e.mock.On("DeleteByTargetAndUser", ctx, targetID, userID, favType)}
}

func (_c *MockFavoriteRepository_DeleteByTargetAndUser_Call) Run(run func(ctx context.Context, targetID string, userID string, favType string)) *MockFavoriteRepository_DeleteByTargetAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockFavoriteRepository_DeleteByTargetAndUser_Call) Return(_a0 error) *MockFavoriteRepository_DeleteByTargetAndUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFavoriteRepository_DeleteByTargetAndUser_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockFavoriteRepository_DeleteByTargetAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID, page, limit
func (_m *MockFavoriteRepository) ListByUserID(ctx context.Context, userID string, page int, limit int) ([]*Favorite, int, bool, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*Favorite
	var r1 int
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*Favorite, int, bool, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*Favorite); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Favorite)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) bool); ok {
		r2 = rf(ctx, userID, page, limit)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, int, int) error); ok {
		r3 = rf(ctx, userID, page, limit)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockFavoriteRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockFavoriteRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - page int
//   - limit int
func (_e *MockFavoriteRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, page interface{}, limit interface{}) *MockFavoriteRepository_ListByUserID_Call {
	return &MockFavoriteRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, page, limit)}
}

func (_c *MockFavoriteRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID string, page int, limit int)) *MockFavoriteRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockFavoriteRepository_ListByUserID_Call) Return(_a0 []*Favorite, _a1 int, _a2 bool, _a3 error) *MockFavoriteRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockFavoriteRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*Favorite, int, bool, error)) *MockFavoriteRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFavoriteRepository creates a new instance of MockFavoriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFavoriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFavoriteRepository {
	mock := &MockFavoriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
