// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	auth "summitmate/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, userID, oldPassword, newPassword, currentToken
func (_m *MockAuthService) ChangePassword(ctx context.Context, userID string, oldPassword string, newPassword string, currentToken string) error {
	ret := _m.Called(ctx, userID, oldPassword, newPassword, currentToken)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, userID, oldPassword, newPassword, currentToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockAuthService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - oldPassword string
//   - newPassword string
//   - currentToken string
func (_e *MockAuthService_Expecter) ChangePassword(ctx interface{}, userID interface{}, oldPassword interface{}, newPassword interface{}, currentToken interface{}) *MockAuthService_ChangePassword_Call {
	return &MockAuthService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, oldPassword, newPassword, currentToken)}
}

func (_c *MockAuthService_ChangePassword_Call) Run(run func(ctx context.Context, userID string, oldPassword string, newPassword string, currentToken string)) *MockAuthService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAuthService_ChangePassword_Call) Return(_a0 error) *MockAuthService_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_ChangePassword_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MockAuthService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: ctx, userID
// ClearRateLimit provides a mock function with given fields: ctx, email
func (_m *MockAuthService) ClearRateLimit(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ClearRateLimit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_ClearRateLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearRateLimit'
type MockAuthService_ClearRateLimit_Call struct {
	*mock.Call
}

// ClearRateLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthService_Expecter) ClearRateLimit(ctx interface{}, email interface{}) *MockAuthService_ClearRateLimit_Call {
	return &MockAuthService_ClearRateLimit_Call{Call: _e.mock.On("ClearRateLimit", ctx, email)}
}

func (_c *MockAuthService_ClearRateLimit_Call) Run(run func(ctx context.Context, email string)) *MockAuthService_ClearRateLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_ClearRateLimit_Call) Return(_a0 error) *MockAuthService_ClearRateLimit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_ClearRateLimit_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthService_ClearRateLimit_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *MockAuthService) DeleteAccount(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockAuthService_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthService_Expecter) DeleteAccount(ctx interface{}, userID interface{}) *MockAuthService_DeleteAccount_Call {
	return &MockAuthService_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, userID)}
}

func (_c *MockAuthService_DeleteAccount_Call) Run(run func(ctx context.Context, userID string)) *MockAuthService_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_DeleteAccount_Call) Return(_a0 error) *MockAuthService_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_DeleteAccount_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthService_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockAuthService) GetUserByID(ctx context.Context, id string) (*auth.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockAuthService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAuthService_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockAuthService_GetUserByID_Call {
	return &MockAuthService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockAuthService_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *MockAuthService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_GetUserByID_Call) Return(_a0 *auth.User, _a1 error) *MockAuthService_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_GetUserByID_Call) RunAndReturn(run func(context.Context, string) (*auth.User, error)) *MockAuthService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *MockAuthService) Login(ctx context.Context, email string, password string) (*auth.User, string, string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.User
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*auth.User, string, string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *auth.User); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) string); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string) error); ok {
		r3 = rf(ctx, email, password)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuthService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 *auth.User, _a1 string, _a2 string, _a3 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context.Context, string, string) (*auth.User, string, string, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, token
func (_m *MockAuthService) Logout(ctx context.Context, token string) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, token interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, token)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, token string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(_a0 error) *MockAuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, tokenString
func (_m *MockAuthService) RefreshToken(ctx context.Context, tokenString string) (*auth.User, string, string, error) {
	ret := _m.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *auth.User
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.User, string, string, error)); ok {
		return rf(ctx, tokenString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.User); ok {
		r0 = rf(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, tokenString)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) string); ok {
		r2 = rf(ctx, tokenString)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = rf(ctx, tokenString)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAuthService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *MockAuthService_Expecter) RefreshToken(ctx interface{}, tokenString interface{}) *MockAuthService_RefreshToken_Call {
	return &MockAuthService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, tokenString)}
}

func (_c *MockAuthService_RefreshToken_Call) Run(run func(ctx context.Context, tokenString string)) *MockAuthService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) Return(_a0 *auth.User, _a1 string, _a2 string, _a3 error) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockAuthService_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (*auth.User, string, string, error)) *MockAuthService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, password, displayName, avatar
func (_m *MockAuthService) Register(ctx context.Context, email string, password string, displayName string, avatar *string) (*auth.User, string, string, error) {
	ret := _m.Called(ctx, email, password, displayName, avatar)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.User
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) (*auth.User, string, string, error)); ok {
		return rf(ctx, email, password, displayName, avatar)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) *auth.User); ok {
		r0 = rf(ctx, email, password, displayName, avatar)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *string) string); ok {
		r1 = rf(ctx, email, password, displayName, avatar)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, *string) string); ok {
		r2 = rf(ctx, email, password, displayName, avatar)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string, string, *string) error); ok {
		r3 = rf(ctx, email, password, displayName, avatar)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - displayName string
//   - avatar *string
func (_e *MockAuthService_Expecter) Register(ctx interface{}, email interface{}, password interface{}, displayName interface{}, avatar interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, email, password, displayName, avatar)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, email string, password string, displayName string, avatar *string)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*string))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(_a0 *auth.User, _a1 string, _a2 string, _a3 error) *MockAuthService_Register_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(context.Context, string, string, string, *string) (*auth.User, string, string, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ResendVerificationCode provides a mock function with given fields: ctx, emailAddr
func (_m *MockAuthService) ResendVerificationCode(ctx context.Context, emailAddr string) error {
	ret := _m.Called(ctx, emailAddr)

	if len(ret) == 0 {
		panic("no return value specified for ResendVerificationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, emailAddr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_ResendVerificationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendVerificationCode'
type MockAuthService_ResendVerificationCode_Call struct {
	*mock.Call
}

// ResendVerificationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - emailAddr string
func (_e *MockAuthService_Expecter) ResendVerificationCode(ctx interface{}, emailAddr interface{}) *MockAuthService_ResendVerificationCode_Call {
	return &MockAuthService_ResendVerificationCode_Call{Call: _e.mock.On("ResendVerificationCode", ctx, emailAddr)}
}

func (_c *MockAuthService_ResendVerificationCode_Call) Run(run func(ctx context.Context, emailAddr string)) *MockAuthService_ResendVerificationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_ResendVerificationCode_Call) Return(_a0 error) *MockAuthService_ResendVerificationCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_ResendVerificationCode_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthService_ResendVerificationCode_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUserByEmail provides a mock function with given fields: ctx, emailAddr
func (_m *MockAuthService) SearchUserByEmail(ctx context.Context, emailAddr string) (*auth.User, error) {
	ret := _m.Called(ctx, emailAddr)

	if len(ret) == 0 {
		panic("no return value specified for SearchUserByEmail")
	}

	var r0 *auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.User, error)); ok {
		return rf(ctx, emailAddr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.User); ok {
		r0 = rf(ctx, emailAddr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, emailAddr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_SearchUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUserByEmail'
type MockAuthService_SearchUserByEmail_Call struct {
	*mock.Call
}

// SearchUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - emailAddr string
func (_e *MockAuthService_Expecter) SearchUserByEmail(ctx interface{}, emailAddr interface{}) *MockAuthService_SearchUserByEmail_Call {
	return &MockAuthService_SearchUserByEmail_Call{Call: _e.mock.On("SearchUserByEmail", ctx, emailAddr)}
}

func (_c *MockAuthService_SearchUserByEmail_Call) Run(run func(ctx context.Context, emailAddr string)) *MockAuthService_SearchUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_SearchUserByEmail_Call) Return(_a0 *auth.User, _a1 error) *MockAuthService_SearchUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_SearchUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*auth.User, error)) *MockAuthService_SearchUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, displayName, avatar
func (_m *MockAuthService) UpdateProfile(ctx context.Context, userID string, displayName *string, avatar *string) (*auth.User, error) {
	ret := _m.Called(ctx, userID, displayName, avatar)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *auth.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) (*auth.User, error)); ok {
		return rf(ctx, userID, displayName, avatar)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) *auth.User); ok {
		r0 = rf(ctx, userID, displayName, avatar)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *string, *string) error); ok {
		r1 = rf(ctx, userID, displayName, avatar)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockAuthService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - displayName *string
//   - avatar *string
func (_e *MockAuthService_Expecter) UpdateProfile(ctx interface{}, userID interface{}, displayName interface{}, avatar interface{}) *MockAuthService_UpdateProfile_Call {
	return &MockAuthService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, displayName, avatar)}
}

func (_c *MockAuthService_UpdateProfile_Call) Run(run func(ctx context.Context, userID string, displayName *string, avatar *string)) *MockAuthService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string))
	})
	return _c
}

func (_c *MockAuthService_UpdateProfile_Call) Return(_a0 *auth.User, _a1 error) *MockAuthService_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_UpdateProfile_Call) RunAndReturn(run func(context.Context, string, *string, *string) (*auth.User, error)) *MockAuthService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function with given fields: ctx, emailAddr, code
func (_m *MockAuthService) VerifyEmail(ctx context.Context, emailAddr string, code string) error {
	ret := _m.Called(ctx, emailAddr, code)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, emailAddr, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockAuthService_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - emailAddr string
//   - code string
func (_e *MockAuthService_Expecter) VerifyEmail(ctx interface{}, emailAddr interface{}, code interface{}) *MockAuthService_VerifyEmail_Call {
	return &MockAuthService_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, emailAddr, code)}
}

func (_c *MockAuthService_VerifyEmail_Call) Run(run func(ctx context.Context, emailAddr string, code string)) *MockAuthService_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_VerifyEmail_Call) Return(_a0 error) *MockAuthService_VerifyEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_VerifyEmail_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAuthService_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
