// Code generated by mockery v2.53.6. DO NOT EDIT.

package interaction

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMessageRepository is an autogenerated mock type for the MessageRepository type
type MockMessageRepository struct {
	mock.Mock
}

type MockMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepository) EXPECT() *MockMessageRepository_Expecter {
	return &MockMessageRepository_Expecter{mock: &_m.Mock}
}

// CreateMessage provides a mock function with given fields: ctx, msg
func (_m *MockMessageRepository) CreateMessage(ctx context.Context, msg *TripMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *TripMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRepository_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MockMessageRepository_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *TripMessage
func (_e *MockMessageRepository_Expecter) CreateMessage(ctx interface{}, msg interface{}) *MockMessageRepository_CreateMessage_Call {
	return &MockMessageRepository_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, msg)}
}

func (_c *MockMessageRepository_CreateMessage_Call) Run(run func(ctx context.Context, msg *TripMessage)) *MockMessageRepository_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*TripMessage))
	})
	return _c
}

func (_c *MockMessageRepository_CreateMessage_Call) Return(_a0 error) *MockMessageRepository_CreateMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRepository_CreateMessage_Call) RunAndReturn(run func(context.Context, *TripMessage) error) *MockMessageRepository_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessage provides a mock function with given fields: ctx, messageID
func (_m *MockMessageRepository) DeleteMessage(ctx context.Context, messageID string) error {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRepository_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockMessageRepository_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID string
func (_e *MockMessageRepository_Expecter) DeleteMessage(ctx interface{}, messageID interface{}) *MockMessageRepository_DeleteMessage_Call {
	return &MockMessageRepository_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", ctx, messageID)}
}

func (_c *MockMessageRepository_DeleteMessage_Call) Run(run func(ctx context.Context, messageID string)) *MockMessageRepository_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMessageRepository_DeleteMessage_Call) Return(_a0 error) *MockMessageRepository_DeleteMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRepository_DeleteMessage_Call) RunAndReturn(run func(context.Context, string) error) *MockMessageRepository_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageByID provides a mock function with given fields: ctx, messageID
func (_m *MockMessageRepository) GetMessageByID(ctx context.Context, messageID string) (*TripMessage, error) {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageByID")
	}

	var r0 *TripMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*TripMessage, error)); ok {
		return rf(ctx, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *TripMessage); ok {
		r0 = rf(ctx, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*TripMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepository_GetMessageByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageByID'
type MockMessageRepository_GetMessageByID_Call struct {
	*mock.Call
}

// GetMessageByID is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID string
func (_e *MockMessageRepository_Expecter) GetMessageByID(ctx interface{}, messageID interface{}) *MockMessageRepository_GetMessageByID_Call {
	return &MockMessageRepository_GetMessageByID_Call{Call: _e.mock.On("GetMessageByID", ctx, messageID)}
}

func (_c *MockMessageRepository_GetMessageByID_Call) Run(run func(ctx context.Context, messageID string)) *MockMessageRepository_GetMessageByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMessageRepository_GetMessageByID_Call) Return(_a0 *TripMessage, _a1 error) *MockMessageRepository_GetMessageByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepository_GetMessageByID_Call) RunAndReturn(run func(context.Context, string) (*TripMessage, error)) *MockMessageRepository_GetMessageByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListTripMessages provides a mock function with given fields: ctx, tripID, page, limit
func (_m *MockMessageRepository) ListTripMessages(ctx context.Context, tripID string, page int, limit int) ([]*TripMessage, int, bool, error) {
	ret := _m.Called(ctx, tripID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTripMessages")
	}

	var r0 []*TripMessage
	var r1 int
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*TripMessage, int, bool, error)); ok {
		return rf(ctx, tripID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*TripMessage); ok {
		r0 = rf(ctx, tripID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*TripMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, tripID, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) bool); ok {
		r2 = rf(ctx, tripID, page, limit)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, int, int) error); ok {
		r3 = rf(ctx, tripID, page, limit)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockMessageRepository_ListTripMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTripMessages'
type MockMessageRepository_ListTripMessages_Call struct {
	*mock.Call
}

// ListTripMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - page int
//   - limit int
func (_e *MockMessageRepository_Expecter) ListTripMessages(ctx interface{}, tripID interface{}, page interface{}, limit interface{}) *MockMessageRepository_ListTripMessages_Call {
	return &MockMessageRepository_ListTripMessages_Call{Call: _e.mock.On("ListTripMessages", ctx, tripID, page, limit)}
}

func (_c *MockMessageRepository_ListTripMessages_Call) Run(run func(ctx context.Context, tripID string, page int, limit int)) *MockMessageRepository_ListTripMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockMessageRepository_ListTripMessages_Call) Return(_a0 []*TripMessage, _a1 int, _a2 bool, _a3 error) *MockMessageRepository_ListTripMessages_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockMessageRepository_ListTripMessages_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*TripMessage, int, bool, error)) *MockMessageRepository_ListTripMessages_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMessage provides a mock function with given fields: ctx, msg
func (_m *MockMessageRepository) UpdateMessage(ctx context.Context, msg *TripMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *TripMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageRepository_UpdateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMessage'
type MockMessageRepository_UpdateMessage_Call struct {
	*mock.Call
}

// UpdateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *TripMessage
func (_e *MockMessageRepository_Expecter) UpdateMessage(ctx interface{}, msg interface{}) *MockMessageRepository_UpdateMessage_Call {
	return &MockMessageRepository_UpdateMessage_Call{Call: _e.mock.On("UpdateMessage", ctx, msg)}
}

func (_c *MockMessageRepository_UpdateMessage_Call) Run(run func(ctx context.Context, msg *TripMessage)) *MockMessageRepository_UpdateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*TripMessage))
	})
	return _c
}

func (_c *MockMessageRepository_UpdateMessage_Call) Return(_a0 error) *MockMessageRepository_UpdateMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageRepository_UpdateMessage_Call) RunAndReturn(run func(context.Context, *TripMessage) error) *MockMessageRepository_UpdateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageRepository creates a new instance of MockMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepository {
	mock := &MockMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
