// Code generated by mockery v2.53.6. DO NOT EDIT.

package interaction

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPollRepository is an autogenerated mock type for the PollRepository type
type MockPollRepository struct {
	mock.Mock
}

type MockPollRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPollRepository) EXPECT() *MockPollRepository_Expecter {
	return &MockPollRepository_Expecter{mock: &_m.Mock}
}

// AddPollOption provides a mock function with given fields: ctx, option
func (_m *MockPollRepository) AddPollOption(ctx context.Context, option *PollOption) error {
	ret := _m.Called(ctx, option)

	if len(ret) == 0 {
		panic("no return value specified for AddPollOption")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *PollOption) error); ok {
		r0 = rf(ctx, option)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPollRepository_AddPollOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPollOption'
type MockPollRepository_AddPollOption_Call struct {
	*mock.Call
}

// AddPollOption is a helper method to define mock.On call
//   - ctx context.Context
//   - option *PollOption
func (_e *MockPollRepository_Expecter) AddPollOption(ctx interface{}, option interface{}) *MockPollRepository_AddPollOption_Call {
	return &MockPollRepository_AddPollOption_Call{Call: _e.mock.On("AddPollOption", ctx, option)}
}

func (_c *MockPollRepository_AddPollOption_Call) Run(run func(ctx context.Context, option *PollOption)) *MockPollRepository_AddPollOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*PollOption))
	})
	return _c
}

func (_c *MockPollRepository_AddPollOption_Call) Return(_a0 error) *MockPollRepository_AddPollOption_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPollRepository_AddPollOption_Call) RunAndReturn(run func(context.Context, *PollOption) error) *MockPollRepository_AddPollOption_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePoll provides a mock function with given fields: ctx, poll
func (_m *MockPollRepository) CreatePoll(ctx context.Context, poll *Poll) error {
	ret := _m.Called(ctx, poll)

	if len(ret) == 0 {
		panic("no return value specified for CreatePoll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Poll) error); ok {
		r0 = rf(ctx, poll)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPollRepository_CreatePoll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePoll'
type MockPollRepository_CreatePoll_Call struct {
	*mock.Call
}

// CreatePoll is a helper method to define mock.On call
//   - ctx context.Context
//   - poll *Poll
func (_e *MockPollRepository_Expecter) CreatePoll(ctx interface{}, poll interface{}) *MockPollRepository_CreatePoll_Call {
	return &MockPollRepository_CreatePoll_Call{Call: _e.mock.On("CreatePoll", ctx, poll)}
}

func (_c *MockPollRepository_CreatePoll_Call) Run(run func(ctx context.Context, poll *Poll)) *MockPollRepository_CreatePoll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Poll))
	})
	return _c
}

func (_c *MockPollRepository_CreatePoll_Call) Return(_a0 error) *MockPollRepository_CreatePoll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPollRepository_CreatePoll_Call) RunAndReturn(run func(context.Context, *Poll) error) *MockPollRepository_CreatePoll_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePoll provides a mock function with given fields: ctx, pollID
func (_m *MockPollRepository) DeletePoll(ctx context.Context, pollID string) error {
	ret := _m.Called(ctx, pollID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePoll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, pollID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPollRepository_DeletePoll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePoll'
type MockPollRepository_DeletePoll_Call struct {
	*mock.Call
}

// DeletePoll is a helper method to define mock.On call
//   - ctx context.Context
//   - pollID string
func (_e *MockPollRepository_Expecter) DeletePoll(ctx interface{}, pollID interface{}) *MockPollRepository_DeletePoll_Call {
	return &MockPollRepository_DeletePoll_Call{Call: _e.mock.On("DeletePoll", ctx, pollID)}
}

func (_c *MockPollRepository_DeletePoll_Call) Run(run func(ctx context.Context, pollID string)) *MockPollRepository_DeletePoll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPollRepository_DeletePoll_Call) Return(_a0 error) *MockPollRepository_DeletePoll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPollRepository_DeletePoll_Call) RunAndReturn(run func(context.Context, string) error) *MockPollRepository_DeletePoll_Call {
	_c.Call.Return(run)
	return _c
}

// GetPollByID provides a mock function with given fields: ctx, pollID
func (_m *MockPollRepository) GetPollByID(ctx context.Context, pollID string) (*Poll, error) {
	ret := _m.Called(ctx, pollID)

	if len(ret) == 0 {
		panic("no return value specified for GetPollByID")
	}

	var r0 *Poll
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Poll, error)); ok {
		return rf(ctx, pollID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Poll); ok {
		r0 = rf(ctx, pollID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Poll)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pollID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPollRepository_GetPollByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPollByID'
type MockPollRepository_GetPollByID_Call struct {
	*mock.Call
}

// GetPollByID is a helper method to define mock.On call
//   - ctx context.Context
//   - pollID string
func (_e *MockPollRepository_Expecter) GetPollByID(ctx interface{}, pollID interface{}) *MockPollRepository_GetPollByID_Call {
	return &MockPollRepository_GetPollByID_Call{Call: _e.mock.On("GetPollByID", ctx, pollID)}
}

func (_c *MockPollRepository_GetPollByID_Call) Run(run func(ctx context.Context, pollID string)) *MockPollRepository_GetPollByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPollRepository_GetPollByID_Call) Return(_a0 *Poll, _a1 error) *MockPollRepository_GetPollByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPollRepository_GetPollByID_Call) RunAndReturn(run func(context.Context, string) (*Poll, error)) *MockPollRepository_GetPollByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPollOption provides a mock function with given fields: ctx, optionID
func (_m *MockPollRepository) GetPollOption(ctx context.Context, optionID string) (*PollOption, error) {
	ret := _m.Called(ctx, optionID)

	if len(ret) == 0 {
		panic("no return value specified for GetPollOption")
	}

	var r0 *PollOption
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*PollOption, error)); ok {
		return rf(ctx, optionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *PollOption); ok {
		r0 = rf(ctx, optionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PollOption)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, optionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPollRepository_GetPollOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPollOption'
type MockPollRepository_GetPollOption_Call struct {
	*mock.Call
}

// GetPollOption is a helper method to define mock.On call
//   - ctx context.Context
//   - optionID string
func (_e *MockPollRepository_Expecter) GetPollOption(ctx interface{}, optionID interface{}) *MockPollRepository_GetPollOption_Call {
	return &MockPollRepository_GetPollOption_Call{Call: _e.mock.On("GetPollOption", ctx, optionID)}
}

func (_c *MockPollRepository_GetPollOption_Call) Run(run func(ctx context.Context, optionID string)) *MockPollRepository_GetPollOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPollRepository_GetPollOption_Call) Return(_a0 *PollOption, _a1 error) *MockPollRepository_GetPollOption_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPollRepository_GetPollOption_Call) RunAndReturn(run func(context.Context, string) (*PollOption, error)) *MockPollRepository_GetPollOption_Call {
	_c.Call.Return(run)
	return _c
}

// ListTripPolls provides a mock function with given fields: ctx, tripID, page, limit
func (_m *MockPollRepository) ListTripPolls(ctx context.Context, tripID string, page int, limit int) ([]*Poll, int, bool, error) {
	ret := _m.Called(ctx, tripID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTripPolls")
	}

	var r0 []*Poll
	var r1 int
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*Poll, int, bool, error)); ok {
		return rf(ctx, tripID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*Poll); ok {
		r0 = rf(ctx, tripID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Poll)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, tripID, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) bool); ok {
		r2 = rf(ctx, tripID, page, limit)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, int, int) error); ok {
		r3 = rf(ctx, tripID, page, limit)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockPollRepository_ListTripPolls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTripPolls'
type MockPollRepository_ListTripPolls_Call struct {
	*mock.Call
}

// ListTripPolls is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - page int
//   - limit int
func (_e *MockPollRepository_Expecter) ListTripPolls(ctx interface{}, tripID interface{}, page interface{}, limit interface{}) *MockPollRepository_ListTripPolls_Call {
	return &MockPollRepository_ListTripPolls_Call{Call: _e.mock.On("ListTripPolls", ctx, tripID, page, limit)}
}

func (_c *MockPollRepository_ListTripPolls_Call) Run(run func(ctx context.Context, tripID string, page int, limit int)) *MockPollRepository_ListTripPolls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockPollRepository_ListTripPolls_Call) Return(_a0 []*Poll, _a1 int, _a2 bool, _a3 error) *MockPollRepository_ListTripPolls_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockPollRepository_ListTripPolls_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*Poll, int, bool, error)) *MockPollRepository_ListTripPolls_Call {
	_c.Call.Return(run)
	return _c
}

// VoteOption provides a mock function with given fields: ctx, pollID, optionID, userID, allowMultiple
func (_m *MockPollRepository) VoteOption(ctx context.Context, pollID string, optionID string, userID string, allowMultiple bool) error {
	ret := _m.Called(ctx, pollID, optionID, userID, allowMultiple)

	if len(ret) == 0 {
		panic("no return value specified for VoteOption")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) error); ok {
		r0 = rf(ctx, pollID, optionID, userID, allowMultiple)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPollRepository_VoteOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VoteOption'
type MockPollRepository_VoteOption_Call struct {
	*mock.Call
}

// VoteOption is a helper method to define mock.On call
//   - ctx context.Context
//   - pollID string
//   - optionID string
//   - userID string
//   - allowMultiple bool
func (_e *MockPollRepository_Expecter) VoteOption(ctx interface{}, pollID interface{}, optionID interface{}, userID interface{}, allowMultiple interface{}) *MockPollRepository_VoteOption_Call {
	return &MockPollRepository_VoteOption_Call{Call: _e.mock.On("VoteOption", ctx, pollID, optionID, userID, allowMultiple)}
}

func (_c *MockPollRepository_VoteOption_Call) Run(run func(ctx context.Context, pollID string, optionID string, userID string, allowMultiple bool)) *MockPollRepository_VoteOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *MockPollRepository_VoteOption_Call) Return(_a0 error) *MockPollRepository_VoteOption_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPollRepository_VoteOption_Call) RunAndReturn(run func(context.Context, string, string, string, bool) error) *MockPollRepository_VoteOption_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPollRepository creates a new instance of MockPollRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPollRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPollRepository {
	mock := &MockPollRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
